Repository voxel51/fiftyone, pull requests merged in 2020-10, with the labels that each got.

#573 Hotfix
  fiftyone/core/dataset.py
Labels: bug

#574 Bump v0.6.0.1
  setup.py
Labels: setup

#565 Adding support for importing/exporting datasets in YOLO format
  docs/source/recipes/convert_datasets.ipynb
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_creation/index.rst
  docs/source/user_guide/dataset_creation/samples.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/types/dataset_types.py
  fiftyone/utils/yolo.py
  tests/import_export/dataset_tests.py
Labels: feature

#575 Docs fixes
  docs/source/_static/css/custom.css
  fiftyone/core/odm/mixins.py
Labels: bug, documentation

#551 Adding a recipe for merging datasets
  CONTRIBUTING.md
  ISSUE_POLICY.md
  README.md
  docs/source/_static/images/recipes/merge_datasets.png
  docs/source/cli/index.rst
  docs/source/images/homepage1.png
  docs/source/images/homepage2.png
  docs/source/recipes/index.rst
  docs/source/recipes/merge_datasets.ipynb
  examples/evaluate_detections.md
  examples/image_uniqueness.md
  examples/wrangling_datasets.md
  fiftyone/__public__.py
  fiftyone/core/cli.py
  fiftyone/core/dataset.py
  install.bash
Labels: documentation, enhancement

#586 Including frame field schemas in summaries for video datasets/views
  fiftyone/core/dataset.py
  fiftyone/core/sample.py
  fiftyone/core/view.py
Labels: enhancement

#582 App fixes
  electron/app/components/NumericFieldFilter.tsx
  electron/app/components/RangeSlider.tsx
  electron/app/components/ViewBar/ViewBar.tsx
  electron/app/components/ViewBar/ViewStage/ViewStage.tsx
  electron/app/components/ViewBar/ViewStage/ViewStageParameter.tsx
  electron/app/components/ViewBar/ViewStage/utils.ts
  electron/app/components/ViewBar/ViewStage/viewStageParameterMachine.ts
  electron/app/components/ViewBar/viewBarMachine.ts
  fiftyone/core/stages.py
Labels: app

#589 Adding support for importing/exporting video datasets in FiftyOneDataset format
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/sample.py
  fiftyone/types/dataset_types.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
Labels: feature

#581 Eval updates
  fiftyone/utils/eval/coco.py
Labels: core, enhancement

#588 Release 0.6.1
  .github/workflows/build-docs.yml
  .github/workflows/build.yml
  docs/source/release-notes.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/export_datasets.rst
  electron/app/package.json
  electron/package.json
  package/gui/setup.py
  setup.py
Labels: setup

#595 Allowing missing media_type when importing FiftyOneDataset
  fiftyone/core/dataset.py
  fiftyone/utils/data/importers.py
Labels: bug

#596 0.6.1.1
  setup.py
Labels: setup

#594 Adding support for filtering polylines and keypoints
  docs/source/user_guide/using_views.rst
  electron/app/components/Filter.tsx
  fiftyone/core/collections.py
  fiftyone/core/stages.py
  fiftyone/server/main.py
Labels: feature

#593 Raising an informative error when `Dataset.add_samples()` fails
  fiftyone/core/dataset.py
Labels: feature

#598 Data model improvements
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/fields.py
  fiftyone/core/frame.py
  fiftyone/core/frame_utils.py
  fiftyone/core/odm/frame.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/odm/sample.py
  fiftyone/core/sample.py
Labels: enhancement

#592 Adding support for importing/exporting polylines in COCO/CVAT formats
  docs/source/recipes/convert_datasets.ipynb
  docs/source/recipes/custom_exporter.ipynb
  docs/source/recipes/custom_importer.ipynb
  docs/source/recipes/custom_parser.ipynb
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_creation/samples.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/expressions.py
  fiftyone/core/frame.py
  fiftyone/core/labels.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/sample.py
  fiftyone/resources/cvat_image_annotation_template.xml
  fiftyone/resources/cvat_video_interpolation_template.xml
  fiftyone/types/dataset_types.py
  fiftyone/utils/bdd.py
  fiftyone/utils/coco.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/data/ingestors.py
  fiftyone/utils/data/parsers.py
Labels: feature

#603 Adding scikit-image as dependency
  requirements/common.txt
  setup.py
Labels: bug

#601 [WIP] Adding support for storing multiple shapes in a Polyline instance
  docs/source/user_guide/using_datasets.rst
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/fields.py
  fiftyone/core/labels.py
  fiftyone/core/stages.py
  fiftyone/migrations/revisions/v0_6_2.py
  fiftyone/utils/bdd.py
  fiftyone/utils/coco.py
  fiftyone/utils/cvat.py
Labels: enhancement

#608 v0.6.2 kitchen sink
  docs/source/user_guide/basics.rst
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/core/dataset.py
  fiftyone/core/frame.py
  fiftyone/core/labels.py
  fiftyone/core/view.py
  fiftyone/migrations/revisions/v0_6_2.py
  fiftyone/utils/data/base.py
  tests/README.md
  tests/isolated/import_deps_test.py
  tests/isolated/import_time_test.py
  tests/isolated/service_tests.py
  tests/session_tests.py
  tests/unittests/dataset_tests.py
  tests/unittests/decorators.py
  tests/unittests/sample_tests.py
  tests/unittests/synchronization_tests.py
  tests/unittests/utils_tests.py
  tests/unittests/view_tests.py
  tests/utils/command_wrapper.py
  tests/utils/github_actions_flags.py
  tests/utils/interactive_python.py
  tests/utils/pytest_wrapper.py
  tests/utils/session_helper.py
  tests/utils/setup_config.py
Labels: documentation, enhancement

#614 Docs: clarify that Python 3.9 is not yet supported
  docs/source/getting_started/install.rst
  docs/source/getting_started/troubleshooting.rst
Labels: documentation

#612 Adding VideoClassificationDirectoryTree, HMDB51, UCF101, BDD100k, and COCO w/ segmentations
  docs/source/_includes/substitutions.rst
  docs/source/user_guide/basics.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_creation/index.rst
  docs/source/user_guide/dataset_creation/samples.rst
  docs/source/user_guide/dataset_creation/zoo.rst
  docs/source/user_guide/export_datasets.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/eta_utils.py
  fiftyone/core/fields.py
  fiftyone/core/labels.py
  fiftyone/core/media.py
  fiftyone/core/sample.py
  fiftyone/types/dataset_types.py
  fiftyone/utils/bdd.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/base.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/data/ingestors.py
  fiftyone/utils/data/parsers.py
  fiftyone/utils/hmdb51.py
  fiftyone/utils/imagenet.py
  fiftyone/utils/ucf101.py
  fiftyone/zoo/__init__.py
  fiftyone/zoo/base.py
  fiftyone/zoo/tf.py
  fiftyone/zoo/torch.py
  tests/README.md
  tests/import_export/dataset_tests.py
  tests/unittests/utils_tests.py
Labels: feature

#615 Adding support for only including samples that match filters
  docs/source/user_guide/using_views.rst
  fiftyone/core/collections.py
  fiftyone/core/stages.py
Labels: feature

#616 Adding utility for selecting objects from datasets
  fiftyone/utils/selection.py
  tests/README.md
  tests/misc/selection_tests.py
Labels: feature

#620 Allow for insertion case when saving frames
  fiftyone/core/dataset.py
  fiftyone/core/frame.py
Labels: bug, core, enhancement

#619 Minimal sample-level labels support for video datasets in the App
  electron/app/components/SampleModal.tsx
  electron/app/recoil/selectors.ts
  fiftyone/core/dataset.py
  fiftyone/core/frame.py
  fiftyone/core/state.py
  fiftyone/server/main.py
Labels: app

#617 Adding util to re-encode videos in a sample collection
  electron/app/components/Player51.tsx
  fiftyone/utils/data/importers.py
  fiftyone/utils/video.py
Labels: feature

#621 v0.6.3 release
  docs/source/_static/css/custom.css
  docs/source/_static/css/voxel51-website.css
  docs/source/_templates/layout.html
  docs/source/conf.py
  docs/source/release-notes.rst
  package/gui/setup.py
  setup.py
Labels: release

#625 Fix hash change detection
  electron/app/containers/App.tsx
  electron/app/utils/hooks.ts
Labels: app, bug

#623 Adding utils for working with image patches in Torch
  fiftyone/core/dataset.py
  fiftyone/core/labels.py
  fiftyone/utils/torch.py
  tests/misc/torch_tests.py
Labels: feature

#638 Fixing ObjectId bug in selection utils
  fiftyone/core/expressions.py
  fiftyone/core/labels.py
  fiftyone/core/odm/document.py
  fiftyone/core/stages.py
  fiftyone/utils/selection.py
Labels: bug

#643 Adding support for filtering generic label fields, limiting labels, and other related expressions
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/expressions.py
  fiftyone/core/frame_utils.py
  fiftyone/core/stages.py
  fiftyone/core/state.py
  tests/unittests/view_tests.py
Labels: feature

#642 Docs updates
  docs/source/_templates/layout.html
  docs/source/conf.py
  docs/source/release-notes.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_creation/samples.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/server/main.py
  fiftyone/types/dataset_types.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
Labels: documentation

#645 Allow clearing hidden objects in filter widgets
  electron/app/components/CheckboxGrid.tsx
  electron/app/components/Filter.tsx
  electron/app/components/SampleModal.tsx
  electron/app/components/SelectObjectsMenu.tsx
  electron/app/recoil/atoms.ts
  electron/app/recoil/selectors.ts
  electron/app/utils/context.ts
Labels: app, enhancement

#624 Adding support for adding, renaming, and deleting frame fields
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/frame.py
  fiftyone/core/odm/mixins.py
Labels: feature

#648 Converting object selection to ViewStages, and adding documentation
  docs/source/images/coco2017_selected.png
  docs/source/user_guide/app.rst
  fiftyone/core/collections.py
  fiftyone/core/session.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
  fiftyone/server/main.py
  fiftyone/utils/selection.py
  tests/misc/selection_tests.py
Labels: documentation, feature

#650 Release v0.6.4
  docs/source/release-notes.rst
  electron/app/components/SampleModal.tsx
  electron/app/components/Samples.hooks.ts
  electron/app/components/Samples.tsx
  electron/app/containers/Dataset.tsx
  electron/app/package.json
  electron/app/utils/tile.ts
  electron/package.json
  fiftyone/core/aggregations.py
  fiftyone/core/frame.py
  fiftyone/core/session.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
  package/gui/setup.py
  setup.py
Labels: release
