Repository voxel51/fiftyone, pull requests merged in 2020-08, with the labels that each got.

#375 Remove deleted branch from Chromatic workflow PR branches
  .github/workflows/chromatic.yml
Labels: cleaning

#374 App: Fixes adding ViewStages to the ViewBar
  electron/app/components/ViewBar/ViewStage/viewStageMachine.ts
Labels: app, bug

#382 App: Fit last row to match tiling threshold in samples list
  electron/app/utils/tile.ts
Labels: app, bug

#384 Sidebar improvements
  electron/app/components/CheckboxGrid.tsx
  electron/app/components/DisplayOptionsSidebar.tsx
  electron/app/components/ImageContainerHeader.tsx
  electron/app/components/Sample.tsx
  electron/app/components/Tags/SelectionTag.tsx
  electron/app/containers/SamplesContainer.tsx
  electron/app/utils/hooks.ts
Labels: app, enhancement

#383 Fix session updates from App changes
  fiftyone/core/session.py
  tests/isolated/server_tests.py
Labels: app, bug, core, enhancement

#379 Open Images Evaluation Tutorial
  docs/source/_static/images/tutorials/missing_wheel.gif
  docs/source/tutorials/images/open_images_eval.jpg
  docs/source/tutorials/images/open_images_pre_eval.gif
  docs/source/tutorials/images/tucan.jpg
  docs/source/tutorials/index.rst
  docs/source/tutorials/open_images_eval/error_analysis/evaluation.py
  docs/source/tutorials/open_images_eval/error_analysis/inference/tfhub.py
  docs/source/tutorials/open_images_eval/error_analysis/load_data.py
  docs/source/tutorials/open_images_eval/scripts/evaluate_model.py
  docs/source/tutorials/open_images_eval/scripts/inference.py
  docs/source/tutorials/open_images_eval/scripts/load_data.py
  docs/source/tutorials/open_images_evaluation.ipynb
  fiftyone/zoo/__init__.py
Labels: documentation

#392 App cleanup
  electron/app/components/CheckboxGrid.stories.tsx
  electron/app/components/CodeBlock.tsx
  electron/app/components/DisplayOptionsSidebar.stories.tsx
  electron/app/components/Distributions.tsx
  electron/app/components/Header.tsx
  electron/app/components/ImageContainerHeader.stories.tsx
  electron/app/components/InfoItem.tsx
  electron/app/components/JSONView.tsx
  electron/app/components/Labels.tsx
  electron/app/components/Player51.tsx
  electron/app/components/PortForm.tsx
  electron/app/components/Rendering.tsx
  electron/app/components/Sample.tsx
  electron/app/components/Samples.tsx
  electron/app/components/Search.tsx
  electron/app/components/Sidebar.tsx
  electron/app/components/Tags.tsx
  electron/app/components/Tags/SelectionTag.tsx
  electron/app/components/utils.tsx
  electron/app/containers/App.tsx
  electron/app/containers/Dataset.tsx
Labels: cleaning

#393 Renaming list_dataset_names() to list_datasets()
  docs/source/user_guide/using_datasets.rst
  fiftyone/__public__.py
  fiftyone/core/cli.py
  fiftyone/core/dataset.py
  tests/unittests.py
Labels: enhancement

#394 Allowing a single sample ID in Select() and Exclude() stages
  fiftyone/core/collections.py
  fiftyone/core/stages.py
Labels: enhancement

#397 Adding more string operations
  fiftyone/core/expressions.py
  tests/README.md
  tests/db_conn_test.py
  tests/isolated/README.txt
  tests/stage_tests.py
  tests/unittests.py
Labels: enhancement

#405 Adding sample fields to `dir(Sample)`
  fiftyone/core/sample.py
Labels: enhancement

#408 Adding ProgresssBar to public namespace
  docs/source/tutorials/evaluate_detections.ipynb
  fiftyone/__public__.py
Labels: enhancement

#409 Allowing zoo datasets to be loaded with custom names
  fiftyone/zoo/__init__.py
Labels: enhancement

#406 Dataset.iter_samples() 10X faster
  fiftyone/core/dataset.py
Labels: enhancement

#404 Dataset/View stats bugs
  electron/app/recoil/selectors.ts
  fiftyone/core/dataset.py
  fiftyone/core/odm/sample.py
  fiftyone/core/state.py
  fiftyone/core/view.py
  fiftyone/server/main.py
  tests/isolated/server_tests.py
Labels: bug

#410 Including pycocotools as explicit dependency
  fiftyone/core/utils.py
  fiftyone/utils/eval/coco.py
  fiftyone/zoo/torch.py
  requirements/common.txt
  setup.py
Labels: bug, enhancement

#407 Adding support for renaming and cloning datasets
  fiftyone/core/dataset.py
  fiftyone/core/odm/database.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/odm/sample.py
  fiftyone/core/sample.py
  fiftyone/core/view.py
  tests/unittests.py
Labels: feature

#413 View bar feedback part 2
  electron/app/components/ViewBar/ViewBar.tsx
  electron/app/components/ViewBar/ViewStage/ErrorMessage.tsx
  electron/app/components/ViewBar/ViewStage/ViewStage.tsx
  electron/app/components/ViewBar/ViewStage/ViewStageParameter.tsx
  electron/app/components/ViewBar/ViewStage/viewStageMachine.ts
  electron/app/components/ViewBar/ViewStage/viewStageParameterMachine.ts
  electron/app/components/ViewBar/viewBarMachine.ts
  electron/app/shared/colors.ts
Labels: app, bug, enhancement

#414 Adding support for importing and exporting datasets with empty label fields
  docs/source/recipes/custom_importer.ipynb
  docs/source/user_guide/dataset_creation/datasets.rst
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/fields.py
  fiftyone/core/odm/sample.py
  fiftyone/core/view.py
  fiftyone/resources/cvat_image_annotation_template.xml
  fiftyone/types/dataset_types.py
  fiftyone/utils/bdd.py
  fiftyone/utils/coco.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/data/ingestors.py
  fiftyone/utils/data/parsers.py
  fiftyone/utils/kitti.py
  fiftyone/utils/tf.py
  fiftyone/utils/voc.py
  fiftyone/zoo/tf.py
  tests/import_export_tests.py
Labels: feature

#416 Release notes for v0.5.1
  docs/source/images/empty_app.png
  docs/source/release-notes.rst
  docs/source/substitutions.rst
  docs/source/tutorials/index.rst
  docs/source/tutorials/open_images_evaluation.ipynb
  docs/source/user_guide/app.rst
  docs/source/user_guide/basics.rst
  docs/source/user_guide/using_views.rst
  electron/app/components/Sample.tsx
  fiftyone/core/session.py
  fiftyone/types/dataset_types.py
  package/gui/setup.py
  setup.py
Labels: documentation

#422 Preventing `None` dataset names
  fiftyone/core/cli.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/dataset.py
Labels: bug, enhancement

#426 Expand troubleshooting docs
  .github/workflows/build-docs.yml
  README.md
  docs/source/conf.py
  docs/source/getting_started/install.rst
  docs/source/getting_started/troubleshooting.rst
Labels: documentation

#428 Adding View stage examples to docs
  fiftyone/core/collections.py
  fiftyone/core/expressions.py
  fiftyone/core/stages.py
Labels: feature

#435 Docs updates for importing/exporting datasets with no labels
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/types/dataset_types.py
  fiftyone/utils/bdd.py
  fiftyone/utils/coco.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/importers.py
Labels: documentation

#443 Display a friendly error when using the dataset zoo with no ML backend installed
  docs/source/user_guide/dataset_creation/zoo.rst
  fiftyone/core/cli.py
  fiftyone/core/utils.py
  fiftyone/zoo/__init__.py
  fiftyone/zoo/tf.py
  fiftyone/zoo/torch.py
Labels: enhancement

#446 Revert "installing pycocotools by default"
  fiftyone/core/utils.py
  fiftyone/utils/eval/coco.py
  fiftyone/zoo/torch.py
  requirements/common.txt
  setup.py
Labels: setup

#438 Adding getting started walkthrough
  README.md
  WALKTHROUGH.md
Labels: documentation

#445 Adding a FiftyOne quickstart
  README.md
  docs/source/cli/index.rst
  docs/source/getting_started/install.rst
  docs/source/getting_started/troubleshooting.rst
  fiftyone/__public__.py
  fiftyone/core/cli.py
  fiftyone/core/utils.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/quickstart.py
  fiftyone/zoo/__init__.py
  fiftyone/zoo/base.py
Labels: feature

#436 Adding support for importing/exporting multitask image label dataset with per-label fields
  docs/source/recipes/custom_exporter.ipynb
  docs/source/recipes/custom_importer.ipynb
  docs/source/recipes/custom_parser.ipynb
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_creation/samples.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/labels.py
  fiftyone/core/sample.py
  fiftyone/utils/bdd.py
  fiftyone/utils/data/base.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/data/parsers.py
  tests/import_export_tests.py
  tests/unittests.py
Labels: feature

#449 Docs images
  docs/source/_static/images/tutorials/evaluate_detections.png
  docs/source/images/dataset-basics.png
  docs/source/images/dog.png
  docs/source/images/label_mistakes.png
  docs/source/images/uniqueness.png
  docs/source/recipes/images/dedup_1.png
  docs/source/recipes/images/dedup_2.png
  docs/source/recipes/images/dedup_3.png
  docs/source/recipes/images/dedup_4.png
  docs/source/recipes/images/dedup_5.png
  docs/source/recipes/images/inference_1.png
  docs/source/recipes/images/inference_2.png
  docs/source/recipes/images/inference_3.png
  docs/source/recipes/images/inference_4.png
  docs/source/tutorials/images/label_mistakes_1.png
  docs/source/tutorials/images/label_mistakes_2.png
  docs/source/tutorials/images/label_mistakes_3.png
  docs/source/tutorials/images/label_mistakes_4.png
  docs/source/tutorials/images/uniqueness_1.png
  docs/source/tutorials/images/uniqueness_2.png
  docs/source/tutorials/images/uniqueness_3.png
  docs/source/tutorials/images/uniqueness_4.png
  docs/source/user_guide/basics.rst
  fiftyone/core/stages.py
Labels: documentation

#456 Evaluating Object Detections tutorial update
  docs/source/tutorials/evaluate_detections.ipynb
  docs/source/tutorials/images/eval_dets/coco_gt.png
  docs/source/tutorials/images/eval_dets/crowded_sorted.png
  docs/source/tutorials/images/eval_dets/crowded_view.png
  docs/source/tutorials/images/eval_dets/eval_dets_1.png
  docs/source/tutorials/images/eval_dets/eval_dets_2.png
  docs/source/tutorials/images/eval_dets/eval_dets_3.png
  docs/source/tutorials/images/eval_dets/eval_dets_4.png
  docs/source/tutorials/images/eval_dets/eval_dets_5.png
  docs/source/tutorials/images/eval_dets/eval_dets_6.png
  docs/source/tutorials/images/eval_dets/eval_dets_7.png
  docs/source/tutorials/images/eval_dets/eval_dets_8.png
  docs/source/tutorials/images/eval_dets/fp_rev.png
  docs/source/tutorials/images/eval_dets/launch_app.png
  docs/source/tutorials/images/eval_dets/selected.png
  docs/source/tutorials/images/eval_dets/small_view.png
  docs/source/tutorials/images/eval_dets/tp_rev.png
Labels: documentation

#454 Add more links to header
  electron/app/components/Header.tsx
  electron/app/icons.tsx
Labels: app, enhancement

#441 Multiple DB session support
  .github/workflows/build.yml
  docs/source/user_guide/using_datasets.rst
  electron/app/components/PortForm.tsx
  electron/app/index.tsx
  electron/app/recoil/atoms.ts
  electron/app/reducers/update.ts
  fiftyone/core/odm/database.py
  fiftyone/core/service.py
  fiftyone/core/session.py
  fiftyone/server/main.py
  fiftyone/service/__init__.py
  fiftyone/service/ipc.py
  fiftyone/service/main.py
  fiftyone/service/util.py
  tests/db_conn_test.py
  tests/ipc_tests.py
  tests/isolated/service_tests.py
  tests/unittests.py
  tests/utils/interactive_python.py
  tests/utils/pytest_wrapper.py
Labels: bug, feature

#460 Filtering fixes and tweaks
  electron/app/components/Filter.tsx
  electron/app/components/ViewBar/ViewStage/SearchResults.tsx
Labels: app

#457 v0.5.2 release notes
  docs/source/getting_started/install.rst
  docs/source/release-notes.rst
  docs/source/user_guide/config.rst
  docs/source/user_guide/dataset_creation/zoo.rst
  package/gui/setup.py
  setup.py
Labels: documentation

#461 Bump to 0.5.2
  setup.py
Labels: setup

#478 subprocess error handling improvements
  fiftyone/core/service.py
  fiftyone/service/main.py
Labels: bug

#480 Improve colors
  electron/app/Routes.tsx
  electron/app/components/DisplayOptionsSidebar.tsx
  electron/app/components/Player51.tsx
  electron/app/components/Sample.tsx
  electron/app/components/SampleModal.stories.tsx
  electron/app/components/SampleModal.tsx
  electron/app/components/Samples.tsx
  electron/app/components/utils.tsx
  electron/app/containers/Dataset.tsx
  electron/app/containers/SamplesContainer.tsx
  electron/app/recoil/atoms.ts
  electron/app/recoil/selectors.ts
  electron/app/utils/colors.ts
Labels: enhancement
