Repository voxel51/fiftyone, pull requests merged in 2020-12, with the labels that each got.

#704 Clarifying image format support
  docs/source/faq/index.rst
Labels: documentation

#702 Model zoo
  .github/workflows/build-docs.yml
  .github/workflows/build.yml
  docs/source/_includes/substitutions.rst
  docs/source/cli/index.rst
  docs/source/images/dataset_zoo_coco_2017.png
  docs/source/images/model_zoo_predictions_coco_2017.png
  docs/source/recipes/convert_datasets.ipynb
  docs/source/recipes/draw_labels.ipynb
  docs/source/recipes/merge_datasets.ipynb
  docs/source/recipes/model_inference.ipynb
  docs/source/redirects
  docs/source/user_guide/config.rst
  docs/source/user_guide/dataset_creation/index.rst
  docs/source/user_guide/dataset_zoo.rst
  docs/source/user_guide/index.rst
  docs/source/user_guide/model_zoo.rst
  fiftyone/__public__.py
  fiftyone/constants.py
  fiftyone/core/cli.py
  fiftyone/core/collections.py
  fiftyone/core/config.py
  fiftyone/core/eta_utils.py
  fiftyone/core/labels.py
  fiftyone/core/models.py
  fiftyone/core/sample.py
  fiftyone/core/utils.py
  fiftyone/core/validation.py
  fiftyone/utils/bdd.py
  fiftyone/utils/cityscapes.py
  fiftyone/utils/imagenet.py
  fiftyone/utils/quickstart.py
  fiftyone/utils/torch.py
  fiftyone/zoo/__init__.py
  fiftyone/zoo/datasets/__init__.py
  fiftyone/zoo/datasets/base.py
  fiftyone/zoo/datasets/tf.py
  fiftyone/zoo/datasets/torch.py
  fiftyone/zoo/models/__init__.py
  fiftyone/zoo/models/manifest.json
  fiftyone/zoo/models/torch.py
  setup.py
  tests/import_export/model_tests.py
  tests/misc/torch_tests.py
Labels: core, feature

#714 Docs updates for colab launch
  docs/source/cli/index.rst
  docs/source/environments/index.rst
  docs/source/faq/index.rst
  docs/source/getting_started/install.rst
  docs/source/release-notes.rst
  docs/source/user_guide/app.rst
  docs/source/user_guide/config.rst
  docs/source/user_guide/using_views.rst
  fiftyone/core/cli.py
  fiftyone/core/config.py
  fiftyone/core/context.py
  fiftyone/core/session.py
  fiftyone/core/view.py
  fiftyone/utils/quickstart.py
Labels: documentation

#708 In-App feedback
  app/src/components/Header.tsx
  app/src/components/NotificationHub/NotificationHub.tsx
  app/src/containers/App.tsx
  app/src/recoil/atoms.ts
Labels: app, enhancement

#717 Session tweaks
  docs/source/environments/index.rst
  docs/source/faq/index.rst
  docs/source/getting_started/install.rst
  docs/source/getting_started/troubleshooting.rst
  fiftyone/core/dataset.py
  fiftyone/core/session.py
  fiftyone/utils/quickstart.py
  fiftyone/utils/uid.py
Labels: enhancement

#710 Release v0.7.0
  .github/workflows/build-desktop.yml
  .github/workflows/build.yml
  README.md
  app/src/utils/hooks.ts
  app/src/utils/view.ts
  docs/source/cli/index.rst
  docs/source/faq/index.rst
  docs/source/getting_started/install.rst
  docs/source/getting_started/troubleshooting.rst
  docs/source/recipes/detection_mistakenness.ipynb
  docs/source/recipes/image_deduplication.ipynb
  docs/source/recipes/model_inference.ipynb
  docs/source/redirects
  docs/source/release-notes.rst
  docs/source/tutorials/evaluate_detections.ipynb
  docs/source/tutorials/label_mistakes.ipynb
  docs/source/tutorials/open_images_evaluation.ipynb
  docs/source/tutorials/uniqueness.ipynb
  docs/source/user_guide/dataset_zoo/api.rst
  docs/source/user_guide/dataset_zoo/index.rst
  docs/source/user_guide/index.rst
  docs/source/user_guide/model_zoo/api.rst
  docs/source/user_guide/model_zoo/index.rst
  fiftyone/__init__.py
  fiftyone/utils/quickstart.py
  fiftyone/zoo/datasets/tf.py
  fiftyone/zoo/datasets/torch.py
  package/db/setup.py
  setup.py
Labels: release

#726 Adding support for overwriting an existing dataset
  fiftyone/core/dataset.py
Labels: enhancement

#727 Making default App port configurable via fiftyone config
  docs/source/cli/index.rst
  docs/source/environments/index.rst
  docs/source/user_guide/app.rst
  docs/source/user_guide/config.rst
  fiftyone/core/cli.py
  fiftyone/core/config.py
  fiftyone/core/session.py
  fiftyone/server/main.py
  fiftyone/utils/quickstart.py
Labels: enhancement

#729 Adding note for working with TIFF images
  docs/source/faq/index.rst
Labels: documentation

#733 Analytics fixes
  fiftyone/__init__.py
  fiftyone/constants.py
  fiftyone/server/main.py
Labels: bug, enhancement
