Repository voxel51/fiftyone, pull requests merged in 2021-01, with the labels that each got.

#735 Exposing ability to control install/error level when using zoo models via the CLI
  docs/source/cli/index.rst
  fiftyone/core/cli.py
Labels: dataset-zoo, enhancement

#736 Adding support for customizing database directory
  docs/source/user_guide/config.rst
  fiftyone/constants.py
  fiftyone/core/config.py
  fiftyone/core/service.py
Labels: enhancement

#732 Bump to MongoDB 4.4
  docs/source/getting_started/troubleshooting.rst
  fiftyone/__init__.py
  fiftyone/constants.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
  fiftyone/core/service.py
  fiftyone/migrations/__init__.py
  fiftyone/migrations/revisions/admin/v0_7_1.py
  fiftyone/migrations/runner.py
  package/db/setup.py
  setup.py
Labels: dependencies

#738 Fix empty view stats
  fiftyone/server/main.py
Labels: app, bug, server

#731 Improved feedback
  app/public/t-shirt.svg
  app/src/components/Header.tsx
  app/src/recoil/atoms.ts
  app/src/recoil/selectors.ts
  fiftyone/constants.py
  fiftyone/server/main.py
  fiftyone/utils/uid.py
Labels: enhancement

#741 Firefox tweaks
  app/src/components/CheckboxGrid.tsx
  app/src/components/SampleModal.tsx
  app/src/components/ViewBar/ViewBar.tsx
  app/src/components/ViewBar/ViewStage/SearchResults.tsx
  app/src/components/utils.tsx
  app/src/containers/App.tsx
Labels: app

#728 Efficient implementations of field cloning/clearing/renaming, dataset view cloning/saving, and sample merging
  .github/workflows/build.yml
  docs/source/recipes/merge_datasets.ipynb
  docs/source/tutorials/evaluate_detections.ipynb
  docs/source/tutorials/open_images_eval/scripts/evaluate_model.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/frame.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/document.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/sample.py
  fiftyone/core/service.py
  fiftyone/core/view.py
  fiftyone/migrations/revisions/admin/v0_7_1.py
  install.bash
  tests/unittests/dataset_tests.py
  tests/unittests/view_tests.py
Labels: feature

#730 Automatic notebook screenshots
  .github/workflows/build-db.yml
  .github/workflows/build-desktop.yml
  .github/workflows/build-docs.yml
  .github/workflows/build.yml
  .github/workflows/chromatic.yml
  app/package.json
  app/patches/html2canvas+1.0.0-rc.7.patch
  app/src/app.global.css
  app/src/components/CheckboxGrid.tsx
  app/src/components/FieldsSidebar.tsx
  app/src/components/Header.tsx
  app/src/components/HorizontalNav.tsx
  app/src/components/RangeSlider.tsx
  app/src/components/SampleModal.tsx
  app/src/components/Tags/DropdownTag.tsx
  app/src/components/ViewBar/ViewStage/BestMatch.tsx
  app/src/components/ViewBar/ViewStage/ViewStage.tsx
  app/src/components/utils.tsx
  app/src/containers/App.tsx
  app/src/containers/Dataset.tsx
  app/src/containers/Deactivated.tsx
  app/src/recoil/atoms.ts
  app/src/recoil/selectors.ts
  app/src/utils/hooks.ts
  app/yarn.lock
  docs/source/conf.py
  docs/source/environments/index.rst
  fiftyone/core/client.py
  fiftyone/core/session.py
  fiftyone/core/state.py
  fiftyone/server/main.py
  fiftyone/utils/templates.py
  tests/isolated/server_tests.py
Labels: app, feature

#740 TF2 model zoo
  docs/source/user_guide/model_zoo/models.rst
  fiftyone/zoo/models/manifest-tf.json
  tests/unittests/dataset_tests.py
  tests/unittests/view_tests.py
Labels: core, feature, model-zoo

#747 Release v0.7.1
  app/package.json
  app/src/components/CheckboxGrid.tsx
  app/src/components/Distributions.tsx
  docs/.gitignore
  docs/generate_docs.bash
  docs/scripts/make_model_zoo_docs.py
  docs/source/release-notes.rst
  docs/source/user_guide/model_zoo/models.rst
  fiftyone/core/service.py
  fiftyone/server/main.py
  fiftyone/utils/templates.py
  package/db/setup.py
  package/desktop/setup.py
  setup.py
Labels: release

#761 Adding back support for indexing by embedded fields
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/view.py
  tests/unittests/view_tests.py
Labels: bug

#757 Fix int field parsing in App
  app/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts
  tests/isolated/service_tests.py
Labels: bug

#758 Adding images of all zoo datasets to the docs
  docs/source/images/dataset_zoo/bdd100k-validation.png
  docs/source/images/dataset_zoo/caltech101.png
  docs/source/images/dataset_zoo/caltech256.png
  docs/source/images/dataset_zoo/cifar10-test.png
  docs/source/images/dataset_zoo/cifar100-test.png
  docs/source/images/dataset_zoo/cityscapes-validation.png
  docs/source/images/dataset_zoo/coco-2014-segmentation-validation.png
  docs/source/images/dataset_zoo/coco-2014-validation.png
  docs/source/images/dataset_zoo/coco-2017-segmentation-validation.png
  docs/source/images/dataset_zoo/coco-2017-validation.png
  docs/source/images/dataset_zoo/fashion-mnist-test.png
  docs/source/images/dataset_zoo/hmdb51-test.png
  docs/source/images/dataset_zoo/imagenet-2012-validation.png
  docs/source/images/dataset_zoo/imagenet-sample.png
  docs/source/images/dataset_zoo/kitti-train.png
  docs/source/images/dataset_zoo/lfw-test.png
  docs/source/images/dataset_zoo/mnist-test.png
  docs/source/images/dataset_zoo/quickstart-video.png
  docs/source/images/dataset_zoo/quickstart.png
  docs/source/images/dataset_zoo/ucf101-test.png
  docs/source/images/dataset_zoo/voc-2007-validation.png
  docs/source/images/dataset_zoo/voc-2012-validation.png
  docs/source/user_guide/dataset_zoo/datasets.rst
Labels: documentation

#759 Create selectable cards for the Model Zoo docs
  docs/scripts/make_model_zoo_docs.py
  docs/source/custom_directives.py
  docs/source/user_guide/dataset_zoo/datasets.rst
  docs/source/user_guide/dataset_zoo/index.rst
  docs/source/user_guide/model_zoo/index.rst
Labels: documentation, model-zoo

#766 Removing unused server log directory
  fiftyone/server/main.py
Labels: cleaning

#769 Patch release 0.7.1.3
  package/db/setup.py
  setup.py
Labels: bug

#770 Adding utils to transform images and videos
  .github/workflows/build.yml
  docs/source/cli/index.rst
  docs/source/user_guide/dataset_zoo/datasets.rst
  fiftyone/core/cli.py
  fiftyone/core/collections.py
  fiftyone/utils/image.py
  fiftyone/utils/metadata.py
  fiftyone/utils/video.py
  tests/README.md
  tests/intensive/dataset_zoo_tests.py
  tests/intensive/import_export_tests.py
  tests/intensive/model_zoo_tests.py
  tests/intensive/utils_tests.py
Labels: core, feature

#771 Fix label mistakes tutorial
  docs/source/tutorials/label_mistakes.ipynb
Labels: bug, documentation

#750 Add `MapLabels` stage
  fiftyone/core/collections.py
  fiftyone/core/stages.py
  tests/unittests/view_tests.py
Labels: core, feature

#776 Quickstart notebook
  app/src/utils/hooks.ts
  docs/source/_static/css/custom.css
  docs/source/index.rst
  fiftyone/core/session.py
  fiftyone/server/main.py
  fiftyone/utils/templates.py
  tests/isolated/service_tests.py
Labels: documentation

#773 A couple small tweaks
  docs/source/cli/index.rst
  docs/source/user_guide/config.rst
  fiftyone/core/cli.py
  fiftyone/core/config.py
  fiftyone/zoo/datasets/__init__.py
Labels: enhancement

#774 Adding support for checking whether a field exists
  fiftyone/core/expressions.py
Labels: enhancement

#775 Declaring float type of bounding box coordinates
  fiftyone/core/labels.py
Labels: enhancement

#777 Adds HistogramValues aggregation stage and exposes aggregations directly on SampleCollection
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/__public__.py
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
Labels: feature

#787 Patch Release: Prevent blocking eval_js in colab
  fiftyone/core/session.py
  fiftyone/utils/templates.py
  setup.py
Labels: bug, release

#788 Leveling up the README
  LICENSE
  README.md
  docs/source/_static/images/fiftyone.png
  docs/source/_static/images/icons/cloud-icon-256px.png
  docs/source/_static/images/icons/cloud-icon-32px.png
  docs/source/_static/images/icons/colab-logo-256px.png
  docs/source/_static/images/icons/colab-logo-32px.png
  docs/source/_static/images/icons/github-logo-256px.png
  docs/source/_static/images/icons/github-logo-32px.png
  docs/source/_static/images/icons/github-logo.svg
  docs/source/_static/images/icons/jupyter-logo-256px.png
  docs/source/_static/images/icons/jupyter-logo-32px.png
  docs/source/_static/images/icons/logo-facebook-dark.svg
  docs/source/_static/images/icons/logo-twitter-dark.svg
  docs/source/_static/images/icons/medium-logo-256px.png
  docs/source/_static/images/icons/medium-logo-32px.png
  docs/source/_static/images/icons/slack-logo-256px.png
  docs/source/_static/images/icons/slack-logo-32px.png
  docs/source/_static/images/icons/slack-logo.svg
  docs/source/_static/images/icons/twitter-logo-256px.png
  docs/source/_static/images/icons/twitter-logo-32px.png
  docs/source/_static/images/logo/colab-logo-32px.png
  docs/source/_static/images/logo/download-logo-32px.png
  docs/source/conf.py
  docs/source/index.rst
  setup.py
Labels: documentation

#792 Updating subpackage docs
  docs/source/index.rst
  docs/source/user_guide/brain.rst
  package/README.md
  package/brain/LICENSE
  package/brain/README.md
  package/db/README.md
  package/db/setup.py
  package/desktop/README.md
  package/desktop/setup.py
  package/setup_utils.py
  package/voxel51-eta/README.md
Labels: documentation

#791 Clarifying how to close browser App sessions
  fiftyone/core/cli.py
Labels: enhancement

#801 Gracefully handle keyboard interrupts when app exits
  fiftyone/core/cli.py
  fiftyone/utils/quickstart.py
Labels: enhancement

#793 Only return matched results for App filters
  app/src/components/Filter.tsx
  app/src/components/Header.tsx
  app/src/components/NumericFieldFilter.tsx
  app/src/components/RangeSlider.tsx
  app/src/components/SampleModal.tsx
  app/src/components/Samples.hooks.ts
  app/src/components/Samples.tsx
  app/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts
  app/src/containers/SamplesContainer.tsx
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/stages.py
  fiftyone/core/state.py
  fiftyone/server/main.py
Labels: app, enhancement

#807 Prevent Colab from caching requests in notebooks
  fiftyone/server/main.py
Labels: bug

#800 Improved plotting
  app/src/components/Distributions.tsx
  fiftyone/server/main.py
Labels: app, enhancement

#809 Aggregation and view improvements
  docs/source/images/histogram_values_uniqueness.png
  docs/source/index.rst
  docs/source/tutorials/label_mistakes.ipynb
  docs/source/user_guide/index.rst
  docs/source/user_guide/using_aggregations.rst
  docs/source/user_guide/using_views.rst
  fiftyone/__public__.py
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/expressions.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/sample.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
  tests/unittests/aggregation_tests.py
  tests/unittests/synchronization_tests.py
  tests/unittests/view_tests.py
Labels: documentation, feature

#808 [DOCS] Update FAQ, use App in remote notebook
  docs/source/faq/index.rst
Labels: documentation

#820 lstrip error when saving sample
  fiftyone/core/odm/mixins.py
Labels: bug, core

#819 Adding small default confidence threshold to model zoo
  fiftyone/core/collections.py
  fiftyone/core/eta_utils.py
  fiftyone/core/models.py
  fiftyone/core/sample.py
  fiftyone/utils/torch.py
Labels: enhancement

#815 More view and aggregation updates
  app/src/recoil/selectors.ts
  app/src/utils/labels.ts
  docs/source/user_guide/using_aggregations.rst
  docs/source/user_guide/using_views.rst
  fiftyone/__public__.py
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/expressions.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
  fiftyone/server/main.py
  tests/unittests/aggregation_tests.py
  tests/unittests/view_tests.py
Labels: feature

#824 Simplify frames data model and logic
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/frame.py
  fiftyone/core/labels.py
  fiftyone/core/odm/sample.py
  fiftyone/core/sample.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
  fiftyone/migrations/revisions/v0_7_2.py
  fiftyone/server/main.py
  setup.py
Labels: cleaning, core

#812 Release v0.7.2
  app/package.json
  docs/source/_includes/substitutions.rst
  docs/source/environments/index.rst
  docs/source/release-notes.rst
  docs/source/user_guide/config.rst
  docs/source/user_guide/using_views.rst
  fiftyone/core/utils.py
  package/desktop/setup.py
  setup.py
Labels: release
