Repository voxel51/fiftyone, pull requests merged in 2021-07, with the labels that each got.

#1091 Disconnect timeout before closing waited sessions
  fiftyone/server/main.py
Labels: server

#1104 Fixed aws error 404 bug on windows
  fiftyone/utils/openimages.py
Labels: bug

#1111 `Session.open_tab()` in notebooks and remote warning
  fiftyone/core/session.py
Labels: app, bug, enhancement, notebook

#1109 Add progress flag to track iter_samples() progress
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/view.py
  tests/unittests/dataset_tests.py
  tests/unittests/view_tests.py
Labels: enhancement

#1105 Handling unlabeled datasets in COCODetectionDatasetImporter
  fiftyone/utils/coco.py
Labels: enhancement

#1112 Improvements to Open Images partial downloads
  fiftyone/utils/coco.py
  fiftyone/utils/openimages.py
  tests/intensive/dataset_zoo_tests.py
  tests/intensive/import_export_tests.py
Labels: enhancement

#1114 Adds support for evaluating polygons and instance segmentations
  docs/source/integrations/coco.rst
  docs/source/integrations/open_images.rst
  docs/source/user_guide/evaluation.rst
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/labels.py
  fiftyone/core/models.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/patches.py
  fiftyone/core/runs.py
  fiftyone/core/utils.py
  fiftyone/core/validation.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/openimages.py
  fiftyone/utils/eval/segmentation.py
  fiftyone/utils/eval/utils.py
  tests/intensive/evaluation_tests.py
Labels: feature

#1117 Adding plotly<5 requirement to fix interactive plotting
  setup.py
Labels: bug, high-priority, hotfix

#1120 Optimizing evaluation patches view creation
  docs/source/images/app/app-evaluation-patches.gif
  fiftyone/core/patches.py
Labels: enhancement

#1118 Added RHEL7 install for fiftyone-db
  .github/workflows/build-db.yml
  docs/source/getting_started/troubleshooting.rst
  package/db/setup.py
  package/test-envs/dockerfiles/centos7
Labels: enhancement, setup

#1116 Adding support for loading COCO license data
  docs/source/integrations/coco.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_zoo/datasets.rst
  fiftyone/types/dataset_types.py
  fiftyone/utils/coco.py
Labels: feature

#1122 Catch exception when trying to patch plotly on read-only FS
  fiftyone/core/plots/plotly.py
Labels: bug

#1098 Don't allow migrations involving future FiftyOne versions
  docs/source/getting_started/install.rst
  fiftyone/migrations/runner.py
  tests/unittests/utils_tests.py
Labels: enhancement

#1115 Adding support for gracefully handling evaluations/brain methods from future FiftyOne versions
  fiftyone/core/collections.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
  fiftyone/core/odm/runs.py
  fiftyone/core/runs.py
  fiftyone/migrations/revisions/v0_11_2.py
  setup.py
Labels: enhancement

#1124 Adding relevant indexes for patch/frame views
  docs/source/conf.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/patches.py
  fiftyone/core/stages.py
  fiftyone/core/video.py
  fiftyone/core/view.py
  tests/unittests/dataset_tests.py
  tests/unittests/patches_tests.py
  tests/unittests/video_tests.py
Labels: enhancement

#1136 Updating user count
  app/src/components/Header.tsx
Labels: app

#1143 Handling degenerate masks when exporting COCO segmentations
  fiftyone/utils/coco.py
Labels: bug

#1142 Adding support for rendering instances/polylines as segmentations
  fiftyone/core/labels.py
  fiftyone/utils/data/base.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/labels.py
Labels: feature

#1131 Better handling of evaluation edge cases
  .github/workflows/build.yml
  docs/source/conf.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/utils/coco.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/openimages.py
  fiftyone/utils/eval/segmentation.py
  tests/unittests/evaluation_tests.py
Labels: enhancement

#1133 Fixing loading of zoo datasets with partial downloads (#1129)
  docs/source/user_guide/dataset_zoo/datasets.rst
  fiftyone/utils/coco.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/openimages.py
  fiftyone/zoo/datasets/__init__.py
  fiftyone/zoo/datasets/base.py
Labels: bug

#1123 v0.11.2 release
  docs/source/release-notes.rst
  setup.py
Labels: release

#1147 Fixing #1146
  fiftyone/utils/cityscapes.py
  fiftyone/utils/data/exporters.py
Labels: bug

#1150 Fixing #1149
  fiftyone/utils/coco.py
  tests/intensive/dataset_zoo_tests.py
Labels: hotfix

#1151 Open Images download hotfix
  fiftyone/utils/openimages.py
  setup.py
  tests/intensive/dataset_zoo_tests.py
Labels: bug, hotfix
