Repository voxel51/fiftyone, pull requests merged in 2021-10, with the labels that each got.

#1227 Adding a temporal detection label type
  app/packages/app/src/recoil/selectors.ts
  app/packages/app/src/utils/labels.ts
  app/packages/looker/src/constants.ts
  app/packages/looker/src/elements/base.ts
  app/packages/looker/src/elements/common/error.ts
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/index.ts
  app/packages/looker/src/overlays/classifications.ts
  app/packages/looker/src/overlays/index.ts
  app/packages/looker/src/processOverlays.ts
  app/packages/looker/src/state.ts
  app/packages/looker/src/util.ts
  docs/source/_includes/substitutions.rst
  docs/source/user_guide/basics.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/export_datasets.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/__public__.py
  fiftyone/core/fields.py
  fiftyone/core/labels.py
  fiftyone/core/metadata.py
  fiftyone/types/dataset_types.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/data/parsers.py
  tests/unittests/import_export_tests.py
Labels: feature

#1257 Adding support for rendering temporal detections via draw_labels()
  docs/source/images/draw_labels/example1.jpg
  docs/source/images/draw_labels/example2.jpg
  docs/source/user_guide/draw_labels.rst
  docs/source/user_guide/model_zoo/api.rst
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/eta_utils.py
  fiftyone/core/labels.py
  fiftyone/core/models.py
  fiftyone/utils/annotations.py
  fiftyone/utils/coco.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/data/parsers.py
  fiftyone/utils/eta.py
  fiftyone/utils/patches.py
  fiftyone/utils/torch.py
  fiftyone/zoo/models/manifest-tf.json
Labels: feature

#1312 Adding support for configuring whether label additions/deletions/spatial edits are allowed during annotation
  docs/source/integrations/cvat.rst
  docs/source/user_guide/annotation.rst
  fiftyone/core/collections.py
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
Labels: enhancement

#1313 Adding support for read-only labels/attributes during annotation
  docs/source/integrations/cvat.rst
  docs/source/user_guide/annotation.rst
  fiftyone/core/collections.py
  fiftyone/utils/annotations.py
Labels: enhancement

#1316 Remove duplicate page stage
  fiftyone/server/main.py
Labels: bug, server

#1317 Fixing a subtle run results cloning bug
  fiftyone/core/dataset.py
Labels: bug

#1318 Allow a list of task assignees for CVAT
  docs/source/integrations/cvat.rst
  fiftyone/utils/cvat.py
Labels: feature

#1322 Supporting class-specific attributes during annotation import
  fiftyone/utils/annotations.py
Labels: bug

#1323 Fixing serialization of CVAT attribute values
  fiftyone/utils/cvat.py
Labels: bug

#1383 Fix bug when annotating and allow_additions is False
  fiftyone/utils/annotations.py
Labels: bug
