Repository voxel51/fiftyone, pull requests merged in 2021-08, with the labels that each got.

#1152 Only load matching samples when classes/attrs requirements are provided
  fiftyone/utils/openimages.py
Labels: bug

#1154 Adding session.wait() instructions in key places
  README.md
  docs/source/faq/index.rst
  docs/source/getting_started/install.rst
  docs/source/index.rst
  docs/source/user_guide/app.rst
Labels: documentation

#1160 Gracefully ignore None-valued new fields when expanding dataset schemas
  fiftyone/core/dataset.py
  fiftyone/core/frame.py
  fiftyone/core/labels.py
  fiftyone/core/runs.py
  tests/unittests/dataset_tests.py
  tests/unittests/video_tests.py
Labels: enhancement

#1158 Adding support for importing DICOM datasets
  .github/workflows/build.yml
  docs/source/conf.py
  docs/source/user_guide/dataset_creation/datasets.rst
  fiftyone/types/dataset_types.py
  fiftyone/utils/dicom.py
  requirements/dev.txt
  tests/unittests/import_export_tests.py
Labels: feature

#1164 Documenting batch actions
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/core/collections.py
  fiftyone/core/session.py
  fiftyone/utils/geojson.py
  tests/misc/selection_tests.py
Labels: documentation

#1166 Adding merge_samples() documentation to user guide
  docs/source/user_guide/using_datasets.rst
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/frame.py
  fiftyone/core/sample.py
  fiftyone/utils/data/importers.py
Labels: documentation

#1169 Release v0.12.0
  .github/workflows/build-desktop.yml
  app/packages/app/package.json
  app/packages/desktop/package.json
  docs/source/environments/index.rst
  docs/source/release-notes.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/core/stages.py
  fiftyone/core/state.py
  fiftyone/utils/torch.py
  setup.py
Labels: release

#1186 fixed loading yolov5 yaml with multiply paths
  docs/source/user_guide/using_datasets.rst
  fiftyone/utils/yolo.py
Labels: bug

#1188 Adding a group_by() view stage
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/stages.py
Labels: feature

#1194 Fixing Issue #1192
  fiftyone/core/dataset.py
  fiftyone/core/odm/mixins.py
Labels: bug

#1179 Update desktop app source launches
  app/package.json
  app/packages/desktop/package.json
  fiftyone/core/service.py
Labels: bug

#1181 Fix range slider blurs
  app/packages/app/src/components/Filters/RangeSlider.tsx
Labels: app

#1180 Zoom fix for empty samples
  app/packages/looker/src/index.ts
Labels: bug, app

#1183 App issues
  app/packages/app/src/components/CheckboxGroup.tsx
  app/packages/app/src/components/Flashlight.tsx
  app/packages/flashlight/src/index.ts
  app/packages/flashlight/src/zooming.ts
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/elements/frame.ts
  app/packages/looker/src/elements/image.ts
  app/packages/looker/src/elements/video.ts
  app/packages/looker/src/index.ts
Labels: bug, app

#1197 Fix duplicate app rendering in IPython notebooks
  fiftyone/core/session.py
Labels: bug, core, notebook

#1182 Fix next/previous click controls in notebooks
  app/packages/looker/src/elements/base.ts
  app/packages/looker/src/elements/common/actions.ts
  app/packages/looker/src/elements/common/canvas.ts
  app/packages/looker/src/elements/common/controls.ts
  docs/source/user_guide/app.rst
Labels: app

#1193 App list fields filtering
  app/packages/app/src/components/CheckboxGroup.tsx
  app/packages/app/src/components/Common/Checkbox.tsx
  app/packages/app/src/components/Common/Results.tsx
  app/packages/app/src/components/Distributions.tsx
  app/packages/app/src/components/FieldsSidebar.tsx
  app/packages/app/src/components/Filters/BooleanFieldFilter.state.ts
  app/packages/app/src/components/Filters/BooleanFieldFilter.tsx
  app/packages/app/src/components/Filters/CategoricalFilter.tsx
  app/packages/app/src/components/Filters/LabelFieldFilters.state.tsx
  app/packages/app/src/components/Filters/NumericFieldFilter.state.ts
  app/packages/app/src/components/Filters/NumericFieldFilter.tsx
  app/packages/app/src/components/Filters/StringFieldFilter.state.ts
  app/packages/app/src/components/Filters/StringFieldFilter.tsx
  app/packages/app/src/components/Filters/atoms.ts
  app/packages/app/src/components/Filters/filtered.ts
  app/packages/app/src/components/Filters/types.ts
  app/packages/app/src/components/Filters/utils.ts
  app/packages/app/src/components/Flashlight.tsx
  app/packages/app/src/components/Looker.tsx
  app/packages/app/src/containers/Dataset.tsx
  app/packages/app/src/recoil/atoms.ts
  app/packages/app/src/recoil/selectors.ts
  app/packages/app/src/utils/labels.ts
  app/packages/flashlight/src/index.ts
  app/packages/looker/src/elements/common/tags.module.css
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/elements/index.ts
  app/packages/looker/src/index.ts
  app/packages/looker/src/state.ts
  fiftyone/core/.dataset.py.swp
  fiftyone/core/aggregations.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/state.py
  fiftyone/server/extended_view.py
  fiftyone/server/main.py
  tests/unittests/dataset_tests.py
Labels: app

#1198 Fix initial patch zoom for grid thumbnails
  app/packages/looker/src/index.ts
Labels: bug, app

#1201 Add .swp to .gitignore
  .gitignore
  fiftyone/core/.dataset.py.swp
Labels: cleaning

#1202 Path cleanup
  .github/workflows/build.yml
  fiftyone/constants.py
  fiftyone/core/service.py
Labels: cleaning

#1207 Adding support for BDD score field
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/utils/bdd.py
Labels: enhancement

#1208 App JSON improvements
  app/packages/app/src/components/Actions/ActionsRow.tsx
  app/packages/app/src/components/Flashlight.tsx
  app/packages/app/src/components/Looker.tsx
  app/packages/app/src/recoil/atoms.ts
  app/packages/looker/src/constants.ts
  app/packages/looker/src/index.ts
  app/packages/looker/src/overlays/base.ts
  app/packages/looker/src/overlays/classifications.ts
  app/packages/looker/src/overlays/segmentation.ts
  app/packages/looker/src/state.ts
  app/packages/looker/src/worker.ts
Labels: app

#1211 Add Apple Silicon support and a configurable database connection
  .github/workflows/build-db.yml
  .github/workflows/build-desktop.yml
  .github/workflows/build.yml
  app/packages/desktop/package.json
  docs/source/faq/index.rst
  docs/source/getting_started/install.rst
  docs/source/getting_started/troubleshooting.rst
  docs/source/user_guide/config.rst
  fiftyone/__public__.py
  fiftyone/constants.py
  fiftyone/core/config.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
  fiftyone/core/service.py
  fiftyone/core/utils.py
  fiftyone/server/main.py
  fiftyone/service/main.py
  package/db/setup.py
  package/desktop/setup.py
Labels: core

#1216 v0.13.0 release
  .github/workflows/build-desktop.yml
  app/package.json
  app/packages/app/package.json
  app/packages/desktop/package.json
  app/packages/flashlight/package.json
  app/packages/looker/package.json
  docs/source/release-notes.rst
  fiftyone/core/runs.py
  fiftyone/core/service.py
  fiftyone/core/session.py
  fiftyone/core/uid.py
  fiftyone/migrations/revisions/v0_13_0.py
  fiftyone/server/main.py
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
  fiftyone/utils/eval/base.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/openimages.py
  fiftyone/utils/eval/segmentation.py
  package/desktop/setup.py
  setup.py
Labels: release
