Repository voxel51/fiftyone, pull requests merged in 2021-09, with the labels that each got.

#1240 Docs formatting tweaks
  docs/source/integrations/coco.rst
  docs/source/integrations/open_images.rst
  docs/source/user_guide/dataset_zoo/datasets.rst
Labels: documentation

#1233 Adding support for compound sort criteria
  fiftyone/core/collections.py
  fiftyone/core/stages.py
Labels: feature

#1245 Configurable session waiting
  docs/source/cli/index.rst
  fiftyone/core/cli.py
  fiftyone/core/session.py
Labels: enhancement

#1248 [BUG] Fix error when loading CVATImageDataset with None values
  fiftyone/utils/cvat.py
Labels: bug

#1224 Select only relevant objects before editing in App tagging workflow
  fiftyone/server/utils.py
Labels: app

#1242 Facet optimization
  fiftyone/core/collections.py
  fiftyone/core/odm/database.py
  fiftyone/server/main.py
Labels: enhancement, app

#1250 [BUG] Fix importing COCO, VOC formats when exported from CVAT
  fiftyone/utils/coco.py
  fiftyone/utils/voc.py
Labels: bug, core

#1249 Aggregation optimizations
  fiftyone/core/collections.py
  fiftyone/core/odm/database.py
Labels: enhancement

#1247 Release v0.13.2
  .github/workflows/build.yml
  app/package.json
  app/packages/app/package.json
  app/packages/app/src/components/Filters/CategoricalFilter.tsx
  app/packages/app/src/containers/App.tsx
  app/packages/desktop/package.json
  app/packages/looker/src/overlays/detection.ts
  docs/source/release-notes.rst
  fiftyone/core/odm/database.py
  fiftyone/core/service.py
  fiftyone/core/uid.py
  fiftyone/server/main.py
  fiftyone/service/main.py
  package/desktop/setup.py
  setup.py
  tests/isolated/service_tests.py
  tests/no_wrapper/multiprocess_tests.py
Labels: bug, release

#1256 Adding missing zip to cityscapes docs
  docs/source/release-notes.rst
  docs/source/user_guide/dataset_zoo/datasets.rst
  fiftyone/zoo/datasets/base.py
Labels: documentation

#1244 Frames improvements
  app/packages/app/src/components/Flashlight.tsx
  app/packages/app/src/components/SampleModal.tsx
  fiftyone/core/frame.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
  fiftyone/server/main.py
  tests/unittests/video_tests.py
Labels: enhancement

#1258 Setup tweaks
  fiftyone/core/cli.py
  fiftyone/core/service.py
  package/desktop/setup.py
  requirements/common.txt
Labels: setup

#1254 Fix image map keys when using subset/subdirectory in cvat dataset
  fiftyone/utils/cvat.py
Labels: bug

#1261 Limit stats results
  app/packages/app/src/components/Distributions.tsx
  fiftyone/core/aggregations.py
  fiftyone/server/main.py
Labels: bug, app

#1264 Fixing boolean App filters
  fiftyone/core/aggregations.py
  fiftyone/core/state.py
Labels: bug

#1266 Fixing #1265
  fiftyone/core/collections.py
  fiftyone/core/plots/base.py
  fiftyone/core/plots/manager.py
  fiftyone/core/plots/matplotlib.py
  fiftyone/core/plots/plotly.py
Labels: bug, core

#1271 Split labels and merge labels
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
Labels: enhancement

#1269 Allowing MongoDB v5 custom database usages
  docs/source/faq/index.rst
  docs/source/user_guide/config.rst
  fiftyone/core/odm/database.py
Labels: documentation, enhancement

#1278 App video issues
  app/packages/looker/src/elements/util.ts
  app/packages/looker/src/elements/video.ts
  app/packages/looker/src/index.ts
Labels: bug, app

#1283 Relax `opencv-python-headless` version requirement
  setup.py
Labels: setup

#1280 Adding support for loading GeoTIFF images
  docs/source/conf.py
  docs/source/faq/index.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/types/dataset_types.py
  fiftyone/utils/geotiff.py
Labels: feature

#1279 Expose the mutable property for CVAT attributes
  docs/source/integrations/cvat.rst
  docs/source/user_guide/annotation.rst
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
Labels: core

#1277 Expose CVAT API parameters to upload higher quality video
  docs/source/integrations/cvat.rst
  fiftyone/utils/cvat.py
Labels: feature, core

#1281 Annotation improvements
  docs/source/integrations/cvat.rst
  docs/source/user_guide/annotation.rst
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/labels.py
  fiftyone/core/patches.py
  fiftyone/core/runs.py
  fiftyone/core/video.py
  fiftyone/core/view.py
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/labels.py
Labels: enhancement

#1285 Interpolate CVAT object tracks
  fiftyone/utils/cvat.py
Labels: enhancement

#1284 Only warn during `mongod` compatibility validation
  docs/source/user_guide/config.rst
  fiftyone/core/config.py
  fiftyone/core/odm/database.py
Labels: setup

#1286 Release v0.13.3
  app/package.json
  app/packages/app/package.json
  app/packages/desktop/package.json
  app/packages/looker/package.json
  docs/source/integrations/cvat.rst
  docs/source/release-notes.rst
  docs/source/user_guide/annotation.rst
  package/desktop/setup.py
  setup.py
  tests/isolated/import_time_test.py
Labels: release

#1287 Docs updates
  docs/source/_static/js/voxel51-website.js
  docs/source/_templates/layout.html
  docs/source/environments/index.rst
  docs/source/faq/index.rst
Labels: documentation

#1296 Including missing GT/predictions by default in confusion matrices
  fiftyone/utils/eval/base.py
Labels: enhancement

#1297 Adding support for filtering object trajectories
  fiftyone/core/collections.py
  fiftyone/core/stages.py
  tests/unittests/view_tests.py
Labels: enhancement

#1226 Adding created_at and last_loaded_at properties to datasets
  docs/source/cli/index.rst
  docs/source/user_guide/config.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/core/cli.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/dataset.py
  fiftyone/migrations/revisions/v0_14_0.py
  fiftyone/utils/data/importers.py
Labels: feature

#1301 Adding set operation expressions
  fiftyone/core/aggregations.py
  fiftyone/core/expressions.py
  fiftyone/core/stages.py
Labels: enhancement

#1305 Adding support for per-class attributes in annotation schemas
  docs/source/integrations/cvat.rst
  docs/source/integrations/index.rst
  docs/source/user_guide/annotation.rst
  fiftyone/core/service.py
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
Labels: enhancement

#1307 Adding support for annotation backend to recommend attribute widget type
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
Labels: enhancement
