Repository voxel51/fiftyone, pull requests merged in 2021-03, with the labels that each got.

#898 Release v0.7.4
  app/package.json
  docs/source/release-notes.rst
  package/desktop/setup.py
  setup.py
Labels: release

#892 Utilities for tagging and visualizing samples and labels
  .github/workflows/build.yml
  app/src/components/SampleModal.tsx
  app/src/components/SelectLabelsMenu.tsx
  app/src/containers/App.tsx
  app/src/containers/Dataset.tsx
  app/src/utils/selection.ts
  docs/source/user_guide/using_aggregations.rst
  fiftyone/__public__.py
  fiftyone/core/aggregations.py
  fiftyone/core/client.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/expressions.py
  fiftyone/core/labels.py
  fiftyone/core/sample.py
  fiftyone/core/session.py
  fiftyone/core/stages.py
  fiftyone/core/state.py
  fiftyone/server/main.py
  fiftyone/utils/plot/__init__.py
  fiftyone/utils/plot/location.py
  fiftyone/utils/plot/scatter.py
  fiftyone/utils/plot/selector.py
  fiftyone/utils/plot/utils.py
  tests/intensive/collections_tests.py
  tests/intensive/utils_plot_tests.py
  tests/misc/selection_tests.py
  tests/unittests/view_tests.py
Labels: feature

#884 Adds support for showing "other" predictions in confusion matrix
  fiftyone/core/collections.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/detection.py
  tests/intensive/evaluation_tests.py
Labels: enhancement

#893 Adding support for saving run results on datasets
  fiftyone/core/brain.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/evaluation.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
  fiftyone/core/odm/runs.py
  fiftyone/core/runs.py
  fiftyone/migrations/revisions/v0_7_5.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/segmentation.py
Labels: feature

#903 Adding support for storing class lists on datasets
  docs/source/user_guide/basics.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/export_datasets.rst
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/fields.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/view.py
  fiftyone/migrations/revisions/v0_7_5.py
  fiftyone/utils/coco.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/segmentation.py
  fiftyone/utils/yolo.py
  fiftyone/zoo/datasets/__init__.py
  tests/unittests/dataset_tests.py
Labels: feature

#912 Build view along with pipeline when aggregating views
  fiftyone/core/view.py
Labels: bug

#908 Adding GeoLocation label type and view stages
  docs/source/_includes/substitutions.rst
  docs/source/images/dataset_zoo/quickstart-geo.png
  docs/source/user_guide/basics.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_zoo/datasets.rst
  docs/source/user_guide/export_datasets.rst
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/fields.py
  fiftyone/core/labels.py
  fiftyone/core/session.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
  fiftyone/types/dataset_types.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/geojson.py
  fiftyone/utils/plot/location.py
  fiftyone/utils/plot/scatter.py
  fiftyone/utils/plot/selector.py
  fiftyone/zoo/datasets/base.py
Labels: feature

#914 Always allow disk use in aggregations
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
  fiftyone/core/view.py
Labels: bug, core, enhancement

#925 Fixing ViewField copying
  fiftyone/__public__.py
  fiftyone/core/expressions.py
  tests/unittests/view_tests.py
Labels: bug

#930 Updating remote session instructions
  app/src/containers/Setup.tsx
  docs/docs_guide.md
  docs/source/cli/index.rst
  docs/source/environments/index.rst
  docs/source/user_guide/app.rst
  fiftyone/core/cli.py
  fiftyone/core/session.py
Labels: bug

#929 Colab installs from source
  README.md
  install.bash
  requirements/common.txt
Labels: bug, enhancement, notebook

#931 Bump ETA requirement
  setup.py
Labels: bug, setup

#937 Hide label attributes by default in Player51
  docs/source/user_guide/config.rst
  fiftyone/core/config.py
Labels: app, enhancement

#933 Adding support for efficiently merging video datasets
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/view.py
  tests/intensive/merge_tests.py
Labels: feature

#939 Adding trigonometric ViewExpressions and Gaussian random variable support
  fiftyone/core/expressions.py
Labels: enhancement

#911 Adding respsonsive plotting interface
  docs/source/getting_started/install.rst
  docs/source/user_guide/config.rst
  docs/source/user_guide/evaluation.rst
  fiftyone/__public__.py
  fiftyone/core/aggregations.py
  fiftyone/core/client.py
  fiftyone/core/collections.py
  fiftyone/core/context.py
  fiftyone/core/dataset.py
  fiftyone/core/labels.py
  fiftyone/core/plots/__init__.py
  fiftyone/core/plots/base.py
  fiftyone/core/plots/manager.py
  fiftyone/core/plots/matplotlib.py
  fiftyone/core/plots/plotly.py
  fiftyone/core/plots/utils.py
  fiftyone/core/plots/views.py
  fiftyone/core/runs.py
  fiftyone/core/session.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
  fiftyone/server/main.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/segmentation.py
  fiftyone/utils/plot/__init__.py
  fiftyone/utils/plot/location.py
  fiftyone/utils/plot/scatter.py
  fiftyone/utils/plot/selector.py
  install.bash
  requirements/common.txt
  setup.py
  tests/intensive/merge_tests.py
  tests/intensive/utils_plot_tests.py
Labels: feature

#941 FAQ Refresh
  docs/source/faq/index.rst
  docs/source/user_guide/app.rst
Labels: documentation

#938 Fixing detection evaluation for videos
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/evaluation.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/segmentation.py
Labels: bug

#932 More efficient import/export of FiftyOne datasets
  docs/source/_includes/substitutions.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/export_datasets.rst
  docs/source/user_guide/using_aggregations.rst
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/frame.py
  fiftyone/core/media.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/plots/base.py
  fiftyone/core/plots/matplotlib.py
  fiftyone/core/plots/plotly.py
  fiftyone/core/runs.py
  fiftyone/core/sample.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
  fiftyone/migrations/__init__.py
  fiftyone/migrations/runner.py
  fiftyone/types/dataset_types.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/data/parsers.py
  tests/intensive/import_export_tests.py
Labels: feature

#945 Adding type checks for Session property setters
  fiftyone/core/session.py
Labels: enhancement

#946 Validate keyword arguments in Session's init
  fiftyone/core/session.py
Labels: bug, enhancement
