Repository voxel51/fiftyone, pull requests merged in 2021-06, with the labels that each got.

#1063 Server: Always set mime type to text/javascript for .js files
  fiftyone/server/main.py
Labels: app, bug, server

#1052 Adding support for exporting image patches
  docs/source/user_guide/export_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/core/collections.py
  fiftyone/core/labels.py
  fiftyone/core/models.py
  fiftyone/core/utils.py
  fiftyone/utils/bdd.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/ingestors.py
  fiftyone/utils/data/parsers.py
  fiftyone/utils/labelbox.py
  fiftyone/utils/patches.py
  fiftyone/utils/scale.py
  fiftyone/zoo/datasets/__init__.py
Labels: feature

#1048 Adding support for merging list fields, plus other goodies
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/expressions.py
  fiftyone/core/frame.py
  fiftyone/core/sample.py
  fiftyone/core/utils.py
  tests/intensive/merge_tests.py
  tests/unittests/dataset_tests.py
  tests/unittests/sample_tests.py
  tests/unittests/video_tests.py
Labels: feature

#1017 Adding ID to document schemas
  app/src/components/Filters/utils.ts
  app/src/utils/labels.ts
  docs/source/user_guide/basics.rst
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/__public__.py
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/frame.py
  fiftyone/core/labels.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/odm/frame.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/odm/sample.py
  fiftyone/core/patches.py
  fiftyone/core/sample.py
  fiftyone/core/stages.py
  fiftyone/core/state.py
  fiftyone/server/json_util.py
  tests/unittests/aggregation_tests.py
  tests/unittests/patches_tests.py
  tests/unittests/sample_tests.py
  tests/unittests/video_tests.py
  tests/unittests/view_tests.py
Labels: core, enhancement

#1004 Adding support for creating frames views into video datasets
  app/src/components/Filters/NumericFieldFilter.tsx
  app/src/components/Filters/RangeSlider.tsx
  app/src/utils/labels.ts
  docs/source/user_guide/using_views.rst
  fiftyone/__public__.py
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/frame.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/odm/frame.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/patches.py
  fiftyone/core/sample.py
  fiftyone/core/stages.py
  fiftyone/core/state.py
  fiftyone/core/video.py
  fiftyone/core/view.py
  fiftyone/migrations/revisions/v0_9_4.py
  fiftyone/server/extended_view.py
  fiftyone/server/main.py
  fiftyone/utils/video.py
  tests/intensive/video_tests.py
  tests/unittests/aggregation_tests.py
  tests/unittests/patches_tests.py
  tests/unittests/video_tests.py
Labels: core

#1066 Open csv files related to open images with a utf8 encoding
  fiftyone/utils/openimages.py
Labels: bug

#1069 Release v0.9.4
  app/package.json
  app/src/components/FieldsSidebar.tsx
  app/src/components/Header.tsx
  app/src/components/Sample.tsx
  app/src/recoil/atoms.ts
  app/src/recoil/selectors.ts
  docs/source/_static/css/custom.css
  docs/source/_static/css/voxel51-website.css
  docs/source/_templates/layout.html
  docs/source/conf.py
  docs/source/release-notes.rst
  fiftyone/constants.py
  fiftyone/migrations/revisions/v0_9_4.py
  fiftyone/server/main.py
  package/desktop/setup.py
  setup.py
Labels: release

#1059 Adding support for applying Lightning Flash models to datasets
  docs/source/_static/css/voxel51-website.css
  docs/source/_static/images/integrations/lightning_flash.png
  docs/source/_static/images/integrations/open_images.png
  docs/source/_templates/layout.html
  docs/source/conf.py
  docs/source/images/integrations/flash_embeddings.png
  docs/source/index.rst
  docs/source/integrations/index.rst
  docs/source/integrations/lightning_flash.rst
  docs/source/release-notes.rst
  fiftyone/core/collections.py
  fiftyone/core/models.py
  fiftyone/core/plots/matplotlib.py
  fiftyone/core/plots/plotly.py
  fiftyone/core/utils.py
  fiftyone/utils/coco.py
  fiftyone/utils/flash.py
  fiftyone/utils/openimages.py
  fiftyone/zoo/datasets/torch.py
  fiftyone/zoo/models/__init__.py
  setup.py
  tests/isolated/import_deps_test.py
Labels: core, feature

#1077 Fixes display issues for the `sample_id` patches view field
  app/src/components/FieldsSidebar.tsx
  app/src/components/Sample.tsx
  app/src/recoil/selectors.ts
Labels: app

#1082 Filter classifications in the sample grid
  app/src/components/Sample.tsx
Labels: app, bug

#1083 COCO Evaluation Updates
  fiftyone/utils/coco.py
Labels: core

#1085 Adding select_by() and exclude_by() stages
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/stages.py
Labels: feature

#1086 Optimizing implementation of batch aggregations
  docs/source/user_guide/using_aggregations.rst
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  tests/unittests/aggregation_tests.py
Labels: enhancement

#1078 Adding support for customizing dataset imports and exports
  docs/source/integrations/lightning_flash.rst
  docs/source/release-notes.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_creation/index.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/eta_utils.py
  fiftyone/core/media.py
  fiftyone/core/models.py
  fiftyone/core/utils.py
  fiftyone/types/dataset_types.py
  fiftyone/utils/bdd.py
  fiftyone/utils/coco.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/data/ingestors.py
  fiftyone/utils/geojson.py
  fiftyone/utils/kitti.py
  fiftyone/utils/openimages.py
  fiftyone/utils/patches.py
  fiftyone/utils/tf.py
  fiftyone/utils/torch.py
  fiftyone/utils/voc.py
  fiftyone/utils/yolo.py
  fiftyone/zoo/datasets/__init__.py
  fiftyone/zoo/datasets/base.py
  fiftyone/zoo/datasets/tf.py
  fiftyone/zoo/datasets/torch.py
  requirements/common.txt
  setup.py
  tests/intensive/import_export_tests.py
Labels: feature

#1079 Adding support for partial downloads of the COCO dataset
  app/package.json
  docs/source/_static/images/integrations/coco.png
  docs/source/_templates/layout.html
  docs/source/cli/index.rst
  docs/source/conf.py
  docs/source/images/dataset_zoo/coco-2014-segmentation-validation.png
  docs/source/images/dataset_zoo/coco-2014-validation.png
  docs/source/images/dataset_zoo/coco-2017-segmentation-validation.png
  docs/source/images/dataset_zoo/coco-2017-validation.png
  docs/source/index.rst
  docs/source/integrations/coco.rst
  docs/source/integrations/index.rst
  docs/source/integrations/lightning_flash.rst
  docs/source/integrations/open_images.rst
  docs/source/release-notes.rst
  docs/source/user_guide/app.rst
  docs/source/user_guide/basics.rst
  docs/source/user_guide/brain.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_creation/samples.rst
  docs/source/user_guide/dataset_zoo/datasets.rst
  docs/source/user_guide/dataset_zoo/index.rst
  docs/source/user_guide/draw_labels.rst
  docs/source/user_guide/evaluation.rst
  docs/source/user_guide/export_datasets.rst
  docs/source/user_guide/model_zoo/index.rst
  docs/source/user_guide/plots.rst
  docs/source/user_guide/using_aggregations.rst
  fiftyone/core/cli.py
  fiftyone/types/dataset_types.py
  fiftyone/utils/coco.py
  fiftyone/utils/eval/coco.py
  fiftyone/utils/kitti.py
  fiftyone/utils/openimages.py
  fiftyone/utils/voc.py
  fiftyone/utils/yolo.py
  fiftyone/zoo/datasets/__init__.py
  fiftyone/zoo/datasets/base.py
  fiftyone/zoo/datasets/tf.py
  fiftyone/zoo/datasets/torch.py
  package/desktop/setup.py
  setup.py
Labels: feature

#1089 Patch release
  app/package.json
  app/src/components/Header.tsx
  docs/source/_static/js/custom.js
  docs/source/_templates/layout.html
  docs/source/conf.py
  docs/source/getting_started/troubleshooting.rst
  docs/source/index.rst
  package/desktop/setup.py
  setup.py
Labels: release
