Repository voxel51/fiftyone, pull requests merged in 2021-05, with the labels that each got.

#992 Adding support for reloading dataset schemas + frames implementation overhaul
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/frame.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
  fiftyone/core/odm/document.py
  fiftyone/core/odm/frame.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/sample.py
  fiftyone/core/session.py
  fiftyone/core/singleton.py
  fiftyone/core/singletons.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  tests/benchmarking/cifar10_benchmark.py
  tests/unittests/sample_tests.py
  tests/unittests/synchronization_tests.py
  tests/unittests/video_tests.py
Labels: core, enhancement

#997 Fix handling of None-valued brain results
  fiftyone/core/runs.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
Labels: bug, core

#982 Adding support for big values() aggregations
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
Labels: enhancement

#985 App patches
  app/src/app.global.css
  app/src/components/Actions/ActionsRow.tsx
  app/src/components/Actions/Checker.tsx
  app/src/components/Actions/Common.tsx
  app/src/components/Actions/Patcher.tsx
  app/src/components/Actions/Selected.tsx
  app/src/components/Actions/Similar.tsx
  app/src/components/Actions/Tagger.tsx
  app/src/components/Actions/utils.tsx
  app/src/components/CheckboxGroup.tsx
  app/src/components/Common/Checkbox.tsx
  app/src/components/Common/Input.tsx
  app/src/components/Common/RadioGroup.tsx
  app/src/components/Common/Results.tsx
  app/src/components/ExternalLink.tsx
  app/src/components/FieldsSidebar.tsx
  app/src/components/Filters/BooleanFieldFilter.tsx
  app/src/components/Filters/BooleanFilter.tsx
  app/src/components/Filters/LabelFieldFilter.tsx
  app/src/components/Filters/NumericFieldFilter.tsx
  app/src/components/Filters/RangeSlider.tsx
  app/src/components/Filters/StringFieldFilter.tsx
  app/src/components/Filters/StringFilter.tsx
  app/src/components/Filters/utils.ts
  app/src/components/ImageContainerHeader.tsx
  app/src/components/Sample.tsx
  app/src/components/SampleModal.tsx
  app/src/components/utils.tsx
  app/src/recoil/selectors.ts
  app/src/utils/generic.ts
  app/src/utils/hooks.ts
  app/src/utils/labels.ts
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/state.py
  fiftyone/server/main.py
Labels: app

#994 Adding support for applying image models to video frames
  docs/source/cli/index.rst
  fiftyone/core/cli.py
  fiftyone/core/collections.py
  fiftyone/core/eta_utils.py
  fiftyone/core/metadata.py
  fiftyone/core/models.py
  fiftyone/core/sample.py
  fiftyone/core/validation.py
  fiftyone/utils/torch.py
  tests/intensive/model_tests.py
Labels: feature

#995 Require eager execution mode when exporting datasets in TF format
  fiftyone/core/utils.py
  fiftyone/utils/tf.py
Labels: bug

#1000 `Session.wait()` support for browsers
  fiftyone/core/client.py
  fiftyone/core/session.py
  fiftyone/server/main.py
Labels: app, bug

#1006 Recover from cursor timeouts
  fiftyone/core/dataset.py
  fiftyone/core/view.py
Labels: bug

#1005 Graphs enhancements
  app/src/components/Distributions.tsx
  app/src/components/HorizontalNav.tsx
  app/src/components/Loading.tsx
  app/src/containers/Dataset.tsx
  fiftyone/server/main.py
Labels: app, enhancement

#1001 Update remote notebook FAQ
  docs/source/environments/index.rst
  docs/source/faq/index.rst
Labels: documentation

#1010 Fixes App-based label tagging for patches views
  app/src/components/CheckboxGroup.tsx
  app/src/components/FieldsSidebar.tsx
  app/src/components/Filters/StringFilter.tsx
  app/src/components/SampleModal.tsx
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/patches.py
  fiftyone/core/stages.py
  fiftyone/core/state.py
  fiftyone/core/view.py
  fiftyone/server/utils.py
  fiftyone/utils/patches.py
  fiftyone/utils/video.py
  tests/intensive/patches_tests.py
  tests/unittests/patches_tests.py
Labels: bug

#1032 TensorFlow VGG zoo model only supports TF1
  fiftyone/zoo/models/manifest-tf.json
Labels: bug

#1033 Adding FAQ answers
  docs/source/faq/index.rst
  docs/source/user_guide/using_datasets.rst
Labels: documentation

#1034 Fixing multiprocess initialization bug when loading Open Images dataset (#1)
  fiftyone/utils/openimages.py
Labels: bug, dataset-zoo, hotfix

#1040 App video issues
  fiftyone/server/main.py
Labels: app, bug, server

#1037 Patch release v0.9.2
  setup.py
Labels: bug, release

#1044 Color by label fixes
  app/package.json
  app/src/recoil/selectors.ts
  app/src/utils/colors.ts
  app/yarn.lock
Labels: app, bug

#1047 Fix the Labelbox ID used when importing samples
  fiftyone/utils/labelbox.py
Labels: bug

#1057 Bump `npsphinx` docs requirement
  .github/workflows/build-docs.yml
  requirements/docs.txt
Labels: bug

#1051 Adding a match_labels() stage
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/expressions.py
  fiftyone/core/stages.py
  tests/unittests/view_tests.py
Labels: feature

#1053 Syntax sugar for running multiple aggregations of the same type
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/metadata.py
  fiftyone/core/patches.py
  fiftyone/core/stages.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/labelbox.py
  fiftyone/utils/scale.py
Labels: enhancement

#1054 Adds support for using hashlib to compute filehashes
  fiftyone/core/utils.py
Labels: enhancement

#1055 Adding support for rendering edges on plotly scatterplots
  fiftyone/core/plots/plotly.py
  fiftyone/core/plots/views.py
Labels: feature
