Repository voxel51/fiftyone, pull requests merged in 2021-04, with the labels that each got.

#950 Update docs homepage
  docs/source/_static/images/homepage_curate.gif
  docs/source/_static/images/homepage_embeddings.gif
  docs/source/_static/images/homepage_evaluate.gif
  docs/source/_static/images/homepage_mistakes.gif
  docs/source/_static/images/homepage_redundant.gif
  docs/source/custom_directives.py
  docs/source/images/homepage_integrations.png
  docs/source/index.rst
Labels: documentation

#957 Updating migration revision
  fiftyone/migrations/revisions/v0_8_0.py
Labels: bug

#958 Updating confusion matrices in evaluation documentation
  docs/source/_templates/layout.html
  docs/source/conf.py
  docs/source/getting_started/install.rst
  docs/source/images/evaluation/cifar10_binary_pr_curve.png
  docs/source/images/evaluation/cifar10_simple_confusion_matrix.png
  docs/source/images/evaluation/coco_pr_curve.png
  docs/source/images/evaluation/coco_pr_curves.png
  docs/source/user_guide/evaluation.rst
Labels: documentation

#959 Release hotfixes
  docs/source/images/evaluation/imagenet_top_k_eval.png
  docs/source/user_guide/brain.rst
  docs/source/user_guide/evaluation.rst
  docs/source/user_guide/plots.rst
  fiftyone/core/plots/plotly.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/segmentation.py
  setup.py
Labels: bug, documentation

#967 Adding ordered flag to select stage
  fiftyone/core/collections.py
  fiftyone/core/stages.py
  tests/unittests/view_tests.py
Labels: core, enhancement

#964 Proper handling of lists of expressions in view stages
  app/src/components/ViewBar/ViewStage/ViewStageParameter.tsx
  app/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts
  app/src/utils/generic.ts
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/expressions.py
  fiftyone/core/stages.py
Labels: bug

#970 Adding support for controlling whether label selection/exclusion omits samples with no labels
  fiftyone/core/collections.py
  fiftyone/core/stages.py
Labels: enhancement

#965 Expanded view counts and selection
  app/src/components/Actions/ActionsRow.tsx
  app/src/components/Actions/Popout.tsx
  app/src/components/Actions/Selected.tsx
  app/src/components/Actions/utils.tsx
  app/src/components/FieldsSidebar.tsx
  app/src/components/Filters/LabelFieldFilter.tsx
  app/src/components/Filters/LabelFieldFilters.state.tsx
  app/src/components/JSONView.tsx
  app/src/components/SampleModal.tsx
  app/src/components/utils.tsx
Labels: app, bug, enhancement

#972 Stricter `str` stage parameter validation
  app/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts
  fiftyone/core/stages.py
Labels: app, bug

#963 Grid zooming and slider improvements
  app/src/components/Actions/ActionsRow.tsx
  app/src/components/Filters/LabelFieldFilter.tsx
  app/src/components/Filters/NumericFieldFilter.tsx
  app/src/components/Filters/RangeSlider.stories.tsx
  app/src/components/Filters/RangeSlider.tsx
  app/src/components/ImageContainerHeader.tsx
  app/src/components/Samples.hooks.ts
  app/src/recoil/selectors.ts
  app/src/utils/labels.ts
  app/src/utils/tile.ts
  docs/source/user_guide/config.rst
  fiftyone/core/config.py
Labels: app, design, feature

#979 Converting patches to a ViewStage
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/document.py
  fiftyone/core/patches.py
  fiftyone/core/runs.py
  fiftyone/core/sample.py
  fiftyone/core/session.py
  fiftyone/core/stages.py
  fiftyone/core/state.py
  fiftyone/core/utils.py
  fiftyone/core/view.py
  fiftyone/server/main.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/patches.py
Labels: feature

#976 Adding method to delete labels from datasets
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/stages.py
  tests/unittests/dataset_tests.py
Labels: feature

#977 Adding class summaries to API docs
  docs/source/conf.py
Labels: documentation

#978 Adding a sort_by_similarity() view stage
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/runs.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
Labels: feature

#984 Adding support for passing expressions directly to aggregations
  docs/source/user_guide/plots.rst
  docs/source/user_guide/using_aggregations.rst
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/plots/base.py
  fiftyone/core/plots/matplotlib.py
  fiftyone/core/plots/plotly.py
  fiftyone/core/plots/views.py
  tests/unittests/aggregation_tests.py
Labels: enhancement

#983 Adding support for embedded documents in values() and set_values()
  docs/source/user_guide/using_aggregations.rst
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/fields.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/document.py
  fiftyone/core/odm/mixins.py
  fiftyone/utils/eval/classification.py
  tests/unittests/view_tests.py
Labels: enhancement
