Repository voxel51/fiftyone, pull requests merged in 2021-12, with the labels that each got.

#1483 Note explicit Flash version dependency
  docs/source/integrations/lightning_flash.rst
Labels: documentation

#1465 Adding support for importing/exporting confidence in YOLO formats
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/utils/yolo.py
  tests/unittests/import_export_tests.py
Labels: enhancement

#1467 Fix CVAT single frame track bug
  fiftyone/utils/cvat.py
Labels: bug, annotation

#1478 Return sample IDs with unexpected annotations
  docs/source/integrations/cvat.rst
  docs/source/user_guide/annotation.rst
  fiftyone/core/collections.py
  fiftyone/utils/annotations.py
Labels: enhancement, needs-discussion, annotation

#1455 Handle deleted tasks during annotation with CVAT
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
Labels: enhancement, annotation

#1485 Reverting nbsphinx version
  requirements/docs.txt
Labels: bug

#1491 Documenting default COCO label_types
  docs/source/user_guide/dataset_creation/datasets.rst
Labels: documentation

#1486 Adding admin DB note to docs
  docs/source/user_guide/config.rst
Labels: documentation, setup

#1493 Adding support for passing data map directory to importers
  fiftyone/core/dataset.py
  fiftyone/utils/bdd.py
  fiftyone/utils/coco.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/geojson.py
  fiftyone/utils/kitti.py
  fiftyone/utils/voc.py
Labels: enhancement

#1495 Sanitize CVAT URLs
  fiftyone/utils/cvat.py
Labels: enhancement, annotation

#1457 Add task_size parameter to CVAT backend
  docs/source/integrations/cvat.rst
  fiftyone/utils/cvat.py
Labels: bug, feature, annotation

#1490 Adding confidence thresholds to PR/ROC curves
  fiftyone/core/plots/base.py
  fiftyone/core/plots/plotly.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/openimages.py
Labels: enhancement
