Repository voxel51/fiftyone, pull requests merged in 2021-02, with the labels that each got.

#832 Dataset and ViewStage method args improvements
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/stages.py
Labels: enhancement

#834 Adding support for aggregating on expressions
  docs/source/user_guide/using_aggregations.rst
  fiftyone/__public__.py
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/expressions.py
  fiftyone/core/stages.py
Labels: feature

#836 Adding migration API
  docs/source/cli/index.rst
  docs/source/faq/index.rst
  docs/source/getting_started/install.rst
  fiftyone/__init__.py
  fiftyone/core/cli.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
  fiftyone/core/service.py
  fiftyone/core/uid.py
  fiftyone/core/utils.py
  fiftyone/migrations/__init__.py
  fiftyone/migrations/revisions/admin/v0_7_1.py
  fiftyone/migrations/revisions/v0_6_2.py
  fiftyone/migrations/revisions/v0_6_5.py
  fiftyone/migrations/revisions/v0_7_2.py
  fiftyone/migrations/runner.py
  fiftyone/server/main.py
  fiftyone/utils/uid.py
  tests/unittests/dataset_tests.py
  tests/unittests/synchronization_tests.py
  tests/unittests/utils_tests.py
Labels: core, feature

#847 Remove `--index` flag from troutblshooting page installs
  docs/source/getting_started/troubleshooting.rst
Labels: documentation

#846 Adding support for storing logits from zoo models
  docs/source/_includes/substitutions.rst
  docs/source/cli/index.rst
  docs/source/user_guide/model_zoo/index.rst
  fiftyone/core/cli.py
  fiftyone/core/collections.py
  fiftyone/core/eta_utils.py
  fiftyone/core/models.py
  fiftyone/utils/torch.py
  fiftyone/zoo/models/manifest-tf.json
  fiftyone/zoo/models/manifest-torch.json
  tests/intensive/model_zoo_tests.py
Labels: feature

#841 Adding support for accessing samples by filepath
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/view.py
Labels: enhancement, needs-discussion

#842 Adds support for returning a single sample matching an expression
  fiftyone/core/collections.py
Labels: enhancement, needs-discussion

#849 Adding support for evaluating classifications
  docs/source/user_guide/using_aggregations.rst
  fiftyone/__public__.py
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/expressions.py
  fiftyone/core/fields.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/odm/sample.py
  fiftyone/core/sample.py
  fiftyone/core/stages.py
  fiftyone/core/state.py
  fiftyone/core/validation.py
  fiftyone/core/view.py
  fiftyone/server/main.py
  fiftyone/utils/eval/__init__.py
  fiftyone/utils/eval/classification.py
  requirements/common.txt
  setup.py
  tests/unittests/aggregation_tests.py
Labels: feature

#850 Adding util to get stats about a dataset
  fiftyone/core/dataset.py
Labels: feature

#851 Move default confidence thresholds to zoo model configs
  fiftyone/core/cli.py
  fiftyone/core/collections.py
  fiftyone/core/models.py
  fiftyone/utils/torch.py
  fiftyone/zoo/models/manifest-tf.json
  fiftyone/zoo/models/manifest-torch.json
Labels: enhancement

#856 Defaulting only_matches to True
  fiftyone/core/collections.py
  fiftyone/core/expressions.py
  fiftyone/core/stages.py
  fiftyone/server/main.py
  tests/intensive/model_zoo_tests.py
Labels: enhancement

#854 Evaluation API
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/config.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/frame.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/odm/evaluation.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/stages.py
  fiftyone/core/state.py
  fiftyone/core/view.py
  fiftyone/migrations/revisions/v0_7_3.py
  fiftyone/utils/eval/__init__.py
  fiftyone/utils/eval/base.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/torch.py
  tests/unittests/dataset_tests.py
  tests/unittests/view_tests.py
Labels: feature

#858 Adding support for cloning and saving views into video datasets
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/frame.py
  fiftyone/core/odm/document.py
  fiftyone/core/sample.py
  fiftyone/core/view.py
  tests/unittests/sample_tests.py
Labels: enhancement

#863 Adding support for evaluating segmentation models
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/utils/eval/__init__.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/segmentation.py
  tests/isolated/service_tests.py
Labels: feature

#866 Adding support for extracting values from nested array fields
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/stages.py
  tests/unittests/aggregation_tests.py
Labels: enhancement

#867 Adding support for evaluating video classifications
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/expressions.py
  fiftyone/core/stages.py
  fiftyone/server/main.py
  fiftyone/utils/eval/base.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/segmentation.py
  tests/intensive/collections_tests.py
  tests/intensive/evaluation_tests.py
Labels: feature

#868 Adding evaluation to user guide
  docs/source/_includes/substitutions.rst
  docs/source/images/evaluation/cifar10_binary_pr_curve.png
  docs/source/images/evaluation/cifar10_simple_confusion_matrix.png
  docs/source/images/evaluation/evaluate_segmentations.gif
  docs/source/images/evaluation/imagenet_top_k_eval.png
  docs/source/images/evaluation/quickstart_evaluate_detections.gif
  docs/source/images/evaluation/quickstart_evaluate_detections.png
  docs/source/user_guide/evaluation.rst
  docs/source/user_guide/index.rst
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/detection.py
Labels: documentation

#864 Calculate COCO mAP
  docs/source/_includes/substitutions.rst
  docs/source/images/evaluation/coco_pr_curve.png
  docs/source/user_guide/evaluation.rst
  fiftyone/core/collections.py
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/detection.py
Labels: core, feature

#869 Adding support for gracefully skipping samples whose metadata cannot be computed
  fiftyone/core/collections.py
  fiftyone/core/expressions.py
  fiftyone/core/metadata.py
  fiftyone/core/sample.py
  fiftyone/core/stages.py
  fiftyone/utils/metadata.py
Labels: enhancement

#879 Patch python import logging
  fiftyone/core/uid.py
  setup.py
  tests/unittests/utils_tests.py
Labels: bug, release

#878 Docs refresh
  docs/source/_includes/substitutions.rst
  docs/source/_static/images/recipes/adding_classifications.png
  docs/source/_static/images/recipes/adding_detections.png
  docs/source/_static/images/recipes/detection_mistakenness.png
  docs/source/_static/images/recipes/model_inference.png
  docs/source/_static/images/tutorials/classification_mistakes.png
  docs/source/_static/images/tutorials/detection_mistakes.png
  docs/source/_static/images/tutorials/label_mistakes.png
  docs/source/cli/index.rst
  docs/source/environments/index.rst
  docs/source/faq/index.rst
  docs/source/getting_started/troubleshooting.rst
  docs/source/getting_started/virtualenv.rst
  docs/source/index.rst
  docs/source/recipes/images/det_mistakenness_6.png
  docs/source/recipes/index.rst
  docs/source/recipes/model_inference.ipynb
  docs/source/redirects
  docs/source/release-notes.rst
  docs/source/tutorials/classification_mistakes.ipynb
  docs/source/tutorials/images/det_mistakenness_6.png
  docs/source/tutorials/index.rst
  docs/source/tutorials/label_mistakes.ipynb
  docs/source/user_guide/app.rst
  docs/source/user_guide/basics.rst
  docs/source/user_guide/brain.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_creation/index.rst
  docs/source/user_guide/dataset_creation/samples.rst
  docs/source/user_guide/dataset_zoo/api.rst
  docs/source/user_guide/dataset_zoo/datasets.rst
  docs/source/user_guide/dataset_zoo/index.rst
  docs/source/user_guide/draw_labels.rst
  docs/source/user_guide/evaluation.rst
  docs/source/user_guide/export_datasets.rst
  docs/source/user_guide/index.rst
  docs/source/user_guide/model_zoo/api.rst
  docs/source/user_guide/model_zoo/index.rst
  docs/source/user_guide/using_aggregations.rst
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/core/utils.py
Labels: documentation

#887 Adding dataset stats to CLI
  docs/source/cli/index.rst
  fiftyone/core/cli.py
Labels: enhancement

#886 Limit progress bar width to 90 characters in notebook contexts
  fiftyone/core/context.py
  fiftyone/core/utils.py
Labels: enhancement, notebook

#888 Add missing installation steps to App README
  app/README.md
Labels: documentation

#890 Fixing Labelbox bugs
  fiftyone/core/utils.py
  fiftyone/utils/labelbox.py
Labels: bug, core

#881 Adding support for tracking and cleaning up brain method runs
  docs/source/user_guide/brain.rst
  fiftyone/__public__.py
  fiftyone/core/brain.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/evaluation.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/odm/evaluation.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/odm/runs.py
  fiftyone/core/runs.py
  fiftyone/core/validation.py
  fiftyone/migrations/revisions/v0_7_3.py
  fiftyone/migrations/revisions/v0_7_4.py
  fiftyone/migrations/runner.py
  fiftyone/utils/eval/__init__.py
  fiftyone/utils/eval/base.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/segmentation.py
  tests/README.md
Labels: feature

#889 Adding low-level utilities for listing and deleting datasets
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
Labels: enhancement
