Repository voxel51/fiftyone, pull requests merged in 2021-11, with the labels that each got.

#1388 Add model predictions section to docs
  docs/source/user_guide/dataset_creation/index.rst
Labels: documentation

#1377 Multilabel classification import/export
  docs/source/recipes/custom_importer.ipynb
  docs/source/recipes/custom_parser.ipynb
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_creation/samples.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/data/parsers.py
  tests/unittests/import_export_tests.py
Labels: enhancement

#1353 Adding a Regression label type
  app/packages/app/src/components/Filters/LabelFieldFilter.tsx
  app/packages/app/src/components/Filters/LabelFieldFilters.state.tsx
  app/packages/app/src/components/Looker.tsx
  app/packages/app/src/utils/labels.ts
  app/packages/looker/src/constants.ts
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/overlays/classifications.ts
  docs/source/_includes/substitutions.rst
  docs/source/images/evaluation/regression_evaluation_plot.png
  docs/source/images/plots/regression-evaluation.gif
  docs/source/user_guide/basics.rst
  docs/source/user_guide/evaluation.rst
  docs/source/user_guide/plots.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/labels.py
  fiftyone/core/plots/__init__.py
  fiftyone/core/plots/base.py
  fiftyone/core/plots/manager.py
  fiftyone/core/plots/matplotlib.py
  fiftyone/core/plots/plotly.py
  fiftyone/core/state.py
  fiftyone/utils/eval/__init__.py
  fiftyone/utils/eval/regression.py
  fiftyone/utils/eval/segmentation.py
  tests/intensive/evaluation_tests.py
  tests/unittests/evaluation_tests.py
Labels: feature

#1386 Fixing import of FiftyOneDataset instances with run results
  fiftyone/core/dataset.py
  fiftyone/core/runs.py
  fiftyone/utils/data/importers.py
  tests/unittests/import_export_tests.py
Labels: bug

#1370 Apache beam I/O
  fiftyone/core/dataset.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/odm/sample.py
  fiftyone/utils/beam.py
Labels: feature

#1384 Upgrading YOLO I/O and general I/O docs
  docs/source/_includes/substitutions.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_creation/index.rst
  docs/source/user_guide/export_datasets.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/utils/bdd.py
  fiftyone/utils/coco.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/dicom.py
  fiftyone/utils/geojson.py
  fiftyone/utils/geotiff.py
  fiftyone/utils/kitti.py
  fiftyone/utils/openimages.py
  fiftyone/utils/tf.py
  fiftyone/utils/voc.py
  fiftyone/utils/yolo.py
  tests/unittests/import_export_tests.py
Labels: documentation, enhancement

#1392 Fix count values for colab
  fiftyone/server/main.py
Labels: app, notebook

#1350 Graceful handling of nan and inf field values
  app/packages/app/src/components/Common/Checkbox.tsx
  app/packages/app/src/components/FieldsSidebar.tsx
  app/packages/app/src/components/Filters/CategoricalFilter.tsx
  app/packages/app/src/components/Filters/DateTimeFilter.tsx
  app/packages/app/src/components/Filters/Exclude.tsx
  app/packages/app/src/components/Filters/LabelFieldFilter.tsx
  app/packages/app/src/components/Filters/LabelFieldFilters.state.tsx
  app/packages/app/src/components/Filters/NumericFieldFilter.state.ts
  app/packages/app/src/components/Filters/NumericFieldFilter.tsx
  app/packages/app/src/components/Filters/RangeSlider.tsx
  app/packages/looker/src/constants.ts
  app/packages/looker/src/overlays/base.ts
  app/packages/looker/src/overlays/detection.ts
  app/packages/looker/src/state.ts
  app/yarn.lock
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/state.py
  fiftyone/server/extended_view.py
  fiftyone/server/json_util.py
  fiftyone/server/main.py
  tests/unittests/aggregation_tests.py
Labels: bug, app, core

#1391 Track label IDs using CVAT server IDs
  docs/source/integrations/cvat.rst
  fiftyone/utils/cvat.py
Labels: enhancement

#1393 Add support for non-sequential updates in set_values()
  fiftyone/core/collections.py
  tests/unittests/view_tests.py
Labels: enhancement

#1396 [BUG] Fix bug when annotating new fields in CVAT
  fiftyone/utils/cvat.py
Labels: bug

#1397 Hotfix
  fiftyone/core/collections.py
Labels: bug

#1404 bug: gcsfuse command
  docs/source/environments/index.rst
Labels: bug, documentation

#1407 Fixed model oom
  fiftyone/utils/torch.py
  fiftyone/zoo/models/manifest-torch.json
  tests/misc/torch_tests.py
Labels: enhancement

#1401 Fix bug when annotating videos in CVAT with None label field
  fiftyone/utils/annotations.py
Labels: bug

#1409 Fixing to_frames() bug
  fiftyone/core/video.py
Labels: bug

#1412 Windows App script FAQ
  docs/source/faq/index.rst
  docs/source/user_guide/app.rst
Labels: documentation

#1414 Fixes #1413
  fiftyone/core/dataset.py
Labels: bug

#1417 Documenting ffmpeg dependency more prominently
  docs/source/getting_started/install.rst
  docs/source/getting_started/troubleshooting.rst
Labels: documentation

#1411 Updating dependencies for build workflows
  .github/workflows/build-docs.yml
  .github/workflows/build.yml
  docs/source/user_guide/using_datasets.rst
  requirements/dev.txt
  requirements/docs.txt
  requirements/extras.txt
Labels: dependencies, ci

#1402 Use threading for COCO and Open Images S3 downloads
  fiftyone/utils/aws.py
  fiftyone/utils/coco.py
  fiftyone/utils/openimages.py
Labels: enhancement

#1416 Adding note on supported browsers
  docs/source/faq/index.rst
  docs/source/user_guide/app.rst
Labels: documentation

#1423 Add global occlusion widget parameter for CVAT annotation runs
  docs/source/integrations/cvat.rst
  fiftyone/utils/cvat.py
Labels: feature

#1424 Server metadata optmizations
  fiftyone/core/metadata.py
  fiftyone/server/main.py
  fiftyone/server/metadata.py
  fiftyone/server/utils.py
  requirements/common.txt
  setup.py
Labels: enhancement, server

#1425 Release v0.14.1
  app/package.json
  app/packages/app/package.json
  app/packages/desktop/package.json
  docs/source/release-notes.rst
  package/desktop/setup.py
  setup.py
Labels: release

#1436 Better handling of relative and user paths
  fiftyone/core/config.py
Labels: enhancement

#1437 Optimizing image metadata calculation
  fiftyone/core/metadata.py
  fiftyone/core/utils.py
  requirements/extras.txt
Labels: enhancement

#1438 Optimize worker label processing
  app/packages/looker/src/index.ts
  app/packages/looker/src/worker.ts
Labels: enhancement, app

#1433 Retain original filenames when annotating in CVAT
  fiftyone/utils/cvat.py
Labels: enhancement, annotation

#1429 Raising error when annotating video label field not starting with "frames."
  fiftyone/utils/annotations.py
Labels: enhancement, annotation

#1445 More robust attribute parsing
  fiftyone/core/cli.py
  fiftyone/core/config.py
  fiftyone/utils/cvat.py
  fiftyone/utils/voc.py
Labels: enhancement

#1444 Model inference/embeddings enhancements
  fiftyone/core/models.py
  fiftyone/core/runs.py
  fiftyone/utils/annotations.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/regression.py
  fiftyone/utils/eval/segmentation.py
  fiftyone/utils/torch.py
  tests/misc/torch_tests.py
Labels: enhancement

#1447 Release v0.14.2
  app/package.json
  app/packages/app/package.json
  app/packages/desktop/package.json
  docs/source/release-notes.rst
  package/desktop/setup.py
  setup.py
Labels: release

#1452 Fixing Torch/TF zoo dataset loading bug
  fiftyone/zoo/datasets/tf.py
  fiftyone/zoo/datasets/torch.py
Labels: bug, dataset-zoo

#1449 Adding support for passing headers to CVAT API
  docs/source/integrations/cvat.rst
  fiftyone/utils/cvat.py
Labels: enhancement

#1450 Gracefully cast all int/float types to python primitives
  fiftyone/core/collections.py
  fiftyone/core/fields.py
  fiftyone/core/frame_utils.py
  fiftyone/core/odm/mixins.py
  tests/unittests/dataset_tests.py
Labels: enhancement

#1454 Fixing #1453
  fiftyone/utils/eval/coco.py
Labels: bug
