Repository voxel51/fiftyone, pull requests merged in 2022-02, with the labels that each got.

#1524 Add utility to download videos from YouTube
  fiftyone/utils/youtube.py
Labels: feature, dataset zoo

#1577 Update CVAT request error handling
  fiftyone/utils/cvat.py
Labels: enhancement, annotation

#1575 Fix builds
  .github/workflows/build.yml
  tests/unittests/import_export_tests.py
Labels: bug

#1582 Fix README slack link
  README.md
Labels: bug, documentation, cleaning

#1580 Apply patch to YouTube download utilities
  fiftyone/utils/youtube.py
Labels: bug

#1586 Fixing frame aggregations
  fiftyone/core/aggregations.py
  tests/unittests/aggregation_tests.py
Labels: bug

#1578 Improving to_frames() implementation
  docs/source/release-notes.rst
  docs/source/user_guide/evaluation.rst
  docs/source/user_guide/using_views.rst
  fiftyone/core/collections.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/stages.py
  fiftyone/core/video.py
  fiftyone/utils/video.py
  tests/intensive/video_tests.py
  tests/unittests/video_tests.py
Labels: enhancement

#1403 Add Kinetics dataset to the zoo
  docs/source/images/dataset_zoo/kinetics.png
  docs/source/user_guide/dataset_zoo/datasets.rst
  fiftyone/utils/data/importers.py
  fiftyone/utils/kinetics.py
  fiftyone/zoo/datasets/base.py
Labels: dataset zoo

#1576 Release v0.14.4
  app/package.json
  app/packages/app/package.json
  app/packages/desktop/package.json
  docs/source/_includes/substitutions.rst
  docs/source/release-notes.rst
  docs/source/user_guide/annotation.rst
  package/desktop/setup.py
  setup.py
Labels: release

#1583 Add support for per-point confidences in Keypoint class
  fiftyone/core/labels.py
  fiftyone/utils/coco.py
  fiftyone/utils/eta.py
  fiftyone/utils/torch.py
Labels: enhancement

#1604 Update regression
  app/packages/app/src/components/Filters/LabelFieldFilter.tsx
Labels: bug, app

#1343 Add Databricks notebook visualization
  app/packages/app/src/shared/connection.ts
  app/packages/looker/src/util.ts
  fiftyone/core/context.py
  fiftyone/core/service.py
  fiftyone/core/session.py
  fiftyone/utils/templates.py
Labels: feature
