Repository voxel51/fiftyone, pull requests merged in 2022-09, with the labels that each got.

#2043 Keep app_config in sync with dataset schema changes
  app/packages/app/src/Root/Datasets/__generated__/DatasetQuery.graphql.ts
  app/packages/relay/src/mutations/__generated__/setViewMutation.graphql.ts
  app/packages/state/src/recoil/aggregations.ts
  app/packages/state/src/recoil/atoms.ts
  app/packages/state/src/recoil/schema.ts
  app/schema.graphql
  docs/source/images/app/app-multiple-media-fields.gif
  docs/source/user_guide/app.rst
  docs/source/user_guide/config.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/core/dataset.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/odm/mixins.py
  fiftyone/server/query.py
  tests/unittests/dataset_tests.py
Labels: enhancement

#2048 Adding support for linking directly to imported subpackage contents
  docs/source/_includes/substitutions.rst
  docs/source/release-notes.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_creation/samples.rst
  docs/source/user_guide/export_datasets.rst
  docs/source/user_guide/plots.rst
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/plots/__init__.py
  fiftyone/core/plots/manager.py
  fiftyone/core/session/__init__.py
  fiftyone/core/session/client.py
  fiftyone/core/session/events.py
  fiftyone/core/session/notebooks.py
  fiftyone/core/session/session.py
  fiftyone/migrations/__init__.py
  fiftyone/types/__init__.py
  fiftyone/utils/cityscapes.py
  fiftyone/utils/data/__init__.py
  fiftyone/utils/data/base.py
  fiftyone/utils/data/converters.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/eval/__init__.py
  fiftyone/utils/openimages.py
  fiftyone/zoo/__init__.py
  fiftyone/zoo/datasets/__init__.py
Labels: documentation, enhancement

#2055 Optimizing group selection in server get_view()
  fiftyone/core/view.py
  fiftyone/server/view.py
Labels: enhancement

#2053 Improving groups migration
  fiftyone/core/cli.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/dataset.py
  fiftyone/migrations/revisions/v0_17_0.py
Labels: enhancement

#2051 Fixing custom embedded documents regression
  docs/source/_includes/substitutions.rst
  docs/source/release-notes.rst
  fiftyone/core/odm/utils.py
  tests/unittests/dataset_tests.py
Labels: bug

#2025 Persistent group slice in expanded view
  app/packages/app/src/Root/Datasets/__generated__/DatasetDataQuery.graphql.ts
  app/packages/app/src/Root/Datasets/__generated__/DatasetData_query.graphql.ts
  app/packages/app/src/components/Common/CountSubcount.tsx
  app/packages/app/src/components/Common/LoadingCircle.tsx
  app/packages/app/src/components/Grid/Grid.tsx
  app/packages/app/src/components/Grid/recoil.ts
  app/packages/app/src/components/Grid/useExpandSample.ts
  app/packages/app/src/components/Group/Group.tsx
  app/packages/app/src/components/GroupSliceSelector.tsx
  app/packages/app/src/components/Modal/Group.tsx
  app/packages/app/src/components/Modal/Looker.tsx
  app/packages/app/src/components/Modal/Sample.tsx
  app/packages/app/src/components/Sidebar/Entries/PathValueEntry.tsx
  app/packages/relay/src/queries/__generated__/mainSampleQuery.graphql.ts
  app/packages/relay/src/queries/__generated__/paginateGroupPinnedSample_query.graphql.ts
  app/packages/relay/src/queries/__generated__/paginateGroupQuery.graphql.ts
  app/packages/relay/src/queries/index.ts
  app/packages/relay/src/queries/mainSample.ts
  app/packages/relay/src/queries/paginateGroup.ts
  app/packages/state/src/hooks/useCreateLooker.ts
  app/packages/state/src/hooks/useExpandSample.ts
  app/packages/state/src/hooks/useSetExpandedSample.ts
  app/packages/state/src/hooks/useStateUpdate.ts
  app/packages/state/src/recoil/aggregations.ts
  app/packages/state/src/recoil/atoms.ts
  app/packages/state/src/recoil/groups.ts
  app/packages/state/src/recoil/modal.ts
  app/packages/state/src/recoil/selectors.ts
Labels: enhancement

#2056 Bugfixes for Groups/Looker3D
  app/packages/app/src/components/Modal/Looker.tsx
  app/packages/components/src/components/HelpPanel/HelpPanel.tsx
  app/packages/looker-3d/src/Looker3d.tsx
  app/packages/looker-3d/src/Looker3dPlugin.tsx
Labels: app

#2061 Adding plugins docs/env var
  app/packages/plugins/README.md
  docs/source/user_guide/app.rst
  docs/source/user_guide/config.rst
  fiftyone/core/config.py
  fiftyone/server/app.py
  fiftyone/server/routes/plugins.py
Labels: documentation

#2060 Adding rel_dir to export() and draw_labels()
  docs/source/getting_started/install.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/core/collections.py
  fiftyone/core/utils.py
  fiftyone/utils/annotations.py
  fiftyone/utils/bdd.py
  fiftyone/utils/coco.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/geojson.py
  fiftyone/utils/kitti.py
  fiftyone/utils/voc.py
  fiftyone/utils/yolo.py
  tests/unittests/import_export_tests.py
Labels: bug

#1691 Add CLIP to the model zoo
  docs/scripts/make_model_zoo_docs.py
  fiftyone/utils/clip/__init__.py
  fiftyone/utils/clip/model.py
  fiftyone/utils/clip/tokenizer.py
  fiftyone/utils/clip/zoo.py
  fiftyone/zoo/models/manifest-torch.json
  tests/intensive/model_zoo_tests.py
Labels: feature

#2038 Group statistics and tagging mode
  app/packages/app/src/components/Actions/Checker.tsx
  app/packages/app/src/components/Actions/Options.tsx
  app/packages/app/src/components/Actions/Tagger.tsx
  app/packages/app/src/components/Actions/utils.tsx
  app/packages/app/src/components/Grid/Grid.tsx
  app/packages/app/src/components/ImageContainerHeader.tsx
  app/packages/app/src/components/Modal/Sample.tsx
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/zoom.ts
  app/packages/relay/src/mutations/__generated__/setViewMutation.graphql.ts
  app/packages/relay/src/mutations/setView.ts
  app/packages/state/src/hooks/useExpandSample.ts
  app/packages/state/src/hooks/useSetExpandedSample.ts
  app/packages/state/src/recoil/aggregations.ts
  app/packages/state/src/recoil/groups.ts
  app/packages/state/src/recoil/index.ts
  app/packages/state/src/recoil/schema.ts
  docs/source/images/groups/groups-stats.gif
  docs/source/user_guide/groups.rst
  fiftyone/core/view.py
  fiftyone/server/routes/aggregations.py
  fiftyone/server/routes/pin.py
  fiftyone/server/routes/tag.py
  fiftyone/server/routes/tagging.py
  fiftyone/server/samples.py
  fiftyone/server/view.py
Labels: app

#2069 Fix Colab sessions and screenshotting
  app/README.md
  app/packages/app/src/index.tsx
  app/packages/utilities/src/fetch.ts
  fiftyone/core/context.py
  fiftyone/core/service.py
  fiftyone/core/session/notebooks.py
  fiftyone/core/session/session.py
  fiftyone/core/session/templates.py
  fiftyone/server/events.py
  fiftyone/server/samples.py
  fiftyone/utils/templates.py
  install.bash
  requirements/common.txt
Labels: bug, notebook, colab

#2070 Fix CVAT bug when checking if a task exists
  fiftyone/utils/cvat.py
  tests/intensive/cvat_tests.py
Labels: bug, annotation

#1869 Load all COCO label types by default
  docs/source/user_guide/dataset_creation/datasets.rst
  fiftyone/core/document.py
  fiftyone/core/odm/mixins.py
  fiftyone/utils/coco.py
  fiftyone/zoo/datasets/__init__.py
  fiftyone/zoo/datasets/base.py
  tests/unittests/import_export_tests.py
Labels: enhancement

#2044 Session group slice
  app/packages/app/src/Root/Datasets/Dataset.tsx
  app/packages/app/src/Root/Datasets/__generated__/DatasetQuery.graphql.ts
  app/packages/app/src/components/Actions/Selected.tsx
  app/packages/app/src/components/Actions/Tagger.tsx
  app/packages/app/src/components/Actions/utils.tsx
  app/packages/app/src/components/GroupSliceSelector.tsx
  app/packages/app/src/components/Sidebar/Entries/PathValueEntry.tsx
  app/packages/relay/src/mutations/__generated__/setGroupSliceMutation.graphql.ts
  app/packages/relay/src/mutations/__generated__/setViewMutation.graphql.ts
  app/packages/relay/src/mutations/index.ts
  app/packages/relay/src/mutations/setGroupSlice.ts
  app/packages/relay/src/mutations/setView.ts
  app/packages/state/src/hooks/index.ts
  app/packages/state/src/hooks/useSetGroupSlice.ts
  app/packages/state/src/hooks/useStateUpdate.ts
  app/packages/state/src/recoil/types.ts
  app/schema.graphql
  fiftyone/core/clips.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/patches.py
  fiftyone/core/session/session.py
  fiftyone/core/stages.py
  fiftyone/core/state.py
  fiftyone/core/video.py
  fiftyone/core/view.py
  fiftyone/server/mutation.py
  fiftyone/server/query.py
  fiftyone/server/view.py
  tests/unittests/group_tests.py
Labels: enhancement, app

#2074 Resolve Labelstudio task_map key error
  fiftyone/utils/labelstudio.py
Labels: bug, annotation

#2072 CLIP tweaks
  docs/scripts/make_model_zoo_docs.py
  fiftyone/utils/clip/__init__.py
  fiftyone/utils/clip/model.py
  fiftyone/utils/clip/tokenizer.py
  fiftyone/utils/clip/zoo.py
  fiftyone/zoo/models/manifest-torch.json
  fiftyone/zoo/models/torch.py
Labels: cleaning

#2075 Looker3D Settings Issue
  app/packages/utilities/src/index.ts
Labels: app

#2076 Fix Looker3D escape sequence
  app/packages/looker-3d/src/Looker3d.tsx
Labels: app

#2081 fix pinned sample not clearing
  app/packages/app/src/components/Modal/Group.tsx
Labels: app

#2082 Add Qdrant Tutorial
  docs/source/_static/images/tutorials/qdrant.png
  docs/source/index.rst
  docs/source/tutorials/index.rst
  docs/source/tutorials/qdrant.ipynb
Labels: documentation

#2083 fix L3D hotkey targeting
  app/packages/looker-3d/src/Looker3d.tsx
Labels: app

#2079 App groups fixes
  app/packages/app/src/Root/Datasets/Dataset.tsx
  app/packages/app/src/components/Actions/Tagger.tsx
  app/packages/app/src/components/Actions/utils.tsx
  app/packages/app/src/components/Grid/usePage.ts
  app/packages/app/src/components/Group/Group.tsx
  app/packages/app/src/components/Modal/Group.tsx
  app/packages/app/src/components/Modal/Looker.tsx
  app/packages/app/src/components/Sidebar/Entries/FilterablePathEntry.tsx
  app/packages/app/src/components/Sidebar/Entries/TagValueEntry.tsx
  app/packages/app/src/index.css
  app/packages/app/src/index.tsx
  app/packages/app/src/recoil/config.ts
  app/packages/app/src/recoil/utils.ts
  app/packages/looker-3d/src/Looker3d.tsx
  app/packages/looker-3d/src/Looker3dPlugin.tsx
  app/packages/looker/src/elements/common/actions.ts
  app/packages/map/src/Options.tsx
  app/packages/relay/src/queries/__generated__/mainSampleQuery.graphql.ts
  app/packages/relay/src/queries/__generated__/paginateGroupPageQuery.graphql.ts
  app/packages/relay/src/queries/__generated__/paginateGroupPinnedSample_query.graphql.ts
  app/packages/relay/src/queries/__generated__/paginateGroupQuery.graphql.ts
  app/packages/relay/src/queries/__generated__/paginateGroup_query.graphql.ts
  app/packages/relay/src/queries/mainSample.ts
  app/packages/relay/src/queries/paginateGroup.ts
  app/packages/state/src/hooks/index.ts
  app/packages/state/src/hooks/useCreateLooker.ts
  app/packages/state/src/hooks/useHoveredSample.ts
  app/packages/state/src/hooks/useLookerStore.ts
  app/packages/state/src/hooks/useUpdateSample.ts
  app/packages/state/src/recoil/atoms.ts
  app/packages/state/src/recoil/groups.ts
  app/packages/state/src/recoil/utils.ts
  app/schema.graphql
  fiftyone/core/session/events.py
  fiftyone/core/session/session.py
  fiftyone/server/metadata.py
  fiftyone/server/routes/tag.py
  fiftyone/server/routes/tagging.py
  fiftyone/server/samples.py
  schema.graphql
Labels: bug, app

#2088 Add the option to load a view or dataset for run results
  fiftyone/core/collections.py
  fiftyone/core/runs.py
  fiftyone/utils/annotations.py
  tests/intensive/cvat_tests.py
Labels: bug, annotation

#2087 Fix CVAT task id bug and add task download progress bar
  fiftyone/core/collections.py
  fiftyone/core/runs.py
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
  tests/intensive/cvat_tests.py
Labels: bug, annotation

#2089 Update Qdrant tutorial
  docs/source/tutorials/qdrant.ipynb
Labels: bug, documentation

#2093 Tagging simplification and server tests
  app/packages/app/src/components/Actions/Tagger.tsx
  app/packages/app/src/components/Actions/utils.tsx
  app/packages/app/src/components/Modal/Looker.tsx
  app/packages/looker/src/elements/common/actions.ts
  fiftyone/server/routes/tag.py
  fiftyone/server/routes/tagging.py
  fiftyone/server/tags.py
  tests/unittests/server_tests.py
Labels: enhancement, testing

#2097 Use UUIDs in dataset collection names
  fiftyone/core/dataset.py
Labels: bug

#2099 Merging v0.17 release into develop
  app/packages/app/src/components/Actions/Similar.tsx
  app/packages/app/src/components/Modal/Looker.tsx
  app/packages/state/src/hooks/useStateUpdate.ts
  app/packages/state/src/recoil/groups.ts
  app/packages/state/src/recoil/looker.ts
  app/packages/state/src/recoil/options.ts
  app/packages/state/src/recoil/types.ts
  docs/source/getting_started/install.rst
  docs/source/release-notes.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/draw_labels.rst
  fiftyone/server/query.py
  fiftyone/utils/clip/model.py
  fiftyone/utils/clip/tokenizer.py
  fiftyone/utils/clip/zoo.py
  package/desktop/setup.py
  setup.py
Labels: release

#2100 [HOTFIX] Release v0.17.1 (patch Python 3.7)
  .github/workflows/build.yml
  app/packages/app/src/Root/Datasets/Dataset.tsx
  app/packages/state/src/recoil/groups.ts
  docs/source/release-notes.rst
  fiftyone/server/tags.py
  package/desktop/setup.py
  setup.py
Labels: bug, hotfix, release

#2103 [HOTFIX] Backward Compatible App
  app/packages/state/src/hooks/useStateUpdate.ts
  docs/source/release-notes.rst
  fiftyone/server/metadata.py
  package/desktop/setup.py
  setup.py
Labels: hotfix, app, release

#2109 Move plugin imports
  app/packages/app/src/Root/Root.tsx
  app/packages/app/src/index.tsx
Labels: cleaning

#2118 Updating docs header/footer
  docs/source/_static/css/custom.css
  docs/source/_static/css/voxel51-website.css
  docs/source/_templates/layout.html
  docs/source/conf.py
Labels: documentation

#2116 Fix documentation download links
  docs/source/conf.py
Labels: bug, documentation

#2125 improve plugin install docs
  app/packages/plugins/README.md
Labels: plugins
