Repository voxel51/fiftyone, pull requests merged in 2022-11, with the labels that each got.

#2208 More tagging optimization
  fiftyone/core/clips.py
  fiftyone/core/collections.py
  fiftyone/core/patches.py
  fiftyone/core/video.py
  tests/unittests/video_tests.py
Labels: enhancement

#2193 Allow frame views to edit source frame filepaths
  fiftyone/core/patches.py
  fiftyone/core/video.py
  tests/unittests/video_tests.py
Labels: bug

#2225 Remove old session client
  fiftyone/core/client.py
Labels: cleaning

#2231 Downgrade starlette
  requirements/common.txt
  setup.py
Labels: bug

#2227 Optimizing ordered select implementation
  fiftyone/core/stages.py
Labels: enhancement

#2216 Adding support for field descriptions
  app/package.json
  app/packages/components/src/components/Icons/Icons.tsx
  app/packages/components/src/components/Icons/index.ts
  app/packages/core/src/Dataset.ts
  app/packages/core/src/__generated__/DatasetQuery.graphql.ts
  app/packages/core/src/components/FieldLabelAndInfo/index.tsx
  app/packages/core/src/components/Filters/CategoricalFilter.tsx
  app/packages/core/src/components/Filters/NumericFieldFilter.tsx
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry.tsx
  app/packages/core/src/components/Sidebar/Entries/PathValueEntry.tsx
  app/packages/core/src/components/index.ts
  app/schema.graphql
  docs/source/images/app/app-field-tooltips.gif
  docs/source/user_guide/app.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/constants.py
  fiftyone/core/clips.py
  fiftyone/core/dataset.py
  fiftyone/core/fields.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/odm/document.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/odm/utils.py
  fiftyone/core/patches.py
  fiftyone/core/state.py
  fiftyone/migrations/revisions/v0_18_0.py
  setup.py
  tests/unittests/dataset_tests.py
Labels: feature

#2190 Adding support for populating default App sidebar groups via SDK
  docs/source/release-notes.rst
  docs/source/user_guide/app.rst
  docs/source/user_guide/config.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/core/config.py
  fiftyone/core/odm/dataset.py
  fiftyone/migrations/revisions/v0_18_0.py
Labels: enhancement

#2269 Documenting app config resets
  docs/source/user_guide/app.rst
  docs/source/user_guide/using_datasets.rst
Labels: documentation

#2271 Sidebar resets
  app/packages/state/src/hooks/useStateUpdate.ts
  app/packages/state/src/recoil/sidebar.ts
Labels: app

#2274 Removed extra title
  app/packages/core/src/components/Filters/CategoricalFilter.tsx
Labels: app

#2276 App patches
  app/packages/app/src/Network.tsx
  app/packages/core/src/Dataset.ts
  app/packages/core/src/Root/Datasets/Dataset.tsx
  app/packages/core/src/components/Common/LoadingDots.module.css
  app/packages/core/src/components/Common/LoadingDots.tsx
  app/packages/core/src/components/Filters/withSuspense.tsx
  app/packages/core/src/components/SamplesContainer.tsx
  app/packages/core/src/components/Sidebar/Entries/EmptyEntry.tsx
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry.tsx
  app/packages/core/src/utils/generic.tsx
  app/packages/state/src/recoil/sidebar.ts
  app/packages/utilities/src/index.ts
  fiftyone/core/odm/dataset.py
  fiftyone/server/aggregations.py
  setup.py
Labels: bug, app

#2289 App patches
  app/packages/core/src/Dataset.ts
  app/packages/state/src/hooks/useSetExpandedSample.ts
Labels: bug, app

#2295 Updating issue templates
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/documentation_issue_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/ISSUE_TEMPLATE/installation_issue_template.md
Labels: documentation

#2304 Fixing #2302
  fiftyone/utils/data/parsers.py
  tests/unittests/dataset_tests.py
Labels: bug

#2314 Dataset package cleaning
  app/packages/core/src/Dataset.ts
  app/packages/core/src/Root/Datasets/Dataset.tsx
  app/packages/core/src/Root/Root.tsx
  app/packages/core/src/Root/__generated__/RootQuery.graphql.ts
  app/packages/core/src/components/Grid/Grid.tsx
  app/packages/core/src/components/Grid/recoil.ts
  app/packages/core/src/components/Modal/Group.tsx
  app/packages/core/src/components/SamplesContainer.tsx
  app/packages/core/src/index.ts
  app/packages/dataset/src/Dataset.tsx
  app/packages/dataset/src/index.ts
  app/packages/dataset/src/index.tsx
  app/packages/dataset/tsconfig.json
  app/packages/looker/src/state.ts
  app/packages/relay/src/queries/__generated__/configQuery.graphql.ts
  app/packages/relay/src/queries/__generated__/paginateGroupPinnedSample_query.graphql.ts
  app/packages/relay/src/queries/__generated__/paginateGroupQuery.graphql.ts
  app/packages/relay/src/queries/__generated__/pinnedSampleQuery.graphql.ts
  app/packages/relay/src/queries/config.ts
  app/packages/relay/src/queries/index.ts
  app/packages/relay/src/queries/paginateGroup.ts
  app/packages/relay/src/queries/pinnedSample.ts
  app/packages/state/src/hooks/useStateUpdate.ts
  app/packages/state/src/recoil/atoms.ts
  app/packages/state/src/recoil/color.ts
  app/packages/state/src/recoil/config.ts
  app/packages/state/src/recoil/groups.ts
  app/packages/state/src/recoil/index.ts
  app/packages/state/src/recoil/selectors.ts
  app/packages/utilities/src/color.ts
Labels: cleaning

#2303 Add a filter that removes the mediaField item that does not exists in the selected fields
  app/packages/core/src/components/Actions/Options.tsx
  app/packages/state/src/recoil/selectors.ts
Labels: bug

#2311 Fixing #2292
  fiftyone/core/collections.py
Labels: bug

#2338 Resolved App React Spring error
  app/packages/core/src/components/ViewBar/ViewStage/ViewStage.tsx
Labels: bug, app

#2288 Patch v0.16.6 compatibility
  app/packages/core/src/__generated__/DatasetQuery.graphql.ts
  app/packages/relay/src/mutations/__generated__/setViewMutation.graphql.ts
  app/schema.graphql
  fiftyone/core/odm/dataset.py
  fiftyone/server/metadata.py
  fiftyone/server/query.py
Labels: bug

#2189 Migrating runs/views to separate collections
  fiftyone/constants.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/odm/runs.py
  fiftyone/core/odm/views.py
  fiftyone/core/runs.py
  fiftyone/migrations/revisions/v0_19_0.py
  fiftyone/utils/data/importers.py
  tests/unittests/dataset_tests.py
Labels: enhancement

#2019 Adding dataset URL names and descriptions
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/view.py
  fiftyone/migrations/revisions/v0_19_0.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  tests/unittests/dataset_tests.py
Labels: feature
