Repository voxel51/fiftyone, pull requests merged in 2022-03, with the labels that each got.

#1625 Add argument to link issue tracker to CVAT tasks
  docs/source/integrations/cvat.rst
  fiftyone/utils/cvat.py
Labels: feature, annotation

#1618 Storing database version in the db
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
  fiftyone/migrations/runner.py
Labels: enhancement

#1617 Docs updates
  docs/source/_includes/substitutions.rst
  docs/source/integrations/activitynet.rst
  docs/source/integrations/cvat.rst
  docs/source/integrations/labelbox.rst
  docs/source/user_guide/annotation.rst
  docs/source/user_guide/config.rst
  docs/source/user_guide/evaluation.rst
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
Labels: documentation

#1616 Adding a keep_fields() method
  docs/source/user_guide/using_views.rst
  fiftyone/core/clips.py
  fiftyone/core/dataset.py
  fiftyone/core/patches.py
  fiftyone/core/video.py
  fiftyone/core/view.py
  tests/unittests/patches_tests.py
  tests/unittests/video_tests.py
  tests/unittests/view_tests.py
Labels: enhancement

#1615 Drop collections when deleting datasets
  fiftyone/core/dataset.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
  fiftyone/migrations/revisions/admin/v0_15_0.py
  fiftyone/migrations/runner.py
  setup.py
Labels: enhancement

#1614 Adding interactive lines plots
  docs/source/images/plots/detection-evaluation-patches.gif
  docs/source/images/plots/lines.gif
  docs/source/user_guide/evaluation.rst
  docs/source/user_guide/plots.rst
  fiftyone/__public__.py
  fiftyone/core/expressions.py
  fiftyone/core/plots/__init__.py
  fiftyone/core/plots/base.py
  fiftyone/core/plots/manager.py
  fiftyone/core/plots/matplotlib.py
  fiftyone/core/plots/plotly.py
  fiftyone/core/plots/views.py
  fiftyone/core/stages.py
Labels: feature

#1612 TF records and conversion utility improvements
  docs/source/cli/index.rst
  docs/source/recipes/convert_datasets.ipynb
  fiftyone/core/cli.py
  fiftyone/core/collections.py
  fiftyone/utils/data/converters.py
  fiftyone/utils/tf.py
  tests/unittests/import_export_tests.py
Labels: enhancement

#1627 Embedded document schema updates
  docs/source/user_guide/config.rst
  fiftyone/constants.py
  fiftyone/core/clips.py
  fiftyone/core/collections.py
  fiftyone/core/config.py
  fiftyone/core/document.py
  fiftyone/core/fields.py
  fiftyone/core/frame.py
  fiftyone/core/labels.py
  fiftyone/core/odm/database.py
  fiftyone/core/odm/document.py
  fiftyone/core/odm/embedded_document.py
  fiftyone/core/patches.py
  fiftyone/core/runs.py
  fiftyone/core/stages.py
  fiftyone/core/video.py
  fiftyone/migrations/runner.py
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
  fiftyone/utils/eval/activitynet.py
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/openimages.py
  tests/unittests/video_tests.py
Labels: enhancement

#1632 in TFExampleGenerator, remove alpha channel if force_rgb=True
  fiftyone/utils/tf.py
Labels: enhancement

#1640 Removing deprecated skip_unlabeled parameter from docs
  docs/source/recipes/custom_importer.ipynb
  docs/source/user_guide/dataset_creation/datasets.rst
Labels: documentation

#1641 Add Creating Views recipe
  docs/source/_static/images/recipes/creating_views.png
  docs/source/recipes/creating_views.ipynb
  docs/source/recipes/index.rst
  docs/source/recipes/merge_datasets.ipynb
Labels: documentation

#1630 ViewExpression slice updates
  fiftyone/core/aggregations.py
  fiftyone/core/expressions.py
  tests/unittests/view_tests.py
Labels: bug, enhancement

#1646 Add `ulimit` and `libssl` troubleshooting notes
  .github/ISSUE_TEMPLATE/bug_report_template.md
  docs/source/getting_started/troubleshooting.rst
Labels: documentation

#1644 Frame expressions fix
  fiftyone/core/aggregations.py
  fiftyone/core/expressions.py
  tests/unittests/aggregation_tests.py
Labels: bug

#1655 Disallow video-level annotation
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
  fiftyone/utils/labelbox.py
Labels: annotation

#1647 Resolve bug when annotating views with mapped labels
  fiftyone/utils/annotations.py
  tests/intensive/cvat_tests.py
Labels: bug, annotation

#1650 Adding a delete_frames() method
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/stages.py
  tests/unittests/dataset_tests.py
Labels: enhancement

#1642 Add destination field argument when loading annotations
  docs/source/integrations/cvat.rst
  docs/source/integrations/labelbox.rst
  docs/source/user_guide/annotation.rst
  fiftyone/core/collections.py
  fiftyone/utils/annotations.py
  tests/intensive/cvat_tests.py
Labels: feature, annotation

#1652 Update Jinja2 requirement
  requirements/common.txt
  requirements/docs.txt
  setup.py
Labels: bug, setup, core

#1638 Support CVATv2 servers
  docs/source/integrations/cvat.rst
  docs/source/integrations/labelbox.rst
  docs/source/user_guide/annotation.rst
  fiftyone/core/collections.py
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
  fiftyone/utils/labelbox.py
  tests/intensive/cvat_tests.py
Labels: bug, enhancement, testing, annotation

#1609 Add importers for OpenLABEL format
  docs/source/user_guide/dataset_creation/datasets.rst
  fiftyone/types/dataset_types.py
  fiftyone/utils/openlabel.py
  tests/misc/selection_tests.py
  tests/unittests/import_export_tests.py
  tests/unittests/utils/__init__.py
  tests/unittests/utils/openlabel.py
Labels: feature

#1656 Release v0.15.0
  .github/workflows/build.yml
  app/package.json
  app/packages/app/package.json
  docs/source/release-notes.rst
  package/desktop/setup.py
  setup.py
Labels: release

#1658 Patch v0.15.0 video playback
  app/package.json
  app/packages/app/package.json
  app/packages/desktop/package.json
  app/packages/looker/src/worker.ts
  package/desktop/setup.py
  setup.py
Labels: bug, app, release

#1660 Support fortran arrays in the app
  app/packages/looker/src/numpy.ts
  fiftyone/server/json_util.py
Labels: bug, app, server

#1664 Always populate iscrowd field when exporting COCO labels
  fiftyone/utils/coco.py
Labels: enhancement
