Repository voxel51/fiftyone, pull requests merged in 2022-06, with the labels that each got.

#1810 change esc ordering for videos
  app/packages/looker/src/elements/common/actions.ts
Labels: feature, app, javascript

#1812 OpenLABEL importer updates
  docs/source/user_guide/dataset_creation/datasets.rst
  fiftyone/utils/openlabel.py
  tests/unittests/import_export_tests.py
  tests/unittests/utils/openlabel.py
Labels: enhancement

#1779 Add keyboard shortcut to temporarily hide all labels in the App
  app/packages/app/src/components/Looker.tsx
  app/packages/app/src/recoil/atoms.ts
  app/packages/looker/src/elements/common/actions.ts
  app/packages/looker/src/elements/common/canvas.ts
  app/packages/looker/src/elements/common/controls.module.css
  app/packages/looker/src/elements/common/controls.ts
  app/packages/looker/src/elements/common/looker.ts
  app/packages/looker/src/elements/common/util.ts
  app/packages/looker/src/elements/index.ts
  app/packages/looker/src/elements/util.ts
  app/packages/looker/src/processOverlays.ts
  app/packages/looker/src/state.ts
Labels: feature, app, javascript

#1824 Fixing DB field bug
  fiftyone/core/odm/mixins.py
  tests/unittests/dataset_tests.py
Labels: bug

#1800 add concurrent app+backend run script
  app/README.md
  app/package.json
  app/yarn.lock
Labels: enhancement

#1842 Add utility to convert classifications to detections
  fiftyone/utils/labels.py
Labels: feature, core

#1839 Update how CVAT task and project pages are requested
  fiftyone/utils/cvat.py
Labels: bug, hotfix, annotation

#1838 Fix bug when using zoo models with newest version of Torchvision
  fiftyone/zoo/models/manifest-torch.json
  fiftyone/zoo/models/torch.py
Labels: bug, ml

#1844 Always use fork for multiprocessing on macOS
  fiftyone/core/metadata.py
  fiftyone/core/utils.py
  fiftyone/utils/data/base.py
  fiftyone/utils/image.py
Labels: enhancement

#1858 Stop passing classes and default_classes to export and evaluation methods
  docs/source/integrations/coco.rst
  docs/source/integrations/cvat.rst
  docs/source/user_guide/annotation.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_creation/index.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/core/collections.py
  fiftyone/utils/annotations.py
  fiftyone/utils/coco.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/segmentation.py
  fiftyone/utils/labels.py
  fiftyone/utils/tf.py
  fiftyone/utils/yolo.py
  tests/unittests/import_export_tests.py
Labels: enhancement

#1880 Fix JSON view nested values
  app/packages/looker/src/index.ts
Labels: bug, app

#1882 Fix selection and expansion for bad media files
  app/packages/looker/src/elements/common/thumbnail.module.css
  app/packages/looker/src/elements/frame.ts
  app/packages/looker/src/elements/image.ts
  app/packages/looker/src/elements/video.ts
Labels: bug, app

#1879 Serialize views as BSON
  app/packages/app/relay.config.json
  app/packages/app/schema.graphql
  app/packages/app/src/Root/Datasets/Dataset.tsx
  app/packages/app/src/Root/Datasets/__generated__/DatasetQuery.graphql.ts
  app/packages/app/src/mutations/__generated__/setViewMutation.graphql.ts
  app/packages/app/src/mutations/setView.ts
  fiftyone/core/state.py
  fiftyone/server/mutation.py
  fiftyone/server/query.py
  fiftyone/server/scalars.py
Labels: bug, app

#1891 updates `FIFTYONE_DEFAULT_APP_ADDRESS` documentation
  docs/source/environments/index.rst
  docs/source/user_guide/config.rst
Labels: documentation

#1876 Adds the ability to upload and download group ids from CVAT
  docs/source/integrations/cvat.rst
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
  tests/intensive/cvat_tests.py
Labels: feature, annotation

#1877 Remove thumbnail frame classifications
  app/packages/looker/src/elements/common/tags.ts
Labels: bug, app

#1884 eliminate non-XML or non-TXT files from CVAT, KITTI, CVATVideo
  fiftyone/utils/cvat.py
  fiftyone/utils/kitti.py
  fiftyone/utils/voc.py
Labels: enhancement

#1861 Bringing back the current section highlight!
  docs/source/_static/js/custom.js
Labels: bug, documentation

#1845 Adding dataset tags
  docs/source/user_guide/evaluation.rst
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/core/cli.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/view.py
  fiftyone/migrations/revisions/v0_16_3.py
  setup.py
  tests/unittests/dataset_tests.py
Labels: feature

#1892 Big Picture script
  docs/source/_templates/layout.html
Labels: documentation

#1878 Maintain active dataset fields
  app/packages/app/src/Root/Datasets/Dataset.tsx
  app/packages/app/src/utils/hooks.ts
  fiftyone/server/query.py
Labels: bug, app

#1829 Nullable GraphQL API
  app/packages/app/schema.graphql
  app/packages/app/src/Root/Datasets/__generated__/DatasetQuery.graphql.ts
  app/packages/app/src/mutations/__generated__/setViewMutation.graphql.ts
  fiftyone/server/query.py
Labels: bug, app, server

#1875 App issues
  app/packages/app/src/Root/Root.tsx
  app/packages/app/src/Root/__generated__/RootQuery.graphql.ts
  app/packages/components/src/components/Results/Results.module.css
  app/packages/components/src/components/Results/Results.tsx
  app/packages/components/src/components/Selector/Selector.module.css
  app/packages/components/src/components/Selector/Selector.tsx
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/elements/frame.ts
  app/packages/looker/src/elements/video.ts
  app/packages/looker/src/worker.ts
  fiftyone/core/session/client.py
  fiftyone/server/constants.py
  fiftyone/server/paginator.py
  fiftyone/server/query.py
  fiftyone/server/view.py
Labels: bug, app

#1817 App distributions fixes
  app/packages/app/src/components/Distributions.tsx
  app/packages/app/src/utils/generic.tsx
  fiftyone/server/routes/distributions.py
Labels: bug, app

#1896 Releases v0.16.3 and v0.16.4
  docs/source/release-notes.rst
  fiftyone/server/query.py
  package/desktop/setup.py
  setup.py
Labels: release

#1907 Release v0.16.5
  app/packages/app/schema.graphql
  app/packages/app/src/Network.tsx
  app/packages/app/src/Root/Datasets/Dataset.tsx
  app/packages/app/src/Root/Datasets/__generated__/DatasetQuery.graphql.ts
  app/packages/app/src/Root/Datasets/transformDataset.ts
  app/packages/components/src/components/Results/Results.module.css
  app/packages/components/src/components/Results/Results.tsx
  app/packages/components/src/components/Route/Route.tsx
  app/packages/components/src/components/Selector/Selector.module.css
  app/packages/components/src/routing/matchPath.ts
  docs/source/release-notes.rst
  fiftyone/server/paginator.py
  fiftyone/server/query.py
  package/desktop/setup.py
  setup.py
Labels: release

#1911 Adding support for serializing Aggregations
  fiftyone/__public__.py
  fiftyone/core/aggregations.py
  fiftyone/core/stages.py
  tests/unittests/aggregation_tests.py
Labels: enhancement
