Repository voxel51/fiftyone, pull requests merged in 2022-01, with the labels that each got.

#1469 Partial work on #1462
  fiftyone/core/odm/document.py
  fiftyone/core/odm/mixins.py
Labels: bug

#1498 Fixing bug in computing patch embeddings defined by polylines
  fiftyone/utils/torch.py
  tests/misc/torch_tests.py
Labels: bug

#1489 Adding TF2 models to zoo
  fiftyone/zoo/models/manifest-tf.json
Labels: enhancement

#1508 Fixing expressions containing near-epoch dates
  fiftyone/core/expressions.py
  fiftyone/core/utils.py
  tests/unittests/view_tests.py
Labels: bug

#1505 Proper handling of ID fields in set_values(..., key_field="id")
  fiftyone/core/collections.py
Labels: bug

#1510 Import existing CVAT datasets into FiftyOne (#2)
  docs/source/integrations/cvat.rst
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
Labels: feature

#1513 Adding support for downloading media from existing CVAT tasks/projects
  docs/source/integrations/cvat.rst
  fiftyone/utils/cvat.py
  fiftyone/utils/video.py
Labels: feature, annotation

#1506 Adding support for setting frame-level fields by frame number in set_values()
  fiftyone/core/collections.py
  tests/unittests/view_tests.py
Labels: enhancement

#1523 Gracefully handle empty segmentation data in COCO format
  fiftyone/utils/coco.py
Labels: bug

#1532 Defaulting to zero workers on Windows
  fiftyone/core/metadata.py
  fiftyone/utils/aws.py
  fiftyone/utils/coco.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/base.py
  fiftyone/utils/image.py
  fiftyone/utils/torch.py
Labels: enhancement

#1518 Docs updates
  docs/source/_templates/layout.html
Labels: documentation

#1534 Update CVATVideoDataset export argument documentation
  docs/source/user_guide/export_datasets.rst
Labels: documentation

#1525 Adding support for defining custom EmbeddedDocument classes
  docs/source/user_guide/config.rst
  fiftyone/core/config.py
  fiftyone/core/labels.py
  fiftyone/core/metadata.py
  fiftyone/core/odm/document.py
Labels: feature

#1526 Adding support for boolean view indexing
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
Labels: enhancement

#1533 Release v0.14.3
  .github/workflows/build-docs.yml
  docs/source/release-notes.rst
  package/db/setup.py
  setup.py
Labels: release

#1481 Update visual similarity stage in-place when possible in App workflows
  fiftyone/core/view.py
Labels: enhancement

#1542 Docker v2
  .dockerignore
  Dockerfile
  README.md
  docs/source/environments/index.rst
  docs/source/user_guide/config.rst
Labels: feature

#1549 optionally treat missing labels as empty detections when adding yolo labels
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_creation/index.rst
  fiftyone/utils/yolo.py
  tests/unittests/import_export_tests.py
Labels: enhancement

#1538 I/O cleanup
  docs/source/cli/index.rst
  fiftyone/core/cli.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/media.py
  fiftyone/core/odm/document.py
  fiftyone/core/odm/sample.py
  fiftyone/core/sample.py
  fiftyone/core/utils.py
  fiftyone/core/video.py
  fiftyone/core/view.py
  fiftyone/utils/bdd.py
  fiftyone/utils/coco.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/base.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/data/ingestors.py
  fiftyone/utils/data/parsers.py
  fiftyone/utils/dicom.py
  fiftyone/utils/geojson.py
  fiftyone/utils/geotiff.py
  fiftyone/utils/image.py
  fiftyone/utils/kitti.py
  fiftyone/utils/tf.py
  fiftyone/utils/video.py
  fiftyone/utils/voc.py
  fiftyone/utils/yolo.py
  requirements/common.txt
  setup.py
  tests/unittests/import_export_tests.py
Labels: enhancement

#1547 Resolve bug when annotating existing fields with multiple label types
  fiftyone/utils/annotations.py
Labels: bug, annotation

#1555 Label conversion utility improvements
  fiftyone/core/labels.py
  fiftyone/utils/coco.py
  fiftyone/utils/eta.py
  fiftyone/utils/labels.py
  fiftyone/utils/patches.py
Labels: enhancement

#1564 Update Dockerfile example
  Dockerfile
Labels: documentation

#1556 Adding support for saving plots as images
  docs/source/images/plots/save-embeddings-matplotlib.png
  docs/source/images/plots/save-embeddings.png
  docs/source/images/plots/save-histogram.jpg
  docs/source/user_guide/plots.rst
  fiftyone/core/plots/base.py
  fiftyone/core/plots/matplotlib.py
  fiftyone/core/plots/plotly.py
Labels: feature

#1566 Handle empty Keypoint in App
  app/packages/looker/src/overlays/keypoint.ts
Labels: bug, app

#1569 Adds tags/classifications when importing and exporting CVATImageDatasets
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/resources/cvat_image_annotation_template.xml
  fiftyone/utils/cvat.py
Labels: feature
