Repository voxel51/fiftyone, pull requests merged in 2022-05, with the labels that each got.

#1721 Fixing #1716
  docs/source/user_guide/dataset_creation/datasets.rst
  fiftyone/utils/yolo.py
Labels: bug

#1746 Optimizing non-persistent dataset deletion
  fiftyone/core/dataset.py
Labels: enhancement

#1736 Avoid non-critical errors in startup services
  fiftyone/core/dataset.py
  fiftyone/core/odm/database.py
Labels: bug, enhancement

#1747 Delete non-persistent datasets at shutdown
  fiftyone/__init__.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
Labels: bug, enhancement

#1749 Cloning/merging bug fixes
  fiftyone/core/dataset.py
  fiftyone/core/odm/mixins.py
  tests/unittests/dataset_tests.py
Labels: bug

#1728 Fixing GeoTIFF list bug
  fiftyone/utils/geotiff.py
Labels: bug

#1725 Updating the dev guide
  CONTRIBUTING.md
  STYLE_GUIDE.md
  app/README.md
  docs/README.md
Labels: documentation

#1773 Allow RunResults to contain BSON
  fiftyone/core/runs.py
Labels: hotfix

#1751 Release v0.16.0
  .github/workflows/build-docs.yml
  app/packages/app/src/routes.ts
  docs/source/release-notes.rst
  fiftyone/server/query.py
  setup.py
  tests/isolated/service_tests.py
Labels: release

#1796 Release v0.16.1
  app/packages/app/src/Root/Datasets/Dataset.tsx
  app/packages/app/src/Root/Root.tsx
  app/packages/app/src/components/Flashlight.tsx
  app/packages/app/src/components/ViewBar/ViewBar.tsx
  app/packages/app/src/recoil/aggregations.ts
  app/packages/components/src/components/Header/Header.tsx
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/index.ts
  app/packages/looker/src/worker.ts
  docs/source/release-notes.rst
  fiftyone/core/json.py
  fiftyone/migrations/revisions/v0_16_1.py
  fiftyone/server/json_util.py
  fiftyone/server/query.py
  fiftyone/server/routes/aggregations.py
  fiftyone/server/routes/pin.py
  fiftyone/server/routes/sort.py
  package/desktop/setup.py
  setup.py
Labels: release

#1776 Fix initial label renders
  app/packages/app/src/Root/Root.tsx
  app/packages/app/src/components/Flashlight.tsx
  app/packages/components/src/components/Header/Header.tsx
Labels: bug, app

#1785 v0.16.1 Revision
  fiftyone/migrations/revisions/v0_16_1.py
  setup.py
Labels: bug, app

#1793 adding filename exception logging for failed xml parsing
  fiftyone/core/utils.py
Labels: enhancement

#1805 Fix App page views
  app/packages/app/src/Root/Root.tsx
Labels: bug
