Repository voxel51/fiftyone, pull requests merged in 2022-08, with the labels that each got.

#1980 Fix session views
  app/packages/app/src/Root/Datasets/Dataset.tsx
Labels: bug, app

#1973 CVAT Annotate attribute documentation update
  docs/source/integrations/cvat.rst
Labels: documentation, annotation

#1953 #1951 and #1952
  docs/source/integrations/coco.rst
  docs/source/integrations/labelbox.rst
  fiftyone/utils/yolo.py
Labels: bug, documentation

#1967 Fixing #1966
  fiftyone/core/plots/base.py
  fiftyone/core/plots/matplotlib.py
  fiftyone/core/plots/plotly.py
Labels: bug

#1925 Adding weighted_sample() and balanced_sample() utils
  docs/source/integrations/lightning_flash.rst
  docs/source/release-notes.rst
  fiftyone/utils/random.py
  fiftyone/utils/splits.py
  tests/intensive/lightning_flash_tests.py
Labels: feature

#1993 Passing attributes through during label coercions
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/parsers.py
  fiftyone/utils/patches.py
Labels: enhancement

#1997 Upgrading AnnotationAPI reuse to interface level
  docs/source/integrations/cvat.rst
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
  fiftyone/utils/labelbox.py
Labels: enhancement

#2003 v0.17.0rc0
  .github/workflows/build.yml
  app/packages/app/src/Root/Datasets/Dataset.tsx
  app/packages/app/src/Root/Datasets/__generated__/DatasetQuery.graphql.ts
  app/packages/app/src/components/Modal/Bars.tsx
  app/packages/app/src/components/Modal/Modal.tsx
  app/packages/app/src/components/Sidebar/Entries/PathValueEntry.tsx
  app/packages/looker/src/elements/common/panel.module.css
  app/packages/looker/src/elements/common/tags.ts
  app/packages/map/package.json
  app/packages/map/src/Map.tsx
  app/packages/relay/src/mutations/__generated__/setViewMutation.graphql.ts
  app/packages/relay/src/mutations/setView.ts
  app/packages/state/src/recoil/atoms.ts
  app/packages/state/src/recoil/groups.ts
  app/packages/state/src/recoil/options.ts
  app/yarn.lock
Labels: release

#1999 Switching to list-based storage of saved views
  fiftyone/__public__.py
  fiftyone/core/dataset.py
  fiftyone/core/fields.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/odm/views.py
  fiftyone/core/utils.py
  fiftyone/migrations/revisions/v0_16_6.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  tests/unittests/dataset_tests.py
  tests/unittests/utils_tests.py
Labels: enhancement

#1981 Adding plotly v5 support!
  docs/source/user_guide/plots.rst
  fiftyone/core/plots/plotly.py
  requirements/common.txt
  requirements/extras.txt
  setup.py
Labels: bug, enhancement

#1944 CVAT optimizations
  docs/source/integrations/cvat.rst
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
  fiftyone/utils/labelbox.py
  tests/intensive/cvat_tests.py
Labels: enhancement, annotation

#1940 Extending stats() method to sample collections
  docs/source/user_guide/using_datasets.rst
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
Labels: feature

#1927 Adding new_ids=True option to Dataset.add_collection()
  fiftyone/core/dataset.py
  tests/unittests/dataset_tests.py
  tests/unittests/video_tests.py
Labels: enhancement

#1922 Bug fixes
  docs/source/user_guide/plots.rst
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/core/clips.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/fields.py
  fiftyone/core/frame.py
  fiftyone/core/labels.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/odm/document.py
  fiftyone/core/odm/frame.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/odm/utils.py
  fiftyone/core/patches.py
  fiftyone/core/runs.py
  fiftyone/core/sample.py
  fiftyone/core/singletons.py
  fiftyone/core/stages.py
  fiftyone/core/video.py
  fiftyone/core/view.py
  fiftyone/utils/coco.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/converters.py
  fiftyone/utils/data/exporters.py
  tests/unittests/dataset_tests.py
  tests/unittests/decorators.py
  tests/unittests/evaluation_tests.py
  tests/unittests/label_tests.py
  tests/unittests/patches_tests.py
  tests/unittests/sample_tests.py
  tests/unittests/video_tests.py
  tests/unittests/view_tests.py
Labels: bug

#1848 Label studio integration
  docs/source/_static/images/integrations/labelstudio.png
  docs/source/integrations/index.rst
  docs/source/integrations/labelstudio.rst
  fiftyone/core/config.py
  fiftyone/utils/annotations.py
  fiftyone/utils/labelstudio.py
  tests/intensive/labelstudio_tests.py
Labels: feature, annotation

#2007 Adding support for writing transformed images/videos to new location/field
  docs/source/cli/index.rst
  fiftyone/core/cli.py
  fiftyone/core/utils.py
  fiftyone/utils/image.py
  fiftyone/utils/video.py
Labels: enhancement

#2006 Label studio updates
  docs/source/integrations/labelstudio.rst
  fiftyone/utils/annotations.py
  fiftyone/utils/cvat.py
  fiftyone/utils/labelbox.py
  fiftyone/utils/labelstudio.py
  tests/intensive/labelstudio_tests.py
Labels: enhancement, annotation

#2012 Save context tweaks
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/__public__.py
  fiftyone/core/clips.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/frame.py
  fiftyone/core/odm/document.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/patches.py
  fiftyone/core/sample.py
  fiftyone/core/singletons.py
  fiftyone/core/video.py
  fiftyone/core/view.py
  tests/unittests/dataset_tests.py
  tests/unittests/video_tests.py
  tests/unittests/view_tests.py
Labels: enhancement

#2011 Adding ipywidgets<8 requirement
  docs/source/user_guide/plots.rst
  fiftyone/core/plots/plotly.py
Labels: documentation

#2009 Package-wide logging config
  docs/source/user_guide/config.rst
  fiftyone/__init__.py
  fiftyone/__public__.py
  fiftyone/core/config.py
  fiftyone/core/logging.py
Labels: enhancement

#1727 Adding a dataset save context
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/__public__.py
  fiftyone/core/clips.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/frame.py
  fiftyone/core/odm/document.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/patches.py
  fiftyone/core/sample.py
  fiftyone/core/singletons.py
  fiftyone/core/video.py
  fiftyone/core/view.py
  tests/unittests/dataset_tests.py
  tests/unittests/video_tests.py
  tests/unittests/view_tests.py
Labels: enhancement

#2023 Fix documentation builds
  .github/workflows/build-docs.yml
Labels: bug, documentation

#2008 Release v0.16.6
  .github/workflows/build-docs.yml
  docs/source/getting_started/install.rst
  docs/source/getting_started/troubleshooting.rst
  docs/source/release-notes.rst
  docs/source/user_guide/config.rst
  fiftyone/core/dataset.py
  fiftyone/migrations/runner.py
  fiftyone/utils/labelstudio.py
  install.bash
  package/desktop/setup.py
  requirements/extras.txt
  setup.py
Labels: release

#2031 Fix README slack links
  README.md
Labels: bug, documentation

#2030 Don't include runs when merging collections
  fiftyone/core/dataset.py
Labels: cleaning

#2028 Adding option to export per-sample JSON in FiftyOneDataset format
  docs/source/user_guide/export_datasets.rst
  fiftyone/core/dataset.py
  fiftyone/core/odm/database.py
  fiftyone/core/utils.py
  fiftyone/core/video.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  tests/unittests/import_export_tests.py
Labels: enhancement

#2029 Fixing match_frames() bug
  fiftyone/core/stages.py
  tests/unittests/view_tests.py
Labels: bug

#2041 Remove old session module
  fiftyone/core/session.py
Labels: bug, core

#2035 Adding grouped dataset importer/exporter interfaces
  docs/source/_includes/substitutions.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/export_datasets.rst
  docs/source/user_guide/groups.rst
  fiftyone/core/dataset.py
  fiftyone/types/dataset_types.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  tests/unittests/group_tests.py
Labels: feature

#2046 Groups cleaning and video fix
  app/packages/looker/src/constants.ts
  app/packages/looker/src/elements/common/index.ts
  app/packages/looker/src/elements/common/json.module.css
  app/packages/looker/src/elements/common/json.ts
  app/packages/looker/src/elements/index.ts
  app/packages/looker/src/elements/video.ts
  app/packages/looker/src/index.ts
Labels: cleaning, app

#2026 Fix group session updates
  app/packages/app/src/Root/Datasets/Dataset.tsx
  app/packages/state/src/hooks/useStateUpdate.ts
Labels: bug
