Repository voxel51/fiftyone, pull requests merged in 2022-10, with the labels that each got.

#2140 Fixing select_by() ID bug
  fiftyone/core/stages.py
  tests/unittests/view_tests.py
Labels: bug

#2141 Automatic Docker address + moving instructions to the docs
  Dockerfile
  README.md
  docs/source/environments/index.rst
  docs/source/user_guide/app.rst
  fiftyone/core/session/session.py
  fiftyone/core/utils.py
Labels: documentation

#1137 Adding schema() aggregation
  fiftyone/__public__.py
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  tests/unittests/aggregation_tests.py
Labels: feature

#2148 add note to plugin docs
  app/packages/plugins/README.md
Labels: plugins

#2150 Fix view expression sort documentation
  docs/source/user_guide/using_views.rst
Labels: documentation

#2159 only warn when plugin re-registered
  app/packages/plugins/src/index.ts
Labels: plugins

#2179 DB config cleanup
  docs/source/user_guide/config.rst
  fiftyone/migrations/revisions/admin/v0_7_1.py
Labels: documentation, cleaning

#2182 Fix relay compilation and ensure future compilations in builds
  .prettierignore
  .prettierrc
  app/packages/aggregations/package.json
  app/packages/app/package.json
  app/packages/components/package.json
  app/packages/core/package.json
  app/packages/core/src/Dataset.ts
  app/packages/core/src/Root/Datasets/Dataset.tsx
  app/packages/core/src/Root/__generated__/DatasetsPaginationQuery.graphql.ts
  app/packages/core/src/Root/__generated__/RootConfig_query.graphql.ts
  app/packages/core/src/Root/__generated__/RootDatasets_query.graphql.ts
  app/packages/core/src/Root/__generated__/RootGA_query.graphql.ts
  app/packages/core/src/Root/__generated__/RootNav_query.graphql.ts
  app/packages/core/src/Root/__generated__/RootQuery.graphql.ts
  app/packages/core/src/__generated__/DatasetQuery.graphql.ts
  app/packages/core/src/components/Teams/__generated__/TeamsStoreTeamsSubmissionMutation.graphql.ts
  app/packages/core/src/index.ts
  app/packages/dataset/package.json
  app/packages/desktop/package.json
  app/packages/flashlight/package.json
  app/packages/looker/package.json
  app/packages/plugins/package.json
  app/packages/prettier-config/index.js
  app/packages/prettier-config/package.json
  app/packages/relay/package.json
  app/packages/relay/src/mutations/__generated__/setGroupSliceMutation.graphql.ts
  app/packages/relay/src/mutations/__generated__/setViewMutation.graphql.ts
  app/packages/relay/src/queries/__generated__/mainSampleQuery.graphql.ts
  app/packages/relay/src/queries/__generated__/paginateGroupPageQuery.graphql.ts
  app/packages/relay/src/queries/__generated__/paginateGroupPinnedSample_query.graphql.ts
  app/packages/relay/src/queries/__generated__/paginateGroupQuery.graphql.ts
  app/packages/relay/src/queries/__generated__/paginateGroup_query.graphql.ts
  app/packages/state/package.json
  app/packages/utilities/package.json
  app/yarn.lock
Labels: bug, app

#2181 add support for readOnly mode
  app/packages/core/src/components/Actions/ActionsRow.tsx
  app/packages/dataset/src/Dataset.tsx
  app/packages/dataset/src/index.tsx
  app/packages/state/src/recoil/atoms.ts
Labels: app

#2144 Handling grouped collections when sampling frames
  fiftyone/core/clips.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/frame.py
  fiftyone/core/patches.py
  fiftyone/core/video.py
  fiftyone/core/view.py
Labels: bug

#2135 Refactor merge_samples() to safely cleanup in case of errors
  fiftyone/core/clips.py
  fiftyone/core/dataset.py
  fiftyone/utils/beam.py
  fiftyone/utils/data/importers.py
Labels: bug

#2200 Fixes mutation of label tags from patches views in the App
  fiftyone/core/view.py
Labels: bug

#2201 Support cuda devices for CLIP zoo model
  fiftyone/utils/clip/zoo.py
Labels: bug, ml

#2115 App bug reports
  app/packages/app/src/index.tsx
  app/packages/components/src/components/ErrorBoundary/ErrorBoundary.tsx
  app/packages/core/src/components/Actions/Tagger.tsx
  app/packages/core/src/utils/generic.tsx
  app/packages/state/src/hooks/useSelectFlashlightSample.ts
  app/packages/utilities/src/index.ts
  fiftyone/core/session/session.py
  fiftyone/core/state.py
Labels: bug, app

#2207 Transparent looker background
  app/packages/looker/src/elements/common/looker.module.css
Labels: bug, design

#2203 Optimizing tagging implementations
  fiftyone/core/collections.py
  fiftyone/core/stages.py
  fiftyone/server/utils.py
  tests/unittests/view_tests.py
Labels: enhancement
