Repository voxel51/fiftyone, pull requests merged in 2022-04, with the labels that each got.

#1666 Embedded document schema updates (take 2)
  docs/source/integrations/coco.rst
  docs/source/user_guide/basics.rst
  docs/source/user_guide/evaluation.rst
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/core/dataset.py
  fiftyone/migrations/revisions/v0_16_0.py
  setup.py
Labels: enhancement

#1667 Adding database admin config setting
  docs/source/cli/index.rst
  docs/source/getting_started/install.rst
  docs/source/user_guide/config.rst
  fiftyone/core/cli.py
  fiftyone/core/config.py
  fiftyone/migrations/revisions/v0_16_0.py
  fiftyone/migrations/runner.py
Labels: enhancement

#1663 Add FIW to the dataset zoo
  docs/source/images/dataset_zoo/fiw.png
  docs/source/user_guide/dataset_zoo/datasets.rst
  fiftyone/types/dataset_types.py
  fiftyone/utils/fiw.py
  fiftyone/zoo/datasets/base.py
Labels: dataset zoo

#1674 Fix CVAT CSRF bug
  fiftyone/utils/cvat.py
Labels: bug, annotation

#1671 Update PyTorch Lightning Flash integration
  docs/source/integrations/lightning_flash.rst
  fiftyone/core/collections.py
  fiftyone/core/models.py
  fiftyone/utils/flash.py
  tests/intensive/lightning_flash_tests.py
Labels: bug, documentation

#1670 Fix Desktop
  app/packages/app/src/shared/connection.ts
  app/packages/desktop/tsconfig.json
Labels: bug, desktop app

#1677 Patch Desktop App
  package/desktop/setup.py
Labels: bug, app, release, desktop app

#1679 Consistent node version
  app/README.md
  install.bash
Labels: documentation, setup

#1686 Export tag attributes for CVATImageDatasets
  fiftyone/resources/cvat_image_annotation_template.xml
  fiftyone/utils/cvat.py
Labels: enhancement, annotation

#1690 Adding filter_keypoints() view stage
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/stages.py
  fiftyone/utils/labels.py
  tests/unittests/view_tests.py
Labels: enhancement

#1684 Fixing #1675
  fiftyone/core/utils.py
  fiftyone/utils/bdd.py
  fiftyone/utils/coco.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/geojson.py
  fiftyone/utils/kitti.py
  fiftyone/utils/openlabel.py
  fiftyone/utils/voc.py
  fiftyone/utils/yolo.py
Labels: bug

#1601 Keypoint updates
  app/packages/app/src/components/Actions/Options.tsx
  app/packages/app/src/components/FieldsSidebar.tsx
  app/packages/app/src/components/Filters/CategoricalFilter.tsx
  app/packages/app/src/components/Filters/LabelFieldFilter.tsx
  app/packages/app/src/components/Filters/LabelFieldFilters.state.tsx
  app/packages/app/src/components/Filters/NumericFieldFilter.state.ts
  app/packages/app/src/components/Filters/StringFieldFilter.state.ts
  app/packages/app/src/components/Filters/atoms.ts
  app/packages/app/src/components/Flashlight.tsx
  app/packages/app/src/components/Looker.tsx
  app/packages/app/src/recoil/atoms.ts
  app/packages/app/src/recoil/selectors.ts
  app/packages/looker/src/constants.ts
  app/packages/looker/src/overlays/base.ts
  app/packages/looker/src/overlays/keypoint.ts
  app/packages/looker/src/state.ts
  app/packages/looker/src/util.ts
  docs/source/_includes/substitutions.rst
  docs/source/user_guide/config.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/config.py
  fiftyone/core/dataset.py
  fiftyone/core/fields.py
  fiftyone/core/labels.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
  fiftyone/migrations/revisions/v0_15_1.py
  fiftyone/server/extended_view.py
  fiftyone/server/main.py
  fiftyone/utils/annotations.py
  fiftyone/utils/coco.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/eta.py
  fiftyone/utils/torch.py
  fiftyone/zoo/datasets/tf.py
  fiftyone/zoo/datasets/torch.py
  fiftyone/zoo/models/manifest-torch.json
  fiftyone/zoo/models/torch.py
  setup.py
  tests/unittests/dataset_tests.py
  tests/unittests/view_tests.py
Labels: enhancement

#1692 Database name, admin, and type
  docs/source/cli/index.rst
  docs/source/getting_started/install.rst
  docs/source/user_guide/config.rst
  fiftyone/constants.py
  fiftyone/core/cli.py
  fiftyone/core/config.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
  fiftyone/migrations/revisions/admin/v0_15_1.py
  fiftyone/migrations/runner.py
  setup.py
Labels: feature

#1699 Non-persistent dataset cleanup tweak
  fiftyone/__init__.py
  fiftyone/__public__.py
  fiftyone/core/odm/database.py
Labels: enhancement

#1697 Automatically delete non-persistent datasets when using custom database URIs
  fiftyone/__init__.py
  fiftyone/__public__.py
  fiftyone/constants.py
  fiftyone/core/odm/database.py
  fiftyone/core/service.py
  fiftyone/service/main.py
Labels: feature

#1702 Patch Desktop App path on Windows
  fiftyone/core/service.py
Labels: bug, release, desktop app

#1703 Fix pre-commit
  .pre-commit-config.yaml
Labels: bug, standard

#1662 Adding a concat() view stage
  docs/source/user_guide/using_views.rst
  fiftyone/__public__.py
  fiftyone/core/clips.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/patches.py
  fiftyone/core/stages.py
  fiftyone/core/video.py
  fiftyone/core/view.py
Labels: feature

#1705 typo fix
  docs/source/recipes/creating_views.ipynb
Labels: bug

#1707 Release v0.15.1
  app/packages/app/src/components/Actions/Options.tsx
  app/packages/app/src/components/FieldsSidebar.tsx
  app/packages/app/src/components/Filters/LabelFieldFilters.state.tsx
  app/packages/app/src/recoil/selectors.ts
  app/packages/looker/src/overlays/base.ts
  app/packages/looker/src/overlays/keypoint.ts
  app/packages/looker/src/state.ts
  docs/source/release-notes.rst
  docs/source/user_guide/config.rst
  fiftyone/__init__.py
  fiftyone/__public__.py
  fiftyone/core/config.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
  package/desktop/setup.py
  setup.py
Labels: release

#1710 Adding Python 3.6 back to pre-commit hooks
  .pre-commit-config.yaml
  requirements/dev.txt
Labels: setup
