Repository voxel51/fiftyone, pull requests merged in 2023-05, with the labels that each got.

#2916 Fixing Scale docs links + unlabeled annotation tasks
  fiftyone/utils/scale.py
Labels: bug

#2928 Adding keypoint evaluation
  docs/source/user_guide/evaluation.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/core/collections.py
  fiftyone/core/patches.py
  fiftyone/core/stages.py
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/openimages.py
  fiftyone/utils/iou.py
Labels: feature, evaluation

#2956 Allow config files to not exist
  fiftyone/core/cli.py
  fiftyone/core/config.py
Labels: enhancement

#2475 Dynamic groups
  app/.eslintrc.js
  app/packages/components/src/components/Loading/LoadingDots.tsx
  app/packages/components/src/components/Selector/Selector.module.css
  app/packages/components/src/components/TabOption/TabOption.tsx
  app/packages/core/src/components/Actions/ActionsRow.tsx
  app/packages/core/src/components/Actions/DynamicGroupAction.tsx
  app/packages/core/src/components/Actions/GroupMediaVisibilityContainer.tsx
  app/packages/core/src/components/Actions/Tagger.tsx
  app/packages/core/src/components/Group/index.ts
  app/packages/core/src/components/GroupSliceSelector.tsx
  app/packages/core/src/components/ImageContainerHeader.tsx
  app/packages/core/src/components/Modal/Group.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/NestedGroup/GroupElementsLinkBar.module.css
  app/packages/core/src/components/Modal/Group/DynamicGroup/NestedGroup/GroupElementsLinkBar.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/NestedGroup/PaginationComponentWithTooltip.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/NestedGroup/index.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/UnorderedDynamicGroup.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/carousel/DynamicGroupCarousel.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/carousel/DynamicGroupsFlashlightWrapper.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/index.tsx
  app/packages/core/src/components/Modal/Group/Group.module.css
  app/packages/core/src/components/Modal/Group/GroupCarousel.tsx
  app/packages/core/src/components/Modal/Group/GroupContextProvider.tsx
  app/packages/core/src/components/Modal/Group/GroupImageVideoSample.tsx
  app/packages/core/src/components/Modal/Group/GroupSample3d.tsx
  app/packages/core/src/components/Modal/Group/GroupSampleWrapper.tsx
  app/packages/core/src/components/Modal/Group/GroupSuspense.tsx
  app/packages/core/src/components/Modal/Group/GroupView.tsx
  app/packages/core/src/components/Modal/Group/index.tsx
  app/packages/core/src/components/Modal/Modal.tsx
  app/packages/flashlight/src/index.ts
  app/packages/looker/src/elements/common/looker.ts
  app/packages/relay/src/queries/__generated__/paginateDynamicGroupSamplesQuery.graphql.ts
  app/packages/relay/src/queries/index.ts
  app/packages/relay/src/queries/paginateDynamicGroupSamples.ts
  app/packages/state/src/hooks/useStateUpdate.ts
  app/packages/state/src/recoil/aggregations.ts
  app/packages/state/src/recoil/atoms.ts
  app/packages/state/src/recoil/groups.ts
  app/packages/state/src/recoil/types.ts
  app/packages/state/src/recoil/utils.ts
  app/packages/state/src/recoil/view.ts
  docs/source/user_guide/groups.rst
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
  fiftyone/server/samples.py
  tests/unittests/group_tests.py
Labels: feature

#2931 Reencode updates
  docs/source/cli/index.rst
  fiftyone/core/cli.py
  fiftyone/utils/image.py
  fiftyone/utils/video.py
Labels: enhancement

#2983 Correct handling of frame fields when modifying app config
  fiftyone/core/odm/mixins.py
Labels: bug

#2959 CVAT v2.4 updates
  fiftyone/utils/cvat.py
Labels: annotation

#2948 Remove unused loading text for tags
  app/packages/core/src/components/SamplesContainer.tsx
  app/packages/state/src/recoil/sidebar.ts
Labels: bug, app

#2918 Handling missing label fields when deleting labels
  fiftyone/core/dataset.py
  tests/unittests/dataset_tests.py
Labels: bug

#2988 Fix modal expansion
  app/packages/core/src/components/Modal/Modal.tsx
Labels: bug, app

#2997 Embedded field visibility support and useSetView fix
  app/packages/core/src/components/Sidebar/Entries/FilterEntry.tsx
  app/packages/state/src/hooks/useSchemaSettings.ts
  app/packages/state/src/hooks/useSetView.ts
  app/packages/state/src/routing/RouterContext.ts
Labels: app

#2970 Adding utils to patch broken saved view/run docs
  fiftyone/core/dataset.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
  fiftyone/core/runs.py
Labels: bug

#2971 Log warnings that hint how to patch broken saved views and runs
  fiftyone/core/annotation.py
  fiftyone/core/brain.py
  fiftyone/core/dataset.py
  fiftyone/core/evaluation.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/runs.py
  fiftyone/server/mutation.py
  fiftyone/server/query.py
  fiftyone/utils/data/exporters.py
Labels: bug

#2994 Adding fiftyone-db build for Ubuntu 22.04
  .github/workflows/build-db.yml
  docs/source/getting_started/troubleshooting.rst
  install.bash
  package/db/setup.py
Labels: installation

#2930 Replace pkg_resources with importlib.metadata
  .github/workflows/test.yml
  fiftyone/core/session/session.py
  fiftyone/core/utils.py
  fiftyone/utils/clip/zoo.py
  fiftyone/utils/youtube.py
  requirements/common.txt
  requirements/test.txt
  setup.py
Labels: cleaning

#3015 Restrict patching to correct Run class
  fiftyone/core/odm/database.py
Labels: bug

#3028 Add ArrayField and VectorField to unsupported OTHER sidebar group
  app/packages/state/src/recoil/sidebar.ts
  app/packages/utilities/src/index.ts
Labels: bug, cleaning, app

#3038 Plugin updates
  docs/source/cli/index.rst
  fiftyone/core/cli.py
  fiftyone/core/config.py
  fiftyone/core/utils.py
  fiftyone/plugins/__init__.py
  fiftyone/plugins/core.py
  fiftyone/plugins/definitions.py
  fiftyone/server/routes/plugins.py
  fiftyone/utils/github.py
  tests/unittests/plugins/core_tests.py
Labels: enhancement

#3051 Plugin requirements + CLI updates
  app/packages/operators/src/operators.ts
  docs/source/cli/index.rst
  fiftyone/core/cli.py
  fiftyone/core/utils.py
  fiftyone/operators/__init__.py
  fiftyone/operators/builtin.py
  fiftyone/operators/decorators.py
  fiftyone/operators/executor.py
  fiftyone/operators/loader.py
  fiftyone/operators/message.py
  fiftyone/operators/operator.py
  fiftyone/operators/permissions.py
  fiftyone/operators/registry.py
  fiftyone/operators/server.py
  fiftyone/operators/types.py
  fiftyone/plugins/__init__.py
  fiftyone/plugins/core.py
  fiftyone/plugins/definitions.py
  fiftyone/utils/github.py
Labels: enhancement

#3091 Fixing color scheme bugs
  fiftyone/core/odm/dataset.py
  fiftyone/core/session/session.py
  fiftyone/core/state.py
Labels: bug

#3092 Welcome message!
  README.md
  app/packages/components/src/components/Icons/Icons.tsx
  app/packages/desktop/src/menu.ts
  docs/source/conf.py
  docs/source/getting_started/troubleshooting.rst
  docs/source/index.rst
  docs/source/release-notes.rst
  fiftyone/constants.py
  fiftyone/core/session/session.py
Labels: documentation

#3099 Bugfix:sample tag color does not respect field color
  app/packages/core/src/components/Filters/BooleanFieldFilter.tsx
  app/packages/core/src/components/Filters/LabelFieldFilter.tsx
  app/packages/core/src/components/Filters/StringFieldFilter.tsx
  app/packages/looker/src/elements/common/tags.ts
Labels: bug

#3110 [Docs] Teams Docs Typo
  docs/source/teams/index.rst
Labels: documentation

#3100 Filter out flattened and redundant sub fields to avoid overcounting label paths, failed tagging, etc.
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry.tsx
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/elements/common/util.ts
  app/packages/looker/src/overlays/base.ts
  app/packages/looker/src/overlays/classifications.ts
  app/packages/looker/src/overlays/index.ts
  app/packages/looker/src/overlays/util.ts
  app/packages/looker/src/worker/painter.ts
  app/packages/state/src/hooks/useUpdateSamples.ts
  app/packages/state/src/recoil/aggregations.ts
  app/packages/state/src/recoil/schema.ts
  fiftyone/core/collections.py
  fiftyone/server/routes/tag.py
Labels: bug

#3122 account for url filepaths with query params
  app/packages/state/src/hooks/useCreateLooker.ts
Labels: bug

#3120 Bugfix: Tagger should count embeddedDocField labels for selected samples
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/elements/common/util.ts
  fiftyone/server/routes/tagging.py
  fiftyone/server/utils.py
  fiftyone/server/view.py
Labels: bug

#3066 Add `run_sync_task` utility
  fiftyone/core/session/events.py
  fiftyone/core/utils.py
  fiftyone/server/query.py
  fiftyone/server/routes/embeddings.py
  fiftyone/server/view.py
Labels: cleaning

#3123 Assume line annotations are not closed
  fiftyone/utils/scale.py
Labels: bug

#3133 Fix label tag matching in sidebar
  fiftyone/core/collections.py
  fiftyone/core/stages.py
  fiftyone/server/utils.py
  fiftyone/server/view.py
Labels: bug, app, server

#3139 Serialization cleanup
  fiftyone/core/json.py
  fiftyone/core/session/client.py
  fiftyone/core/session/events.py
  fiftyone/core/state.py
  fiftyone/operators/server.py
  fiftyone/server/decorators.py
  fiftyone/server/events.py
  fiftyone/server/mutation.py
  fiftyone/server/routes/samples.py
  fiftyone/server/routes/sort.py
Labels: cleaning, server

#3144 Update server tests
  tests/unittests/server_tests.py
Labels: bug, cleaning, testing
