Repository voxel51/fiftyone, pull requests merged in 2023-06, with the labels that each got.

#3155 dynamic groups e2e
  app/packages/components/src/components/PillButton/PillButton.tsx
  app/packages/components/src/components/Results/Results.tsx
  app/packages/components/src/components/Selector/Selector.tsx
  app/packages/components/src/components/TabOption/TabOption.tsx
  app/packages/components/src/components/Tooltip/Tooltip.tsx
  app/packages/core/src/components/Actions/DynamicGroup.tsx
  app/packages/core/src/components/Actions/DynamicGroupAction.tsx
  app/packages/core/src/components/Common/Checkbox.tsx
  app/packages/core/src/components/ImageContainerHeader.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/NestedGroup/GroupElementsLinkBar.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/NestedGroup/PaginationComponentWithTooltip.tsx
  app/packages/core/src/components/Modal/Group/GroupSampleWrapper.tsx
  app/packages/core/src/components/Modal/Modal.tsx
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry.tsx
  app/packages/core/src/components/ViewBar/ViewBar.tsx
  app/packages/core/src/components/ViewBar/ViewStage/ViewStage.tsx
  app/packages/looker/src/elements/common/tags.ts
  e2e/cypress.config.ts
  e2e/cypress/e2e/datasets/quickstart-groups/quickstart-groups.cy.ts
  e2e/cypress/e2e/dynamic-groups/dynamic-groups.cy.ts
  e2e/cypress/fixtures/3d/pointcloud-only-datasets - before.cy.py
  e2e/cypress/fixtures/dynamic-groups/dynamic-groups.cy.py
  e2e/cypress/fixtures/quickstart-groups/quickstart-groups - before.cy.py
  e2e/cypress/support/commands.ts
  e2e/cypress/support/e2e.ts
  e2e/lib/python-runner.ts
  e2e/package.json
  e2e/types/cypress.d.ts
  e2e/yarn.lock
Labels: testing

#3159 Fixing merge_samples() for video datasets
  fiftyone/core/dataset.py
  tests/unittests/video_tests.py
Labels: bug

#3174 use $addFields and $project in aggregation pipelines
  fiftyone/core/aggregations.py
  fiftyone/core/clips.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/database.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/patches.py
  fiftyone/core/stages.py
  fiftyone/core/video.py
  fiftyone/server/samples.py
  fiftyone/server/view.py
  tests/unittests/server_tests.py
Labels: enhancement, experimental

#3177 Adding --all flags to plugin CLI methods
  docs/source/cli/index.rst
  fiftyone/core/cli.py
Labels: enhancement

#3152 Dynamic label field upgrades
  fiftyone/core/clips.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/fields.py
  fiftyone/core/labels.py
  fiftyone/core/models.py
  fiftyone/core/odm/document.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/odm/utils.py
  fiftyone/core/patches.py
  fiftyone/core/stages.py
  fiftyone/server/utils.py
  fiftyone/server/view.py
  fiftyone/utils/annotations.py
  tests/unittests/dataset_tests.py
  tests/unittests/import_export_tests.py
  tests/unittests/label_tests.py
  tests/unittests/sample_tests.py
Labels: bug, core

#3095 Add persistent and overwrite arguments to dataset factory functions
  fiftyone/core/dataset.py
  tests/unittests/dataset_tests.py
Labels: enhancement

#3137 Sample and serialization IO optimizations
  app/packages/app/src/Network.tsx
  app/packages/app/src/index.tsx
  app/packages/core/src/Dataset.ts
  app/packages/core/src/Root/Datasets/Dataset.tsx
  app/packages/core/src/Root/Root.tsx
  app/packages/core/src/__generated__/DatasetQuery.graphql.ts
  app/packages/core/src/components/Actions/Tagger.tsx
  app/packages/core/src/components/Actions/similar/utils.ts
  app/packages/core/src/components/Dataset.tsx
  app/packages/core/src/components/FieldLabelAndInfo/index.tsx
  app/packages/core/src/components/Filters/categoricalFilter/CategoricalFilter.tsx
  app/packages/core/src/components/Grid/Grid.tsx
  app/packages/core/src/components/Grid/useEscape.ts
  app/packages/core/src/components/Grid/useExpandSample.ts
  app/packages/core/src/components/ImageContainerHeader.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/carousel/DynamicGroupsFlashlightWrapper.tsx
  app/packages/core/src/components/Modal/Group/GroupCarousel.tsx
  app/packages/core/src/components/Modal/Group/GroupContextProvider.tsx
  app/packages/core/src/components/Modal/Group/GroupView.tsx
  app/packages/core/src/components/Modal/Looker.tsx
  app/packages/core/src/components/Modal/Modal.tsx
  app/packages/core/src/components/Modal/ModalNavigation.tsx
  app/packages/core/src/components/Modal/Sample.tsx
  app/packages/core/src/components/Modal/Sample3d.tsx
  app/packages/core/src/components/Modal/hooks.ts
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry.tsx
  app/packages/core/src/components/Sidebar/Sidebar.tsx
  app/packages/relay/src/queries/__generated__/mainSampleQuery.graphql.ts
  app/packages/relay/src/queries/__generated__/pcdSampleQuery.graphql.ts
  app/packages/relay/src/queries/mainSample.ts
  app/packages/relay/src/queries/pcdSample.ts
  app/packages/state/src/hooks/useClearModal.ts
  app/packages/state/src/hooks/useExpandSample.ts
  app/packages/state/src/hooks/useSetExpandedSample.ts
  app/packages/state/src/hooks/useStateUpdate.ts
  app/packages/state/src/hooks/useTooltip.ts
  app/packages/state/src/recoil/aggregations.ts
  app/packages/state/src/recoil/atoms.ts
  app/packages/state/src/recoil/filters.ts
  app/packages/state/src/recoil/groups.ts
  app/packages/state/src/recoil/modal.ts
  app/packages/state/src/recoil/selectors.ts
  app/packages/state/src/recoil/utils.ts
  app/schema.graphql
  fiftyone/core/stages.py
  fiftyone/core/utils.py
  fiftyone/server/events.py
  fiftyone/server/query.py
  fiftyone/server/routes/samples.py
  fiftyone/server/routes/tagging.py
  fiftyone/server/samples.py
  fiftyone/server/view.py
  tests/unittests/server_tests.py
Labels: enhancement, app

#3182 Bumping compatibility version
  fiftyone/constants.py
Labels: bug

#3196 Do not recognize list fields as containing labels
  fiftyone/core/collections.py
Labels: bug

#3209 Dynamic groups modal updates
  .github/workflows/build-db.yml
  .github/workflows/build-desktop.yml
  .github/workflows/build-docs.yml
  .github/workflows/build-graphql.yml
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/test.yml
  app/.eslintrc.js
  app/packages/app/vite.config.ts
  app/packages/core/src/Root/Root.tsx
  app/packages/core/src/components/Actions/Selected.tsx
  app/packages/core/src/components/Grid/Grid.tsx
  app/packages/core/src/components/Grid/useExpandSample.ts
  app/packages/core/src/components/Modal/Group/DynamicGroup/NestedGroup/GroupElementsLinkBar.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/NestedGroup/PaginationComponentWithTooltip.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/NestedGroup/index.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/UnorderedDynamicGroup.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/carousel/DynamicGroupsFlashlightWrapper.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/carousel/useSetDynamicGroupSample.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/index.tsx
  app/packages/core/src/components/Modal/Group/Group.module.css
  app/packages/core/src/components/Modal/Group/GroupCarousel.tsx
  app/packages/core/src/components/Modal/Group/GroupContextProvider.tsx
  app/packages/core/src/components/Modal/Group/GroupImageVideoSample.tsx
  app/packages/core/src/components/Modal/Group/GroupView.tsx
  app/packages/core/src/components/Modal/Group/index.tsx
  app/packages/core/src/components/Modal/Group/useSetGroupSample.ts
  app/packages/core/src/components/Modal/Looker.tsx
  app/packages/core/src/components/Modal/Modal.tsx
  app/packages/core/src/components/Modal/ModalNavigation.tsx
  app/packages/core/src/components/Sidebar/Entries/PathValueEntry.tsx
  app/packages/looker/src/index.ts
  app/packages/relay/src/queries/__generated__/mainSampleQuery.graphql.ts
  app/packages/relay/src/queries/mainSample.ts
  app/packages/state/src/hooks/useCreateLooker.ts
  app/packages/state/src/hooks/useExpandSample.ts
  app/packages/state/src/hooks/useLookerStore.ts
  app/packages/state/src/hooks/useSetExpandedSample.ts
  app/packages/state/src/recoil/aggregations.ts
  app/packages/state/src/recoil/groups.ts
  app/packages/state/src/recoil/modal.ts
  app/packages/state/src/recoil/schema.ts
  app/packages/state/src/recoil/selectors.ts
  app/packages/state/src/recoil/utils.ts
  app/packages/state/src/recoil/view.ts
  e2e/cypress.config.ts
  e2e/cypress/e2e/dynamic-groups/dynamic-groups.cy.ts
  e2e/cypress/support/commands.ts
  e2e/package.json
  e2e/yarn.lock
  fiftyone/core/collections.py
  fiftyone/server/query.py
Labels: bug, app

#3222 Session proxy url
  docs/source/user_guide/config.rst
  fiftyone/core/config.py
  fiftyone/core/context.py
  fiftyone/core/session/notebooks.py
  fiftyone/core/session/session.py
Labels: enhancement, core, notebook

#3230 Allow coloring embeddings plots by list fields
  fiftyone/server/routes/embeddings.py
Labels: enhancement

#3233 Restricted supported App labels to match SDK
  app/packages/core/src/components/Actions/Patcher.tsx
  app/packages/core/src/components/FieldLabelAndInfo/index.tsx
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/overlays/index.ts
  app/packages/looker/src/worker/index.ts
  app/packages/state/src/hooks/useSchemaSettings.ts
  app/packages/state/src/hooks/useStateUpdate.ts
  app/packages/state/src/recoil/aggregations.ts
  app/packages/state/src/recoil/schema.ts
  app/packages/state/src/recoil/sidebar.ts
  app/packages/state/src/recoil/types.ts
  app/packages/state/src/recoil/utils.ts
  app/packages/state/tests/recoil/sidebar.test.ts
  app/packages/utilities/src/index.ts
  fiftyone/core/patches.py
  fiftyone/core/stages.py
Labels: bug, enhancement, app

#3240 Fix numeric fields display bug
  app/packages/core/src/components/Filters/NumericFieldFilter.tsx
Labels: bug
