Repository voxel51/fiftyone, pull requests merged in 2023-12, with the labels that each got.

#3858 bugfix: tag labels in multiple samples can only tag labels in the last sample successfully
  app/packages/core/src/components/Actions/utils.tsx
Labels: bug

#3855 Fix Take seed in App
  app/packages/core/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts
  app/packages/relay/src/graphQLSyncFragmentAtom.ts
  app/packages/relay/src/selectorWithEffect.tsx
  app/packages/state/src/recoil/atoms.ts
  app/packages/state/src/recoil/view.ts
Labels: bug, app

#3794 Documenting Redis vector search integration
  docs/source/_static/images/integrations/redis.jpg
  docs/source/index.rst
  docs/source/integrations/index.rst
  docs/source/integrations/redis.rst
  docs/source/user_guide/brain.rst
Labels: documentation, feature

#3845 migration script and documentation for colorscheme
  app/packages/core/src/components/ColorModal/FieldSetting.tsx
  docs/source/user_guide/app.rst
  fiftyone/core/odm/dataset.py
  fiftyone/migrations/revisions/v0_23_0.py
Labels: documentation, core

#3795 Documenting MongoDB vector search integration
  docs/source/_static/images/integrations/mongodb.jpg
  docs/source/index.rst
  docs/source/integrations/index.rst
  docs/source/integrations/mongodb.rst
  docs/source/user_guide/brain.rst
  fiftyone/core/stages.py
Labels: documentation, feature

#3869 ImaVid zoom/pan, loop, and disabled overlays
  app/packages/looker/src/elements/image.ts
  app/packages/looker/src/elements/imavid/index.ts
  app/packages/looker/src/elements/imavid/loader-bar.ts
  app/packages/looker/src/elements/imavid/play-button.ts
  app/packages/looker/src/elements/imavid/seek-bar-thumb.ts
  app/packages/looker/src/elements/imavid/seek-bar.ts
  app/packages/looker/src/elements/video.ts
  app/packages/looker/src/lookers/abstract.ts
  app/packages/looker/src/lookers/image.ts
  app/packages/looker/src/lookers/imavid/ima-vid-frame-samples.ts
  app/packages/looker/src/lookers/imavid/index.ts
  app/packages/looker/src/state.ts
Labels: enhancement, app

#3873 Lightning numeric modal bounds
  app/packages/state/src/recoil/aggregations.ts
Labels: bug

#3877 Always show lightning search input
  app/packages/components/src/components/TabOption/TabOption.tsx
  app/packages/core/src/components/Filters/StringFilter/useSelected.ts
Labels: bug

#3879 Check for None fields value in migration
  fiftyone/migrations/revisions/v0_23_0.py
Labels: bug

#3894 Ensure group indexes exist when importing FiftyOneDataset format
  fiftyone/utils/data/importers.py
  tests/unittests/group_tests.py
Labels: bug

#3903 Handle App query errors
  app/packages/app/src/pages/datasets/DatasetPage.tsx
  app/packages/app/src/routing/RouterContext.ts
  app/packages/app/src/routing/useRouter.ts
  app/packages/state/src/utils.ts
Labels: bug, app

#3905 Fix App server on Python 3.8
  fiftyone/server/query.py
  tests/unittests/server_tests.py
Labels: bug, server

#3900 Fixing bug when inferring doubly-nested dynamic list field types
  fiftyone/core/collections.py
  tests/unittests/dataset_tests.py
Labels: bug

#3910 Documenting V7 integration
  docs/source/_static/images/integrations/v7.jpg
  docs/source/images/integrations/v7-hero.jpg
  docs/source/index.rst
  docs/source/integrations/index.rst
  docs/source/integrations/v7.rst
  docs/source/release-notes.rst
Labels: documentation

#3915 Teams v1.5.2 release notes
  docs/source/_static/images/integrations/v7.jpg
  docs/source/images/integrations/v7-hero.jpg
  docs/source/index.rst
  docs/source/integrations/index.rst
  docs/source/integrations/v7.rst
  docs/source/release-notes.rst
Labels: documentation

#3916 Fix documentation references
  docs/source/environments/index.rst
  docs/source/faq/index.rst
  docs/source/user_guide/config.rst
Labels: documentation

#3913 Don't overwrite dataset metadata with empty values during imports
  fiftyone/utils/data/importers.py
  tests/unittests/import_export_tests.py
Labels: enhancement

#3914 Invalidate builtin operators when there's nothing to do
  fiftyone/operators/builtin.py
Labels: enhancement

#3912 bugfix: similarity search only works on default_group_slice
  app/packages/core/src/components/Actions/similar/utils.ts
  app/packages/state/src/recoil/groups.ts
  app/packages/state/src/recoil/selectors.ts
  app/packages/state/src/session.ts
  fiftyone/server/routes/sort.py
Labels: bug

#3933 Fix Lightning threshold reset
  app/packages/state/src/recoil/lightning.ts
Labels: bug, app

#3932 Update selected sample operators
  app/packages/operators/src/built-in-operators.ts
Labels: bug, app

#3942 Optimize reload docs when performing bulk writes
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/singletons.py
Labels: enhancement

#3939 SDK operator execution tweaks + docs
  docs/source/plugins/using_plugins.rst
  fiftyone/core/cli.py
  fiftyone/operators/executor.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/zoo/datasets/__init__.py
  setup.py
Labels: enhancement

#3946 Update iou.py (cherry-pick)
  fiftyone/utils/iou.py
Labels: enhancement

#3948 Cherry picking OpenCLIP for 0.23.2 release
  docs/scripts/make_model_zoo_docs.py
  fiftyone/utils/open_clip.py
  fiftyone/zoo/models/manifest-torch.json
Labels: feature
