Repository voxel51/fiftyone, pull requests merged in 2023-04, with the labels that each got.

#2862 add --upgrade to fiftyone-brain source install
  install.bash
Labels: installation

#2525 Complex YOLO tweaks
  fiftyone/utils/complex_yolo/__init__.py
  fiftyone/utils/complex_yolo/model.py
  fiftyone/utils/complex_yolo/zoo.py
  fiftyone/utils/torch.py
  fiftyone/zoo/models/manifest-torch.json
Labels: cleaning

#2815 Documenting Teams Azure support
  docs/source/teams/installation.rst
Labels: documentation

#2874 Fixing bug when loading saved view in App
  fiftyone/core/state.py
Labels: bug, app

#2844 Avoid errors during failed merge cleanup
  fiftyone/core/dataset.py
Labels: bug

#2846 Pulling correct data when viewing patches with a sample embeddings plot
  fiftyone/server/routes/embeddings.py
Labels: bug

#2863 Adding support for dynamically inferring fields on embedded lists and documents
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/fields.py
  fiftyone/core/labels.py
  fiftyone/core/odm/mixins.py
  tests/unittests/dataset_tests.py
Labels: enhancement

#2879 Fix field mask targets for RGB
  app/packages/looker/src/worker/index.ts
Labels: bug, app

#2882 Adding support for list fields to dynamic schema methods
  docs/source/user_guide/using_aggregations.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/__public__.py
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/mixins.py
  tests/unittests/aggregation_tests.py
  tests/unittests/dataset_tests.py
Labels: feature, core

#2873 Release v0.20.1
  app/packages/looker/src/overlays/heatmap.ts
  app/packages/looker/src/overlays/util.ts
  app/packages/looker/src/worker/index.ts
  app/packages/looker/src/worker/painter.ts
  app/packages/state/src/recoil/selectors.ts
  docs/source/integrations/pinecone.rst
  docs/source/integrations/qdrant.rst
  docs/source/release-notes.rst
  docs/source/user_guide/using_aggregations.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/__public__.py
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/mixins.py
  fiftyone/server/extensions.py
  fiftyone/server/query.py
  package/desktop/setup.py
  package/graphql/setup.py
  requirements/common.txt
  setup.py
  tests/unittests/aggregation_tests.py
  tests/unittests/dataset_tests.py
Labels: release

#2901 Finishing Dice score
  fiftyone/utils/eval/segmentation.py
  tests/intensive/evaluation_tests.py
Labels: evaluation

#2910 Add stack to GraphQL error extensions
  fiftyone/server/extensions.py
Labels: bug

#2890 Revalidate stages upon view reload
  fiftyone/core/clips.py
  fiftyone/core/patches.py
  fiftyone/core/video.py
  fiftyone/core/view.py
  tests/unittests/similarity_tests.py
  tests/unittests/view_tests.py
Labels: enhancement
