Repository voxel51/fiftyone, pull requests merged in 2023-03, with the labels that each got.

#2569 Adding support for querying by vectors/prompts
  docs/source/release-notes.rst
  docs/source/user_guide/app.rst
  docs/source/user_guide/brain.rst
  docs/source/user_guide/using_views.rst
  fiftyone/core/collections.py
  fiftyone/core/models.py
  fiftyone/core/stages.py
  fiftyone/server/query.py
  fiftyone/utils/clip/zoo.py
Labels: feature

#2703 Fix tagging selection
  app/packages/core/src/components/Actions/utils.tsx
  app/packages/state/src/recoil/aggregations.ts
Labels: bug, app

#2715 Updating embeddings help link
  app/packages/embeddings/src/Embeddings.tsx
Labels: documentation

#2714 Use "fast" sidebar mode by default
  app/packages/core/src/components/Actions/Options.tsx
  docs/source/user_guide/app.rst
  docs/source/user_guide/config.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/core/config.py
  fiftyone/core/odm/dataset.py
Labels: enhancement

#2296 Adding support for cuboids and rotated boxes
  docs/source/images/datasets/cuboids.png
  docs/source/images/datasets/rotated-bounding-boxes.png
  docs/source/user_guide/basics.rst
  docs/source/user_guide/groups.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/core/labels.py
  fiftyone/utils/iou.py
Labels: feature

#2724 Documenting point cloud datasets
  docs/source/_includes/substitutions.rst
  docs/source/faq/index.rst
  docs/source/images/app/app-3d-visualizer.gif
  docs/source/images/app/app-orthographic-projections.gif
  docs/source/release-notes.rst
  docs/source/user_guide/app.rst
  docs/source/user_guide/config.rst
  docs/source/user_guide/groups.rst
  docs/source/user_guide/using_datasets.rst
Labels: documentation

#2730 Fix session usage for schema changes
  fiftyone/core/session/events.py
  fiftyone/core/state.py
  fiftyone/server/routes/event.py
  fiftyone/server/routes/events.py
Labels: bug, server

#2741 Apply extended stages before filters in extended view
  fiftyone/server/mutation.py
  fiftyone/server/view.py
Labels: bug

#2744 Include ftfy and regex as default packages
  fiftyone/utils/clip/tokenizer.py
  fiftyone/zoo/models/manifest-torch.json
  requirements/common.txt
  setup.py
Labels: bug

#2746 Fix color in field info
  app/packages/core/src/components/FieldLabelAndInfo/index.tsx
Labels: app

#2633 Search by text prompt in the App
  app/packages/components/src/components/ExternalLink/index.ts
  app/packages/components/src/components/IconButton/index.tsx
  app/packages/components/src/components/Tooltip/Tooltip.tsx
  app/packages/components/src/components/index.ts
  app/packages/core/src/Dataset.ts
  app/packages/core/src/__generated__/DatasetQuery.graphql.ts
  app/packages/core/src/components/Actions/ActionsRow.tsx
  app/packages/core/src/components/Actions/Selected.tsx
  app/packages/core/src/components/Actions/Similar.tsx
  app/packages/core/src/components/Actions/similar/GroupButton.tsx
  app/packages/core/src/components/Actions/similar/Similar.tsx
  app/packages/core/src/components/Actions/similar/Warning.tsx
  app/packages/core/src/components/Actions/similar/utils.ts
  app/packages/core/src/components/Common/Input.tsx
  app/packages/core/src/components/Grid/Grid.tsx
  app/packages/core/src/components/Grid/usePage.ts
  app/packages/core/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts
  app/packages/core/src/components/ViewBar/viewBarMachine.ts
  app/packages/core/src/components/utils.tsx
  app/packages/relay/src/mutations/__generated__/setViewMutation.graphql.ts
  app/packages/relay/src/mutations/setView.ts
  app/packages/state/src/recoil/aggregations.ts
  app/packages/state/src/recoil/atoms.ts
  app/packages/state/src/recoil/selectors.ts
  app/packages/state/src/recoil/types.ts
  app/schema.graphql
  fiftyone/server/mutation.py
  fiftyone/server/query.py
  fiftyone/server/samples.py
  fiftyone/server/stages.py
  fiftyone/server/view.py
Labels: feature, app

#2749 fixes #2472
  app/packages/core/src/components/Modal/Looker.tsx
  app/packages/looker/src/elements/common/actions.ts
  app/packages/looker/src/elements/common/looker.ts
Labels: bug, app

#2751 Show error when visualization run has not associated data
  app/packages/embeddings/src/EmbeddingsPlot.tsx
  app/packages/embeddings/src/fetch.tsx
  app/packages/embeddings/src/useViewChangeEffect.tsx
  fiftyone/server/routes/embeddings.py
Labels: bug, app

#2754 Fix Map Panel Crash when Extended Selection is Patch ids
  app/packages/map/src/Map.tsx
Labels: bug, app

#2696 Renaming and saving run results
  app/packages/components/src/components/ExternalLink/index.ts
  app/packages/components/src/components/IconButton/index.tsx
  app/packages/components/src/components/Tooltip/Tooltip.tsx
  app/packages/components/src/components/index.ts
  app/packages/core/src/Dataset.ts
  app/packages/core/src/__generated__/DatasetQuery.graphql.ts
  app/packages/core/src/components/Actions/ActionsRow.tsx
  app/packages/core/src/components/Actions/Selected.tsx
  app/packages/core/src/components/Actions/Similar.tsx
  app/packages/core/src/components/Actions/similar/GroupButton.tsx
  app/packages/core/src/components/Actions/similar/Similar.tsx
  app/packages/core/src/components/Actions/similar/Warning.tsx
  app/packages/core/src/components/Actions/similar/utils.ts
  app/packages/core/src/components/Common/Input.tsx
  app/packages/core/src/components/Grid/Grid.tsx
  app/packages/core/src/components/Grid/usePage.ts
  app/packages/core/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts
  app/packages/core/src/components/ViewBar/viewBarMachine.ts
  app/packages/core/src/components/utils.tsx
  app/packages/relay/src/mutations/__generated__/setViewMutation.graphql.ts
  app/packages/relay/src/mutations/setView.ts
  app/packages/state/src/recoil/aggregations.ts
  app/packages/state/src/recoil/atoms.ts
  app/packages/state/src/recoil/selectors.ts
  app/packages/state/src/recoil/types.ts
  app/schema.graphql
  docs/source/integrations/cvat.rst
  docs/source/integrations/labelbox.rst
  docs/source/integrations/labelstudio.rst
  docs/source/user_guide/annotation.rst
  docs/source/user_guide/brain.rst
  docs/source/user_guide/evaluation.rst
  fiftyone/core/collections.py
  fiftyone/core/runs.py
  fiftyone/server/mutation.py
  fiftyone/server/query.py
  fiftyone/server/samples.py
  fiftyone/server/stages.py
  fiftyone/server/view.py
  fiftyone/utils/annotations.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/eval/activitynet.py
  fiftyone/utils/eval/base.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/openimages.py
  fiftyone/utils/eval/regression.py
  fiftyone/utils/eval/segmentation.py
  tests/unittests/evaluation_tests.py
  tests/unittests/similarity_tests.py
Labels: enhancement

#2727 No unnecessary upserts or frames collections
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/frame.py
  fiftyone/core/odm/document.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/runs.py
  fiftyone/core/sample.py
  fiftyone/server/mutation.py
  fiftyone/utils/data/importers.py
  tests/unittests/dataset_tests.py
  tests/unittests/group_tests.py
  tests/unittests/utils3d_tests.py
  tests/unittests/video_tests.py
Labels: enhancement

#2711 Add dataset ID to all documents
  fiftyone/core/clips.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/frame.py
  fiftyone/core/odm/frame.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/odm/sample.py
  fiftyone/core/patches.py
  fiftyone/core/sample.py
  fiftyone/core/video.py
  fiftyone/migrations/revisions/v0_20_0.py
  fiftyone/utils/data/importers.py
  tests/unittests/dataset_tests.py
  tests/unittests/import_export_tests.py
  tests/unittests/patches_tests.py
  tests/unittests/video_tests.py
Labels: feature

#2557 Tags refactor
  app/packages/components/src/components/Selector/Selector.tsx
  app/packages/core/src/components/FieldLabelAndInfo/index.tsx
  app/packages/core/src/components/Filters/LabelFieldFilter.tsx
  app/packages/core/src/components/Filters/NumericFieldFilter.tsx
  app/packages/core/src/components/Filters/categoricalFilter/CategoricalFilter.tsx
  app/packages/core/src/components/Filters/categoricalFilter/Wrapper.tsx
  app/packages/core/src/components/Filters/categoricalFilter/filterOption/FilterOption.tsx
  app/packages/core/src/components/Modal/Modal.tsx
  app/packages/core/src/components/SamplesContainer.tsx
  app/packages/core/src/components/Sidebar/Entries/Draggable.tsx
  app/packages/core/src/components/Sidebar/Entries/EntryCounts.tsx
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry.tsx
  app/packages/core/src/components/Sidebar/Entries/FilterableTagEntry.tsx
  app/packages/core/src/components/Sidebar/Entries/GroupEntries.tsx
  app/packages/core/src/components/Sidebar/Entries/PathValueEntry.tsx
  app/packages/core/src/components/Sidebar/Entries/TagValueEntry.tsx
  app/packages/core/src/components/Sidebar/Entries/index.tsx
  app/packages/core/src/components/Sidebar/Entries/utils.tsx
  app/packages/core/src/components/Sidebar/Sidebar.tsx
  app/packages/flashlight/src/index.ts
  app/packages/looker/src/elements/common/tags.ts
  app/packages/state/src/recoil/aggregations.ts
  app/packages/state/src/recoil/color.ts
  app/packages/state/src/recoil/filters.ts
  app/packages/state/src/recoil/pathFilters/index.ts
  app/packages/state/src/recoil/schema.ts
  app/packages/state/src/recoil/sidebar.ts
  app/packages/state/src/recoil/types.ts
  app/packages/state/tests/recoil/sidebar.test.ts
  fiftyone/core/odm/dataset.py
  fiftyone/migrations/revisions/v0_20_0.py
  fiftyone/server/view.py
  tests/unittests/server_tests.py
Labels: enhancement, feature, app

#2767 Fixing an issue with dynamic embedded list schemas
  fiftyone/core/odm/mixins.py
  fiftyone/core/odm/utils.py
  tests/unittests/dataset_tests.py
Labels: bug

#2770 Adding validation to set_values()
  fiftyone/core/collections.py
  tests/unittests/view_tests.py
Labels: enhancement

#2774 fixes app crashing while filtering keypoints labels (view.py)
  fiftyone/server/view.py
Labels: bug, app

#2782 Fix group selection target
  app/packages/core/src/components/Actions/Selected.tsx
  app/packages/core/src/components/Group/Group.tsx
  app/packages/state/src/recoil/schema.ts
  app/packages/state/src/routing/RouterContext.ts
Labels: bug, app

#2780 similarity sort: last used brainkey should become default
  app/packages/core/src/components/Actions/Selected.tsx
  app/packages/core/src/components/Actions/similar/Similar.tsx
  app/packages/core/src/components/Actions/similar/utils.ts
Labels: enhancement, app

#2781 Use maxK and supportsLeastSimilarity in the UI to restrict search settings
  app/packages/core/src/Dataset.ts
  app/packages/core/src/__generated__/DatasetQuery.graphql.ts
  app/packages/core/src/components/Actions/similar/MaxKWarning.tsx
  app/packages/core/src/components/Actions/similar/Similar.tsx
  app/packages/core/src/components/Actions/similar/utils.ts
  app/packages/state/src/recoil/selectors.ts
  app/packages/state/src/recoil/types.ts
  app/schema.graphql
  fiftyone/server/query.py
Labels: enhancement, app

#2793 fix toPatches modal view regression for similarity search
  app/packages/core/src/components/Actions/ActionsRow.tsx
  app/packages/core/src/components/Actions/similar/utils.ts
Labels: bug, app

#2799 reset selectedLabels after sort submission
  app/packages/core/src/components/Actions/similar/utils.ts
  fiftyone/server/routes/sort.py
Labels: bug, app

#2806 Adding control over importing/exporting runs and saved views
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
Labels: bug

#2805 Release v0.20.0
  app/packages/core/src/components/Actions/similar/utils.ts
  app/packages/core/src/components/Actions/utils.tsx
  app/packages/looker/src/elements/common/canvas.ts
  app/packages/looker/src/lookers/abstract.ts
  app/packages/looker/src/state.ts
  app/packages/looker/src/worker/index.ts
  app/packages/state/src/hooks/hooks-utils.ts
  app/packages/state/src/hooks/useCreateLooker.ts
  app/packages/state/src/hooks/useScreenshot.ts
  app/packages/state/src/recoil/aggregations.ts
  app/packages/state/src/recoil/groups.ts
  app/packages/utilities/src/fetch.ts
  docs/source/release-notes.rst
  fiftyone/constants.py
  fiftyone/core/collections.py
  fiftyone/server/aggregations.py
  fiftyone/server/metadata.py
  fiftyone/server/query.py
  fiftyone/server/routes/sort.py
  fiftyone/server/routes/tag.py
  fiftyone/server/routes/tagging.py
  fiftyone/server/tags.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/utils3d.py
  package/desktop/setup.py
  setup.py
Labels: release

#2750 FiftyOne V2 GraphQL Boilerplate
  .github/CODEOWNERS
  .github/workflows/build-db.yml
  .github/workflows/build-graphql.yml
  fiftyone/server/aggregations.py
  fiftyone/server/extensions.py
  fiftyone/server/inputs.py
  fiftyone/server/mutation.py
  package/graphql/README.md
  package/graphql/fiftyone/__init__.py
  package/graphql/fiftyone/graphql/__init__.py
  package/graphql/setup.py
  requirements/common.txt
  setup.py
Labels: setup, standard

#2838 Update blog link in README.md
  README.md
Labels: documentation

#2849 Hidden results and server MatchLabels fix
  fiftyone/core/collections.py
  fiftyone/server/view.py
  tests/unittests/server_tests.py
Labels: server

#2848 Fixing #2845
  fiftyone/utils/coco.py
  fiftyone/utils/data/importers.py
Labels: bug

#2855 Fixing a bug in dynamic schema expansion
  fiftyone/core/odm/utils.py
  tests/unittests/dataset_tests.py
Labels: bug
