Repository voxel51/fiftyone, pull requests merged in 2023-11, with the labels that each got.

#3749 Fix grid selection and e2e
  .github/workflows/pr.yml
  app/packages/core/src/components/Grid/Grid.tsx
Labels: bug, testing, app

#3755 Ensure main looker is clicked in e2e test
  e2e-pw/src/oss/specs/groups/sparse-groups-scenes.spec.ts
Labels: testing

#3761 Ensure that 3D detection fields are treated as default by SelectFields
  fiftyone/core/collections.py
  tests/unittests/view_tests.py
Labels: bug

#3721 Adding CLI commands for failing/deleting delegated operations
  docs/source/cli/index.rst
  fiftyone/core/cli.py
  setup.py
Labels: enhancement

#3675 fiftyone-db sdist for linux distributions
  .github/workflows/build-db.yml
  docs/source/faq/index.rst
  docs/source/getting_started/troubleshooting.rst
  docs/source/release-notes.rst
  fiftyone/core/odm/database.py
  package/db/setup.py
Labels: bug, enhancement, dependencies

#3760 v0.22.3 Release Notes
  docs/source/release-notes.rst
Labels: documentation, release

#3772 Move Snackbar to @fiftyone/core
  app/packages/app/src/pages/IndexPage.tsx
  app/packages/app/src/pages/datasets/DatasetPage.tsx
  app/packages/core/src/components/Snackbar.tsx
  app/packages/core/src/components/index.ts
Labels: enhancement, app

#3781 Update Labelbox cleanup to support batch mode
  docs/source/integrations/labelbox.rst
  fiftyone/utils/labelbox.py
Labels: annotation

#3622 ColorScheme1.1 (label tags)
  app/packages/app/src/pages/datasets/DatasetPage.tsx
  app/packages/app/src/pages/datasets/__generated__/DatasetPageQuery.graphql.ts
  app/packages/app/src/useSetters/onSetDataset.ts
  app/packages/core/src/components/ColorModal/ColorFooter.tsx
  app/packages/core/src/components/ColorModal/ColorModal.tsx
  app/packages/core/src/components/ColorModal/FieldSetting.tsx
  app/packages/core/src/components/ColorModal/GlobalSetting.tsx
  app/packages/core/src/components/ColorModal/JSONViewer.tsx
  app/packages/core/src/components/ColorModal/LabelTag.tsx
  app/packages/core/src/components/ColorModal/ShareStyledDiv.ts
  app/packages/core/src/components/ColorModal/SidebarList.tsx
  app/packages/core/src/components/ColorModal/colorPalette/FieldByValue.tsx
  app/packages/core/src/components/ColorModal/colorPalette/LabelTagByValue.tsx
  app/packages/core/src/components/ColorModal/controls/ValueColorList.tsx
  app/packages/core/src/components/ColorModal/utils.ts
  app/packages/core/src/components/FieldLabelAndInfo/index.tsx
  app/packages/looker-3d/src/Looker3d.tsx
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/elements/common/util.ts
  app/packages/looker/src/lookers/abstract.ts
  app/packages/looker/src/lookers/shared.ts
  app/packages/looker/src/overlays/base.ts
  app/packages/looker/src/overlays/classifications.ts
  app/packages/looker/src/overlays/util.ts
  app/packages/looker/src/state.ts
  app/packages/looker/src/util.ts
  app/packages/looker/src/worker/index.ts
  app/packages/looker/src/worker/painter.ts
  app/packages/relay/src/fragments/__generated__/colorSchemeFragment.graphql.ts
  app/packages/relay/src/fragments/__generated__/datasetAppConfigFragment.graphql.ts
  app/packages/relay/src/fragments/colorSchemeFragment.ts
  app/packages/relay/src/fragments/datasetAppConfigFragment.ts
  app/packages/relay/src/mutations/__generated__/setColorSchemeMutation.graphql.ts
  app/packages/relay/src/mutations/__generated__/setDatasetColorSchemeMutation.graphql.ts
  app/packages/relay/src/queries/__generated__/datasetQuery.graphql.ts
  app/packages/relay/src/queries/dataset.ts
  app/packages/state/src/recoil/color.ts
  app/packages/state/src/recoil/looker.ts
  app/packages/state/src/session.ts
  app/packages/utilities/src/color.ts
  app/packages/utilities/src/index.ts
  app/schema.graphql
  e2e-pw/src/oss/poms/color-modal/index.ts
  e2e-pw/src/oss/specs/color-scheme/color-scheme.spec.ts
  fiftyone/constants.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/session/events.py
  fiftyone/server/color.py
Labels: app, core

#3787 Better App group slice persistence
  app/packages/app/src/Sync.tsx
  app/packages/app/src/routing/RouterContext.ts
  app/packages/app/src/useEventSource.ts
  app/packages/app/src/useEvents/index.ts
  app/packages/app/src/useEvents/registerEvent.ts
  app/packages/app/src/useEvents/useEvents.ts
  app/packages/app/src/useEvents/useSetGroupSlice.ts
  app/packages/app/src/useEvents/useStateUpdate.ts
  app/packages/app/src/useEvents/utils.ts
  app/packages/app/src/useWriters/useWriters.ts
  app/packages/state/src/session.ts
  e2e-pw/src/oss/specs/regression-tests/group-video/default-video-slice-group.spec.ts
  fiftyone/core/session/session.py
  fiftyone/core/state.py
  fiftyone/server/events.py
  fiftyone/server/mutation.py
Labels: bug, app

#3695 Add support for custom runs
  docs/source/cli/index.rst
  docs/source/plugins/developing_plugins.rst
  docs/source/user_guide/annotation.rst
  docs/source/user_guide/evaluation.rst
  fiftyone/__public__.py
  fiftyone/constants.py
  fiftyone/core/annotation.py
  fiftyone/core/brain.py
  fiftyone/core/cli.py
  fiftyone/core/collections.py
  fiftyone/core/config.py
  fiftyone/core/dataset.py
  fiftyone/core/evaluation.py
  fiftyone/core/odm/__init__.py
  fiftyone/core/odm/database.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/runs.py
  fiftyone/migrations/revisions/v0_23_0.py
  fiftyone/utils/annotations.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/eval/__init__.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/regression.py
  fiftyone/utils/eval/segmentation.py
  tests/unittests/evaluation_tests.py
  tests/unittests/import_export_tests.py
  tests/unittests/run_tests.py
Labels: feature

#3797 Adding plugin notes
  docs/source/index.rst
  docs/source/integrations/cvat.rst
  docs/source/integrations/labelbox.rst
  docs/source/integrations/labelstudio.rst
  docs/source/user_guide/annotation.rst
  docs/source/user_guide/brain.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/dataset_creation/index.rst
  docs/source/user_guide/evaluation.rst
  docs/source/user_guide/export_datasets.rst
Labels: documentation

#3785 Add documentation for Labelbox S3 support
  docs/source/teams/cloud_media.rst
Labels: documentation, annotation

#3799 Update Labelbox integration to handle existing data rows
  docs/source/integrations/labelbox.rst
  fiftyone/utils/labelbox.py
Labels: enhancement, annotation

#3784 Add sample and frame counts to GraphQL Dataset object
  app/packages/app/src/pages/datasets/__generated__/DatasetPageQuery.graphql.ts
  app/packages/app/src/useEvents/utils.ts
  app/packages/relay/src/fragments/__generated__/datasetFragment.graphql.ts
  app/packages/relay/src/fragments/__generated__/estimatedCountsFragment.graphql.ts
  app/packages/relay/src/fragments/datasetFragment.ts
  app/packages/relay/src/fragments/estimatedCountsFragment.ts
  app/packages/relay/src/fragments/index.ts
  app/packages/relay/src/graphQLSyncFragmentAtom.ts
  app/packages/relay/src/queries/__generated__/datasetQuery.graphql.ts
  app/packages/state/src/recoil/dataset.ts
  app/packages/state/src/recoil/index.ts
  app/schema.graphql
  fiftyone/core/odm/database.py
  fiftyone/server/context.py
  fiftyone/server/query.py
Labels: enhancement, server

#3801 Optimize metadata computation
  fiftyone/core/collections.py
  fiftyone/core/metadata.py
Labels: enhancement

#3803 Exhaust generator operators when executing directly
  fiftyone/operators/delegated.py
  fiftyone/operators/executor.py
Labels: bug

#3667 Lightning backend queries
  app/schema.graphql
  fiftyone/core/config.py
  fiftyone/server/aggregations.py
  fiftyone/server/app.py
  fiftyone/server/constants.py
  fiftyone/server/indexes.py
  fiftyone/server/lightning.py
  fiftyone/server/query.py
  tests/unittests/decorators.py
  tests/unittests/index_tests.py
  tests/unittests/lightning_tests.py
Labels: enhancement, feature, server

#3727 Colorscheme1.1 (2D segmentation)
  app/packages/app/src/pages/datasets/DatasetPage.tsx
  app/packages/app/src/pages/datasets/__generated__/DatasetPageQuery.graphql.ts
  app/packages/core/src/components/ColorModal/ColorFooter.tsx
  app/packages/core/src/components/ColorModal/FieldSetting.tsx
  app/packages/core/src/components/ColorModal/GlobalSetting.tsx
  app/packages/core/src/components/ColorModal/JSONViewer.tsx
  app/packages/core/src/components/ColorModal/colorPalette/DatasetColorscale.tsx
  app/packages/core/src/components/ColorModal/colorPalette/DefaultMaskTargets.tsx
  app/packages/core/src/components/ColorModal/colorPalette/FieldsMaskTarget.tsx
  app/packages/core/src/components/ColorModal/controls/IdxColorList.tsx
  app/packages/core/src/components/ColorModal/controls/ModeControl.tsx
  app/packages/core/src/components/ColorModal/state.ts
  app/packages/core/src/components/ColorModal/utils.ts
  app/packages/core/src/components/Common/Input.tsx
  app/packages/looker/src/lookers/shared.ts
  app/packages/looker/src/state.ts
  app/packages/looker/src/worker/painter.ts
  app/packages/relay/src/fragments/__generated__/datasetAppConfigFragment.graphql.ts
  app/packages/relay/src/fragments/datasetAppConfigFragment.ts
  app/packages/relay/src/mutations/__generated__/setColorSchemeMutation.graphql.ts
  app/packages/relay/src/mutations/__generated__/setDatasetColorSchemeMutation.graphql.ts
  app/packages/relay/src/queries/__generated__/datasetQuery.graphql.ts
  app/packages/relay/src/queries/dataset.ts
  app/packages/state/src/recoil/color.ts
  app/schema.graphql
  fiftyone/constants.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/session/events.py
  fiftyone/server/color.py
Labels: app

#3808 Add support for parsing and exporting COCO keypoint visibility
  fiftyone/utils/coco.py
Labels: feature

#3800 Adding a clear_sample_field operator
  fiftyone/operators/builtin.py
Labels: feature

#3814 Use loadable for ctx.current_sample
  app/packages/operators/src/hooks.ts
Labels: bug, app

#3816 Fixes #3763
  fiftyone/core/dataset.py
  tests/unittests/group_tests.py
Labels: bug

#3817 Removing buttons from builtin operators
  app/packages/operators/src/built-in-operators.ts
  fiftyone/operators/builtin.py
Labels: enhancement

#3798 Fix dynamically grouped views for non-group parent media types of grouped datasets
  app/__mocks__/recoil.ts
  app/packages/app/src/pages/datasets/__generated__/DatasetPageQuery.graphql.ts
  app/packages/relay/src/fragments/__generated__/datasetFragment.graphql.ts
  app/packages/relay/src/fragments/datasetFragment.ts
  app/packages/relay/src/queries/__generated__/datasetQuery.graphql.ts
  app/packages/state/src/recoil/groups.test.ts
  app/packages/state/src/recoil/groups.ts
  app/packages/state/src/recoil/view.test.ts
  fiftyone/server/query.py
Labels: bug, app

#3782 DB docs
  docs/source/faq/index.rst
  docs/source/getting_started/troubleshooting.rst
  docs/source/release-notes.rst
Labels: documentation

#3829 teams v1.4.5 Release Notes
  docs/source/release-notes.rst
Labels: documentation, release

#3841 Set color scheme tweaks
  app/packages/app/src/useSetters/onSetColorScheme.ts
  app/packages/state/src/recoil/color.ts
  app/packages/state/src/session.ts
  fiftyone/server/color.py
Labels: cleaning

#3844 Fix set session dataset to None
  fiftyone/server/mutation.py
Labels: server

#3823 fix: #3815 remove cvat filename prefixing
  fiftyone/utils/cvat.py
Labels: enhancement

#3847 colorscheme bugfix
  app/packages/core/src/components/ColorModal/ColorFooter.tsx
  app/packages/core/src/components/ColorModal/ShareStyledDiv.ts
  app/packages/core/src/components/ColorModal/colorPalette/Colorscale.tsx
  app/packages/core/src/components/ColorModal/colorPalette/DatasetColorscale.tsx
  app/packages/core/src/components/ColorModal/colorPalette/FieldColorscale.tsx
  app/packages/core/src/components/ColorModal/colorPalette/GlobalColorscale.tsx
  app/packages/core/src/components/ColorModal/controls/ColorAttribute.tsx
  app/packages/core/src/components/ColorModal/controls/ManualColorScaleList.tsx
  app/packages/core/src/utils/links.ts
  app/packages/relay/src/graphQLSyncFragmentAtom.ts
  app/packages/relay/src/graphQLSyncFragmentAtomFamily.ts
  app/packages/relay/src/mutations/__generated__/setDatasetColorSchemeMutation.graphql.ts
  app/packages/relay/src/mutations/setDatasetColorScheme.ts
  app/schema.graphql
  fiftyone/server/color.py
Labels: bug, app

#3843 Lightning tweaks
  app/packages/components/src/components/Selector/Selector.tsx
  app/packages/components/src/components/Tooltip/Tooltip.tsx
  app/packages/core/src/components/Actions/ActionsRow.tsx
  app/packages/core/src/components/Actions/DynamicGroupAction.tsx
  app/packages/core/src/components/Actions/Options.tsx
  app/packages/core/src/components/Actions/similar/Helper.tsx
  app/packages/core/src/components/Actions/utils.tsx
  app/packages/core/src/components/FieldLabelAndInfo/index.tsx
  app/packages/core/src/components/Filters/NumericFieldFilter/FilterOption.tsx
  app/packages/core/src/components/Filters/NumericFieldFilter/Nonfinites.tsx
  app/packages/core/src/components/Filters/NumericFieldFilter/NumericFieldFilter.tsx
  app/packages/core/src/components/Filters/NumericFieldFilter/state.ts
  app/packages/core/src/components/Filters/StringFilter/Checkboxes.tsx
  app/packages/core/src/components/Filters/StringFilter/StringFilter.tsx
  app/packages/core/src/components/Filters/StringFilter/useSelected.ts
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry/Arrow.tsx
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry/Container.tsx
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry/FilterablePathEntry.tsx
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry/Icon.tsx
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry/LightningFilterablePathEntries.tsx
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry/Loading.tsx
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry/state.ts
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry/useFilterData.ts
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry/useTitleTemplate.tsx
  app/packages/core/src/utils/links.ts
  app/packages/looker/src/elements/common/controls.ts
  app/packages/state/src/recoil/aggregations.ts
  app/packages/state/src/recoil/lightning.ts
  app/packages/state/src/recoil/options.test.ts
  app/packages/state/src/recoil/options.ts
  app/packages/state/src/recoil/pathData/numeric.ts
  app/packages/state/src/recoil/pathFilters/numeric.ts
  app/packages/state/src/recoil/schema.ts
  app/packages/state/src/recoil/sidebar.ts
  fiftyone/core/collections.py
Labels: enhancement
