Repository voxel51/fiftyone, pull requests merged in 2023-07, with the labels that each got.

#3244 [DOCS] Compound indexes for group datasets
  docs/source/user_guide/app.rst
Labels: documentation

#3251 Release v0.21.2
  .github/workflows/pr.yml
  .github/workflows/publish.yml
  app/packages/core/src/components/Grid/Grid.tsx
  app/packages/core/src/components/Grid/usePage.ts
  app/packages/state/src/recoil/pathFilters/string.ts
  app/packages/state/src/recoil/sidebar.ts
  app/packages/state/src/recoil/utils.ts
  app/packages/state/tests/recoil/sidebar.test.ts
  docs/source/release-notes.rst
  package/desktop/setup.py
  setup.py
Labels: release

#3259 LanceDB integration docs
  docs/source/_static/images/integrations/lancedb.png
  docs/source/integrations/index.rst
  docs/source/integrations/lancedb.rst
  docs/source/user_guide/brain.rst
Labels: documentation

#3267 Fix label tags counts for filterless view
  fiftyone/server/view.py
Labels: bug, app, server

#3262 Fix expanding samples in patches views for group datasets
  app/packages/state/src/recoil/groups.ts
Labels: bug, app

#3253 Updating `Session.close()`
  fiftyone/core/session/client.py
  fiftyone/core/session/session.py
Labels: enhancement, app, core

#3256 Embedded frame label fixes
  fiftyone/core/collections.py
  fiftyone/core/stages.py
  tests/unittests/label_tests.py
Labels: bug, core

#3274 Adding merge_sample() method
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/mixins.py
  tests/unittests/dataset_tests.py
Labels: bug, feature

#3270 Fix sidebar matching on label fields
  fiftyone/server/view.py
Labels: app, server, release

#3279 Fixing #3277
  fiftyone/core/collections.py
  fiftyone/core/stages.py
  tests/unittests/view_tests.py
Labels: bug

#3280 Sidebar filtering tests and fixes
  app/packages/core/src/components/Filters/BooleanFieldFilter.tsx
  app/packages/core/src/components/Filters/LabelFieldFilter.tsx
  app/packages/core/src/components/Filters/NumericFieldFilter.tsx
  app/packages/core/src/components/Filters/StringFieldFilter.tsx
  app/packages/core/src/components/Filters/categoricalFilter/CategoricalFilter.tsx
  app/packages/core/src/components/Filters/categoricalFilter/Wrapper.tsx
  app/packages/core/src/components/Filters/categoricalFilter/filterOption/FilterOption.tsx
  app/packages/state/src/recoil/aggregations.ts
  fiftyone/server/samples.py
  fiftyone/server/view.py
  tests/unittests/server_tests.py
Labels: bug, cleaning, app, server

#3288 Updating logo wall links
  docs/source/index.rst
Labels: documentation, hotfix

#3293 Label conversion bugfix/tests
  fiftyone/core/fields.py
  fiftyone/core/labels.py
  tests/unittests/label_tests.py
Labels: bug

#3303 Release v0.21.4
  docs/source/release-notes.rst
  fiftyone/core/session/client.py
  setup.py
Labels: hotfix, release

#3310 Cloud cache works with datasets or views
  docs/source/teams/cloud_media.rst
Labels: documentation

#3308 Improved robustness of concurrent schema updates
  fiftyone/core/dataset.py
  fiftyone/core/odm/document.py
  fiftyone/core/odm/mixins.py
Labels: bug

#3297 Remove starlette ceiling
  setup.py
Labels: server, dependencies

#3326 Embeddings only color-by supported list fields
  fiftyone/server/routes/embeddings.py
Labels: bug

#3328 Only use MPS when manually specified
  fiftyone/utils/torch.py
Labels: bug

#3323 Resolve errors with Labelbox integration
  fiftyone/utils/labelbox.py
Labels: bug, annotation

#3330 Adding Segment Anything to the model zoo!
  docs/scripts/make_model_zoo_docs.py
  fiftyone/core/models.py
  fiftyone/utils/sam.py
  fiftyone/utils/torch.py
  fiftyone/zoo/models/manifest-torch.json
  tests/intensive/model_zoo_tests.py
Labels: feature, model zoo

#3317 Dependency cleanup
  app/packages/looker-3d/load_kiti.py
  app/packages/looker-3d/load_kitti_labels.py
  requirements/common.txt
  setup.py
Labels: cleaning, dependencies

#3349 Ensure has_field() supports dynamic fields
  fiftyone/core/fields.py
  fiftyone/core/odm/document.py
  fiftyone/core/odm/embedded_document.py
  tests/unittests/dataset_tests.py
  tests/unittests/label_tests.py
Labels: bug

#3336 Reapply schema changes after selecting group slices
  fiftyone/core/stages.py
  fiftyone/core/view.py
  tests/unittests/group_tests.py
Labels: bug

#3325 Adding CTAs to Teams docs
  docs/source/_static/images/icons/browser-512px.png
  docs/source/_static/images/icons/statistics-512px.png
  docs/source/_static/images/icons/voxel51-166px.png
  docs/source/_static/images/icons/zoom-512px.png
  docs/source/teams/index.rst
Labels: documentation

#3319 Support to custom color by ListField with boolean, string, and int subfields
  app/packages/core/src/components/ColorModal/FieldSetting.tsx
  app/packages/looker-3d/src/Looker3d.tsx
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/elements/common/util.test.ts
  app/packages/looker/src/elements/common/util.ts
  app/packages/looker/src/overlays/base.ts
  app/packages/looker/src/overlays/util.ts
Labels: app
