Repository voxel51/fiftyone, pull requests merged in 2023-10, with the labels that each got.

#3599 Lint parent media type
  fiftyone/core/view.py
Labels: cleaning

#3607 Fix release PRs
  .github/workflows/test.yml
Labels: bug, testing, ci

#3606 Bugfix: color by value (index) on video
  app/packages/looker-3d/src/Looker3d.tsx
  app/packages/looker/src/overlays/base.ts
  app/packages/looker/src/worker/painter.ts
Labels: bug

#3589 Color by instance
  app/packages/components/src/components/Popout/index.tsx
  app/packages/components/src/components/index.ts
  app/packages/core/src/components/ColorModal/FieldSetting.tsx
  app/packages/core/src/components/ColorModal/GlobalSetting.tsx
  app/packages/core/src/components/ColorModal/controls/ModeControl.tsx
  app/packages/core/src/components/Common/RadioGroup.tsx
  app/packages/core/src/components/FieldLabelAndInfo/index.tsx
  app/packages/looker-3d/src/Looker3d.tsx
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/elements/common/util.ts
  app/packages/looker/src/overlays/base.ts
  app/packages/looker/src/overlays/classifications.ts
  app/packages/looker/src/overlays/util.ts
  app/packages/looker/src/state.ts
  app/packages/looker/src/worker/painter.ts
Labels: app

#3617 Fix actions row component
  app/packages/core/src/components/Actions/ActionsRow.tsx
  app/packages/core/src/components/ColorModal/ColorFooter.tsx
  fiftyone/server/events.py
Labels: bug, app

#3555 global settings persistent + color by instance
  app/packages/app/src/Sync.tsx
  app/packages/app/src/pages/IndexPage.tsx
  app/packages/app/src/pages/__generated__/IndexPageQuery.graphql.ts
  app/packages/app/src/pages/datasets/DatasetPage.tsx
  app/packages/app/src/pages/datasets/__generated__/DatasetPageQuery.graphql.ts
  app/packages/app/src/useEvents/utils.ts
  app/packages/app/src/useSetters/onSetDataset.ts
  app/packages/components/src/components/Popout/index.tsx
  app/packages/components/src/components/index.ts
  app/packages/core/src/components/ColorModal/ColorFooter.tsx
  app/packages/core/src/components/ColorModal/ColorModal.tsx
  app/packages/core/src/components/ColorModal/FieldSetting.tsx
  app/packages/core/src/components/ColorModal/GlobalSetting.tsx
  app/packages/core/src/components/ColorModal/JSONViewer.tsx
  app/packages/core/src/components/ColorModal/colorPalette/AttributeColorSetting.tsx
  app/packages/core/src/components/ColorModal/colorPalette/ColorPalette.tsx
  app/packages/core/src/components/ColorModal/controls/ColorAttribute.tsx
  app/packages/core/src/components/ColorModal/controls/ModeControl.tsx
  app/packages/core/src/components/ColorModal/controls/RefreshColor.tsx
  app/packages/core/src/components/ColorModal/state.ts
  app/packages/core/src/components/Common/RadioGroup.tsx
  app/packages/core/src/components/FieldLabelAndInfo/index.tsx
  app/packages/embeddings/src/EmbeddingsPlot.tsx
  app/packages/looker-3d/src/Looker3d.tsx
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/elements/common/util.ts
  app/packages/looker/src/overlays/base.ts
  app/packages/looker/src/overlays/classifications.ts
  app/packages/looker/src/overlays/util.ts
  app/packages/looker/src/state.ts
  app/packages/looker/src/worker/painter.ts
  app/packages/operators/src/built-in-operators.ts
  app/packages/relay/src/fragments/__generated__/colorSchemeFragment.graphql.ts
  app/packages/relay/src/fragments/__generated__/configFragment.graphql.ts
  app/packages/relay/src/fragments/__generated__/datasetAppConfigFragment.graphql.ts
  app/packages/relay/src/fragments/colorSchemeFragment.ts
  app/packages/relay/src/fragments/configFragment.ts
  app/packages/relay/src/fragments/datasetAppConfigFragment.ts
  app/packages/relay/src/mutations/__generated__/setColorSchemeMutation.graphql.ts
  app/packages/relay/src/mutations/__generated__/setDatasetColorSchemeMutation.graphql.ts
  app/packages/relay/src/queries/__generated__/configQuery.graphql.ts
  app/packages/relay/src/queries/__generated__/datasetQuery.graphql.ts
  app/packages/relay/src/queries/dataset.ts
  app/packages/state/src/hooks/index.ts
  app/packages/state/src/hooks/useGlobalColorSetting.ts
  app/packages/state/src/recoil/atoms.ts
  app/packages/state/src/recoil/color.ts
  app/packages/state/src/recoil/looker.ts
  app/packages/state/src/session.ts
  app/schema.graphql
  e2e-pw/src/oss/poms/color-modal/index.ts
  e2e-pw/src/oss/specs/color-scheme/color-scheme.spec.ts
  e2e-pw/src/oss/specs/sidebar/sidebar-cifar.spec.ts
  fiftyone/core/config.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/session/events.py
  fiftyone/core/state.py
  fiftyone/server/color.py
  fiftyone/server/query.py
Labels: app, core

#3612 Plugin utils
  fiftyone/plugins/core.py
  fiftyone/plugins/utils.py
  fiftyone/utils/github.py
  setup.py
Labels: feature

#3623 Add build system to pyproject.toml
  MANIFEST.in
  pyproject.toml
Labels: cleaning, standard

#3619 Fix bookmark filters action
  app/packages/core/src/components/Actions/ActionsRow.tsx
  app/packages/relay/src/graphQLSyncFragmentAtom.ts
  e2e-pw/src/oss/poms/action-row/grid-actions-row.ts
  e2e-pw/src/oss/specs/smoke-tests/quickstart.spec.ts
Labels: bug, app

#3627 Fix group.id index
  fiftyone/core/dataset.py
Labels: bug, core

#3651 Adding support for directly exporting object patches
  docs/source/user_guide/export_datasets.rst
  fiftyone/utils/coco.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/patches.py
  tests/unittests/import_export_tests.py
Labels: bug

#3660 fix type errors
  app/packages/state/src/recoil/color.ts
  fiftyone/core/state.py
Labels: bug

#3659 Fix duplicate import
  .github/workflows/pr.yml
  app/packages/core/src/components/Modal/Sample.tsx
Labels: bug, app

#3654 Standardizing handling of thread/process pool sizes
  docs/source/cli/index.rst
  docs/source/user_guide/config.rst
  fiftyone/core/cli.py
  fiftyone/core/collections.py
  fiftyone/core/config.py
  fiftyone/core/metadata.py
  fiftyone/core/storage.py
  fiftyone/core/utils.py
  fiftyone/plugins/utils.py
  fiftyone/utils/activitynet.py
  fiftyone/utils/aws.py
  fiftyone/utils/beam.py
  fiftyone/utils/coco.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/base.py
  fiftyone/utils/image.py
  fiftyone/utils/kinetics.py
  fiftyone/utils/kitti.py
  fiftyone/utils/openimages.py
  fiftyone/utils/sama.py
  fiftyone/utils/youtube.py
  fiftyone/zoo/datasets/base.py
Labels: enhancement

#3655 Fix dataset deletion/recreation across processes
  fiftyone/core/singletons.py
  tests/unittests/synchronization_tests.py
Labels: bug, app, core

#3645 Add polling to Colab session URL
  fiftyone/core/context.py
Labels: bug, notebook

#3666 Patches group slice fix
  e2e-pw/src/oss/specs/groups/group-filter-toPatches.spec.ts
  e2e-pw/src/oss/specs/sidebar/sidebar-cifar.spec.ts
  fiftyone/server/mutation.py
  fiftyone/server/view.py
  tests/unittests/server_tests.py
Labels: bug, testing

#3689 [Proposal] Remove unused e2e
  e2e/.env.cypress.example
  e2e/.gitignore
  e2e/README.md
  e2e/cypress.config.ts
  e2e/cypress/e2e/3d/pointcloud-only-datasets.cy.ts
  e2e/cypress/e2e/datasets/quickstart-groups/quickstart-groups.cy.ts
  e2e/cypress/e2e/dynamic-groups/dynamic-groups.cy.ts
  e2e/cypress/fixtures/3d/pointcloud-only-datasets - before.cy.py
  e2e/cypress/fixtures/3d/resources/cone.pcd
  e2e/cypress/fixtures/dynamic-groups/dynamic-groups.cy.py
  e2e/cypress/fixtures/quickstart-groups/quickstart-groups - before.cy.py
  e2e/cypress/snapshots/base/3d/pointcloud-only-datasets.cy.ts/pcd-only-looker-modal-open.png
  e2e/cypress/support/commands.ts
  e2e/cypress/support/e2e.ts
  e2e/cypress/support/tasks.ts
  e2e/cypress/support/utils.ts
  e2e/index.ts
  e2e/lib/constants.ts
  e2e/lib/python-runner.ts
  e2e/package.json
  e2e/readme-assets/basic-arch.png
  e2e/readme-assets/basic-arch.svg
  e2e/tsconfig.json
  e2e/types/cypress.d.ts
  e2e/yarn.lock
Labels: cleaning, low priority

#3710 Fix App on develop
  app/packages/app/src/Sync.tsx
  app/packages/app/src/index.tsx
Labels: app

#3707 Bump sphinx to 3.5.4
  requirements/docs.txt
Labels: bug, documentation, cleaning

#3714 bugfix: last used brain key should be loaded by default in similarity sort
  app/packages/app/src/pages/datasets/DatasetPage.tsx
  app/packages/app/src/pages/datasets/__generated__/DatasetPageQuery.graphql.ts
  app/packages/core/src/components/Actions/similar/GroupButton.tsx
  app/packages/core/src/components/Actions/similar/Similar.tsx
  app/packages/core/src/components/Actions/similar/utils.ts
  app/packages/relay/src/fragments/__generated__/datasetFragment.graphql.ts
  app/packages/relay/src/fragments/datasetFragment.ts
  app/packages/relay/src/queries/__generated__/datasetQuery.graphql.ts
  app/packages/state/src/recoil/selectors.ts
  app/packages/state/src/recoil/types.ts
  app/packages/state/src/recoil/utils.ts
  app/schema.graphql
  fiftyone/server/query.py
Labels: bug

#3712 Docs cleanup
  docs/source/images/datasets-hero.png
  docs/source/release-notes.rst
  docs/source/user_guide/basics.rst
Labels: documentation, cleaning

#3722 Media fields fix
  app/packages/app/src/pages/datasets/__generated__/DatasetPageQuery.graphql.ts
  app/packages/relay/src/fragments/__generated__/mediaFieldsFragment.graphql.ts
  app/packages/relay/src/fragments/mediaFieldsFragment.ts
  app/packages/relay/src/graphQLSyncFragmentAtom.ts
  app/packages/relay/src/queries/__generated__/datasetQuery.graphql.ts
  app/packages/state/src/recoil/index.ts
  app/packages/state/src/recoil/mediaFields.ts
  app/packages/state/src/recoil/selectors.ts
  e2e-pw/src/oss/specs/selection.spec.ts
Labels: bug, app

#3733 Optimize use_view() usage
  fiftyone/core/stages.py
  fiftyone/server/routes/embeddings.py
Labels: enhancement

#3739 Fix active field on view change
  app/packages/state/src/recoil/schema.ts
Labels: bug, enhancement, app
