Repository voxel51/fiftyone, pull requests merged in 2023-02, with the labels that each got.

#2597 Add support for CVAT v2.4
  fiftyone/utils/cvat.py
  tests/intensive/cvat_tests.py
Labels: bug, annotation

#2590 Restrict dacite
  setup.py
Labels: bug

#2605 Adding support for importing/exporting generic media
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/types/dataset_types.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/data/parsers.py
  tests/unittests/import_export_tests.py
Labels: feature

#2608 Handling manual unwinds in aggregations
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  tests/unittests/aggregation_tests.py
Labels: bug

#2606 Add support filtering by dynamic properties in keypoints
  app/packages/core/src/components/Filters/categoricalFilter/Wrapper.tsx
  app/packages/core/src/components/Filters/categoricalFilter/filterOption/FilterOption.tsx
  app/packages/looker/src/overlays/keypoint.ts
  app/packages/state/src/recoil/pathFilters/boolean.ts
  app/packages/state/src/recoil/pathFilters/index.ts
  app/packages/state/src/recoil/skeletonFilter.ts
  fiftyone/server/view.py
Labels: app

#2624 Ensure viewCls for state proxy
  app/packages/state/src/hooks/useSetView.ts
Labels: bug, app

#2614 Always use IDs in plots and brain results
  docs/source/user_guide/plots.rst
  fiftyone/core/collections.py
  fiftyone/core/plots/matplotlib.py
  fiftyone/core/plots/plotly.py
  fiftyone/core/plots/utils.py
  fiftyone/core/runs.py
  fiftyone/server/routes/embeddings.py
  tests/intensive/plot_tests.py
Labels: enhancement

#2617 Faceted aggregation bug fixes
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  tests/unittests/aggregation_tests.py
Labels: bug

#2628 Fix matching single label fields
  fiftyone/server/view.py
Labels: bug, app, server

#2623 fix plugins require fiftyone key
  fiftyone/server/routes/plugins.py
Labels: plugins

#2622 Relay invariant comment on scalar hydration
  app/packages/state/src/hooks/useUpdateSample.ts
  app/packages/state/src/recoil/groups.ts
Labels: documentation, standard

#2632 Fix pinned sample sidebar
  app/packages/state/src/recoil/groups.ts
Labels: bug, app

#2626 Store patch embeddings directly on label objects
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/models.py
  fiftyone/core/stages.py
  tests/intensive/model_tests.py
  tests/unittests/similarity_tests.py
Labels: enhancement

#2616 Add support for importing CSV datasets
  docs/source/user_guide/dataset_creation/datasets.rst
  docs/source/user_guide/export_datasets.rst
  fiftyone/types/dataset_types.py
  fiftyone/utils/csv.py
  requirements/test.txt
  tests/unittests/import_export_tests.py
Labels: feature

#2631 Select slice when pinning
  app/packages/core/src/components/Actions/ActionsRow.tsx
  app/packages/state/src/hooks/useSetView.ts
  app/packages/state/src/recoil/selectors.ts
Labels: bug

#2635 Include all group slices in media size stat
  fiftyone/core/dataset.py
Labels: bug

#2641 Fix Python client session initialization
  app/packages/core/src/components/Actions/Similar.tsx
  fiftyone/core/session/events.py
  fiftyone/core/state.py
Labels: bug

#2642 Ensure notebook context and screenshots
  app/packages/app/vite.config.ts
  app/packages/state/src/hooks/useScreenshot.ts
  app/packages/state/src/hooks/useTo.ts
Labels: bug, app, notebook

#2583 v0.19 release notes
  app/packages/components/src/components/Icons/Icons.tsx
  app/packages/core/src/components/FieldLabelAndInfo/index.tsx
  app/packages/core/src/components/Setup.tsx
  app/packages/core/src/components/ViewBar/ViewBar.tsx
  app/packages/core/src/components/ViewBar/ViewStage/ViewStage.tsx
  app/packages/core/src/utils/links.ts
  app/packages/desktop/src/menu.ts
  app/packages/embeddings/src/Embeddings.tsx
  app/packages/looker/src/elements/common/error.ts
  app/packages/map/src/Map.tsx
  app/packages/map/src/Options.tsx
  docs/source/cheat_sheets/index.rst
  docs/source/conf.py
  docs/source/environments/index.rst
  docs/source/getting_started/install.rst
  docs/source/recipes/index.rst
  docs/source/release-notes.rst
  docs/source/teams/index.rst
  docs/source/teams/overview.rst
  docs/source/tutorials/index.rst
  docs/source/user_guide/dataset_zoo/datasets.rst
  docs/source/user_guide/index.rst
  fiftyone/core/odm/database.py
  fiftyone/core/odm/utils.py
  fiftyone/core/plots/manager.py
  fiftyone/core/plots/plotly.py
  fiftyone/core/session/session.py
  fiftyone/core/utils.py
  fiftyone/core/video.py
  fiftyone/migrations/runner.py
  fiftyone/utils/activitynet.py
  fiftyone/utils/quickstart.py
  fiftyone/zoo/datasets/tf.py
  fiftyone/zoo/datasets/torch.py
  fiftyone/zoo/models/__init__.py
  package/desktop/setup.py
  setup.py
Labels: documentation

#2659 Export getCurrentEnvironment from state package
  app/packages/state/src/hooks/index.ts
Labels: cleaning, app

#2647 Release v0.19.1
  .github/workflows/publish.yml
  app/packages/app/vite.config.ts
  docs/source/release-notes.rst
  fiftyone/core/session/notebooks.py
  fiftyone/server/query.py
  setup.py
Labels: release

#2676 from_dict wrapper for server dataclasses
  fiftyone/server/aggregations.py
  fiftyone/server/dataloader.py
  fiftyone/server/paginator.py
  fiftyone/server/query.py
  fiftyone/server/samples.py
  fiftyone/server/utils.py
Labels: bug

#2683 Skipping downward migrations for future-but-compatible versions
  fiftyone/migrations/runner.py
Labels: enhancement

#2678 Fix docstring for Dataset.from_dir()
  fiftyone/core/dataset.py
Labels: documentation

#2685 Adding tensorflow-macos requirement option
  fiftyone/zoo/models/manifest-tf.json
Labels: enhancement

#2686 Add support for negative integer mask targets
  fiftyone/core/fields.py
Labels: bug

#2687 Documenting on-the-fly custom embedded document creation
  docs/source/user_guide/using_datasets.rst
  fiftyone/__public__.py
  fiftyone/core/odm/mixins.py
  tests/unittests/dataset_tests.py
Labels: documentation
