Repository voxel51/fiftyone, pull requests merged in 2023-01, with the labels that each got.

#2471 Separate method for clearing a dataset's run cache
  fiftyone/core/dataset.py
Labels: feature

#2491 Fix CVAT bug when checking if a project exists
  fiftyone/utils/cvat.py
  tests/intensive/cvat_tests.py
Labels: bug, annotation

#2474 Update KITTI datasets to not use legacy 3D visualizer settings
  app/packages/looker-3d/src/Looker3d.tsx
  docs/source/images/groups/toy-point-cloud.png
  docs/source/user_guide/groups.rst
  fiftyone/migrations/revisions/v0_19_0.py
  fiftyone/utils/kitti.py
  fiftyone/zoo/datasets/__init__.py
  fiftyone/zoo/datasets/base.py
Labels: enhancement

#2483 add support for rgb overlays
  .gitignore
  app/packages/core/src/__generated__/DatasetQuery.graphql.ts
  app/packages/core/src/components/Modal/TooltipInfo.tsx
  app/packages/looker/src/index.ts
  app/packages/looker/src/numpy.ts
  app/packages/looker/src/overlays/detection.ts
  app/packages/looker/src/overlays/heatmap.ts
  app/packages/looker/src/overlays/segmentation.ts
  app/packages/looker/src/overlays/util.ts
  app/packages/looker/src/state.ts
  app/packages/looker/src/worker.ts
  app/packages/relay/src/mutations/__generated__/setViewMutation.graphql.ts
  app/packages/state/src/recoil/selectors.ts
  app/packages/state/src/utils.ts
  app/packages/utilities/src/color.ts
  app/packages/utilities/src/index.ts
  app/schema.graphql
  docs/source/user_guide/evaluation.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/fields.py
  fiftyone/core/labels.py
  fiftyone/core/odm/dataset.py
  fiftyone/server/query.py
  fiftyone/utils/eval/segmentation.py
  fiftyone/utils/labels.py
  install.bash
  tests/unittests/dataset_tests.py
  tests/unittests/evaluation_tests.py
Labels: feature

#2498 Documenting label conversion utils
  docs/source/user_guide/using_datasets.rst
Labels: documentation

#2499 Cleaning for SSR environments
  app/packages/app/package.json
  app/packages/components/package.json
  app/packages/core/package.json
  app/packages/core/src/components/Setup.tsx
  app/packages/core/src/components/ViewBar/ViewStage/ErrorMessage.tsx
  app/packages/dataset/index.html
  app/packages/dataset/package.json
  app/packages/dataset/src/Dataset.tsx
  app/packages/dataset/src/index.tsx
  app/packages/dataset/vite.config.ts
  app/packages/looker-3d/src/Looker3dPlugin.tsx
  app/packages/looker/package.json
  app/packages/looker/src/elements/base.ts
  app/packages/looker/src/elements/common/controls.ts
  app/packages/looker/src/elements/common/thumbnail.ts
  app/packages/looker/src/elements/util.ts
  app/packages/looker/src/icons/index.ts
  app/packages/looker/src/util.ts
  app/packages/looker/src/worker.ts
  app/packages/plugins/src/index.ts
  app/packages/relay/src/mutations/setDataset.ts
  app/packages/relay/src/mutations/setGroupSlice.ts
  app/packages/relay/src/mutations/setSelected.ts
  app/packages/relay/src/mutations/setSelectedLabels.ts
  app/packages/relay/src/mutations/setSidebarGroups.ts
  app/packages/relay/src/mutations/setView.ts
  app/packages/relay/src/queries/aggregations.ts
  app/packages/relay/src/queries/config.ts
  app/packages/relay/src/queries/countValues.ts
  app/packages/relay/src/queries/histogramValues.ts
  app/packages/relay/src/queries/mainSample.ts
  app/packages/relay/src/queries/paginateGroup.ts
  app/packages/relay/src/queries/pinnedSample.ts
  app/packages/relay/src/resolve.ts
  app/packages/state/package.json
  app/packages/state/src/hooks/index.ts
  app/packages/state/src/recoil/groups.ts
  app/packages/state/src/routing/RouterContext.ts
  app/packages/state/vite.config.ts
  app/packages/utilities/src/fetch.ts
  app/packages/utilities/src/index.ts
  app/yarn.lock
Labels: cleaning

#2513 Adding support for declaring dynamic fields on generated views via set_values()
  fiftyone/core/clips.py
  fiftyone/core/dataset.py
  fiftyone/core/patches.py
  fiftyone/core/video.py
  tests/unittests/patches_tests.py
  tests/unittests/video_tests.py
Labels: bug

#2397 Fix databricks integration
  app/packages/app/src/index.tsx
  app/packages/app/vite.config.ts
  app/packages/state/src/hooks/useScreenshot.ts
  app/packages/state/src/recoil/distributions.ts
  app/packages/utilities/src/fetch.ts
  fiftyone/core/context.py
  fiftyone/core/session/events.py
  fiftyone/core/session/notebooks.py
  fiftyone/core/session/session.py
  fiftyone/core/session/templates.py
  fiftyone/server/app.py
  fiftyone/server/events.py
  fiftyone/server/main.py
  fiftyone/server/routes/__init__.py
  fiftyone/server/routes/screenshot.py
Labels: app, notebook

#2466 filter | match toggle updates
  app/packages/components/src/components/Tooltip/Tooltip.tsx
  app/packages/core/src/components/Filters/BooleanFieldFilter.tsx
  app/packages/core/src/components/Filters/Exclude.tsx
  app/packages/core/src/components/Filters/NumericFieldFilter.tsx
  app/packages/core/src/components/Filters/StringFieldFilter.tsx
  app/packages/core/src/components/Filters/categoricalFilter/CategoricalFilter.tsx
  app/packages/core/src/components/Filters/categoricalFilter/ResultComponent.tsx
  app/packages/core/src/components/Filters/categoricalFilter/Wrapper.tsx
  app/packages/core/src/components/Filters/categoricalFilter/filterOption/FilterItem.tsx
  app/packages/core/src/components/Filters/categoricalFilter/filterOption/FilterOption.tsx
  app/packages/core/src/components/Filters/utils.ts
  app/packages/looker/src/elements/common/tags.ts
  app/packages/state/src/recoil/aggregations.ts
  app/packages/state/src/recoil/atoms.ts
  app/packages/state/src/recoil/pathFilters/boolean.ts
  app/packages/state/src/recoil/pathFilters/numeric.ts
  app/packages/state/src/recoil/pathFilters/string.ts
  app/packages/state/tests/recoil/filters.test.ts
  fiftyone/server/samples.py
  fiftyone/server/view.py
  tests/unittests/server_tests.py
Labels: app

#2537 Maintain Starlette route list
  fiftyone/server/app.py
  fiftyone/server/routes/__init__.py
  fiftyone/server/routes/embeddings.py
Labels: cleaning

#2538 Remove stray print
  fiftyone/server/events.py
Labels: cleaning

#2543 Updating docs links
  docs/source/_templates/layout.html
  docs/source/conf.py
  docs/source/environments/index.rst
Labels: documentation, cleaning

#2550 Cleaning for builds
  app/packages/core/src/components/ViewBar/ViewStage/ErrorMessage.tsx
  app/packages/embeddings/src/Embeddings.tsx
  app/packages/looker/src/lookers/abstract.ts
  app/packages/state/src/recoil/view.ts
Labels: cleaning

#2549 Throw GraphQL errors correctly
  app/packages/state/src/routing/RouterContext.ts
Labels: bug

#2528 Adding support for loading specific group slices
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/view.py
  tests/unittests/group_tests.py
Labels: feature

#2562 Documenting Spaces!
  docs/source/_includes/substitutions.rst
  docs/source/images/app/app-embeddings-panel-controls.gif
  docs/source/images/app/app-embeddings-panel.gif
  docs/source/images/app/app-histograms-panel.gif
  docs/source/images/app/app-map-controls.gif
  docs/source/images/app/app-map-panel-controls.gif
  docs/source/images/app/app-map-panel-selection.gif
  docs/source/images/app/app-map-panel.gif
  docs/source/images/app/app-map-selection.gif
  docs/source/images/app/app-map.gif
  docs/source/images/app/app-samples-panel.gif
  docs/source/images/app/app-spaces-hero.png
  docs/source/images/app/app-spaces-layout1.gif
  docs/source/images/app/app-spaces-layout2.gif
  docs/source/images/app/app-spaces-layout3.gif
  docs/source/images/app/app-stats.gif
  docs/source/plugins/index.rst
  docs/source/release-notes.rst
  docs/source/user_guide/app.rst
  docs/source/user_guide/config.rst
  fiftyone/core/odm/dataset.py
Labels: documentation

#2570 Adding native support for text prompts
  fiftyone/core/collections.py
  fiftyone/core/stages.py
  fiftyone/server/query.py
Labels: feature

#2568 Publish syntax fixes
  .github/workflows/build.yml
  .github/workflows/publish.yml
Labels: bug, ci
