Repository voxel51/fiftyone, pull requests merged in 2023-09, with the labels that each got.

#3479 Fix modal popout widths
  app/packages/core/src/components/Actions/ActionsRow.tsx
  app/packages/core/src/components/Actions/DynamicGroup.tsx
  app/packages/core/src/components/Actions/GroupMediaVisibilityContainer.tsx
  app/packages/core/src/components/Actions/Options.tsx
  app/packages/core/src/components/Actions/Patcher.tsx
  app/packages/core/src/components/Actions/Popout.tsx
  app/packages/core/src/components/Actions/Selected.tsx
  app/packages/core/src/components/Actions/Tagger.tsx
  app/packages/core/src/components/Actions/similar/Similar.tsx
Labels: bug

#3470 Fix dynamic grouping for disjoint group datasets
  app/packages/components/src/components/Selector/Selector.tsx
  app/packages/core/src/components/Actions/DynamicGroup.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/NestedGroup/GroupElementsLinkBar.tsx
  app/packages/relay/src/queries/__generated__/aggregationsQuery.graphql.ts
  app/packages/state/src/recoil/aggregations.ts
  app/schema.graphql
  e2e-pw/src/oss/fixtures/loader.ts
  e2e-pw/src/oss/poms/action-row/dynamic-group.ts
  e2e-pw/src/oss/poms/action-row/grid-actions-row.ts
  e2e-pw/src/oss/poms/grid/index.ts
  e2e-pw/src/oss/poms/modal/dynamic-group-pagination-bar.ts
  e2e-pw/src/oss/poms/modal/group-actions.ts
  e2e-pw/src/oss/poms/modal/modal-sidebar.ts
  e2e-pw/src/oss/poms/selector.ts
  e2e-pw/src/oss/specs/groups/sparse-dynamic-groups.spec.ts
  e2e-pw/src/oss/specs/plugins/histograms.spec.ts
  e2e-pw/src/oss/specs/smoke-tests/quickstart.spec.ts
  fiftyone/server/aggregations.py
Labels: bug, app

#3492 Adding support for listing datasets with tags
  docs/source/cli/index.rst
  fiftyone/core/cli.py
  fiftyone/core/dataset.py
Labels: feature

#3167 [DOCS] add poetry installation instructions for Teams SDK
  docs/source/teams/installation.rst
Labels: documentation

#3528 Optimize list datasets info
  fiftyone/core/cli.py
  fiftyone/core/dataset.py
Labels: enhancement

#3515 Compound group-by and better index creation control
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
  tests/isolated/service_tests.py
  tests/unittests/group_tests.py
  tests/unittests/view_tests.py
Labels: bug, enhancement

#3531 Fix warning text of image similarity
  app/packages/core/src/components/Actions/ActionsRow.tsx
  app/packages/core/src/components/Actions/similar/Helper.tsx
  app/packages/core/src/components/Actions/similar/Similar.tsx
  app/packages/state/src/hooks/index.ts
  app/packages/state/src/hooks/similaritySearch/useSimilarity.test.tsx
  app/packages/state/src/hooks/similaritySearch/useSimilarityType.ts
Labels: bug, testing

#3519 Always log stack traces in server
  fiftyone/server/app.py
Labels: enhancement, server

#3556 [Proposal] Add lint step to e2e
  .github/workflows/e2e.yml
  e2e-pw/src/oss/poms/field-visibility/field-visibility.ts
  e2e-pw/src/oss/specs/display-options/display-options.spec.ts
  e2e-pw/src/oss/specs/smoke-tests/embeddings.spec.ts
  e2e-pw/src/oss/specs/smoke-tests/quickstart-groups.spec.ts
  e2e-pw/src/oss/specs/smoke-tests/tagger.spec.ts
Labels: cleaning, ci

#3559 Only process instance masks with width and height
  app/packages/looker/src/overlays/detection.ts
Labels: bug, app

#3527 Codecov cleanup
  codecov.yml
Labels: cleaning

#3561 Docs updates
  docs/source/_static/css/custom.css
  docs/source/cheat_sheets/fiftyone_terminology.rst
  docs/source/images/plugins/file-explorer.gif
  docs/source/images/plugins/hello-world.gif
  docs/source/images/plugins/operator-browser.gif
  docs/source/images/plugins/operators/examples/annotation.gif
  docs/source/images/plugins/operators/examples/embeddings.gif
  docs/source/images/plugins/operators/examples/evaluation.gif
  docs/source/images/plugins/operators/examples/import.gif
  docs/source/images/plugins/plugin-design.png
  docs/source/images/teams/secrets_page.png
  docs/source/plugins/developing_plugins.rst
  docs/source/plugins/index.rst
  docs/source/plugins/using_plugins.rst
  docs/source/release-notes.rst
  docs/source/teams/dataset_versioning.rst
  docs/source/teams/index.rst
  docs/source/teams/secrets.rst
  docs/source/teams/teams_plugins.rst
  docs/source/user_guide/app.rst
  docs/source/user_guide/config.rst
  fiftyone/core/cli.py
  fiftyone/operators/executor.py
Labels: documentation

#3520 [Proposal] Require e2e in PR and Publish workflows
  .github/workflows/pr.yml
  .github/workflows/publish.yml
Labels: testing

#3374 Color scheme e2e test
  app/packages/core/src/components/ColorModal/ColorModal.tsx
  app/packages/core/src/components/ColorModal/FieldSetting.tsx
  app/packages/core/src/components/ColorModal/GlobalSetting.tsx
  app/packages/core/src/components/ColorModal/JSONViewer.tsx
  app/packages/core/src/components/ColorModal/SidebarList.tsx
  app/packages/core/src/components/ColorModal/colorPalette/AttributeColorSetting.tsx
  app/packages/core/src/components/ColorModal/colorPalette/ColorPalette.tsx
  app/packages/core/src/components/ColorModal/controls/ColorAttribute.tsx
  app/packages/core/src/components/ColorModal/controls/ModeControl.tsx
  app/packages/core/src/components/ColorModal/controls/RefreshColor.tsx
  app/packages/core/src/components/Common/Input.tsx
  app/packages/core/src/components/Common/RadioGroup.tsx
  e2e-pw/src/oss/poms/color-modal/index.ts
  e2e-pw/src/oss/poms/grid/index.ts
  e2e-pw/src/oss/specs/color-scheme/color-scheme.spec.ts
  e2e-pw/src/oss/specs/color-scheme/color-scheme.spec.ts-snapshots/change-color-palette-chromium-darwin.png
  e2e-pw/src/oss/specs/color-scheme/color-scheme.spec.ts-snapshots/change-color-palette-chromium-linux.png
  e2e-pw/src/oss/specs/color-scheme/color-scheme.spec.ts-snapshots/change-color-palette-json-editor-chromium-darwin.png
  e2e-pw/src/oss/specs/color-scheme/color-scheme.spec.ts-snapshots/change-color-palette-json-editor-chromium-linux.png
  e2e-pw/src/oss/specs/color-scheme/color-scheme.spec.ts-snapshots/color-pool-1-chromium-darwin.png
  e2e-pw/src/oss/specs/color-scheme/color-scheme.spec.ts-snapshots/color-pool-1-chromium-linux.png
  e2e-pw/src/oss/specs/color-scheme/color-scheme.spec.ts-snapshots/color-value-setting-1-chromium-darwin.png
  e2e-pw/src/oss/specs/color-scheme/color-scheme.spec.ts-snapshots/color-value-setting-1-chromium-linux.png
  e2e-pw/src/oss/specs/color-scheme/color-scheme.spec.ts-snapshots/color-value-setting-2-chromium-darwin.png
  e2e-pw/src/oss/specs/color-scheme/color-scheme.spec.ts-snapshots/color-value-setting-2-chromium-linux.png
Labels: testing

#3567 Update Playwright .env.dev.template
  e2e-pw/.env.dev.template
Labels: cleaning, testing

#3578 Fix docs typo
  docs/source/teams/teams_plugins.rst
Labels: documentation

#3582 Adding a delete_frame() method
  fiftyone/core/frame.py
Labels: enhancement

#3581 Gracefully handle runs that are already migrated when importing data in FiftyOneDataset format
  fiftyone/migrations/revisions/v0_19_0.py
Labels: bug
