Repository voxel51/fiftyone, pull requests merged in 2024-12, with the labels that each got.

#5200 Fix grid caching
  app/packages/core/src/components/Grid/Grid.tsx
  app/packages/core/src/components/Grid/useRefreshers.ts
  app/packages/core/src/components/Grid/useSelect.ts
  app/packages/spotlight/src/row.ts
  app/packages/spotlight/src/section.ts
  app/packages/spotlight/src/types.ts
Labels: bug, app

#5169 labels rendering performance improvement: create ImageBitmaps in worker
  app/packages/looker/src/lookers/abstract.ts
  app/packages/looker/src/lookers/frame-reader.ts
  app/packages/looker/src/overlays/base.ts
  app/packages/looker/src/overlays/detection.ts
  app/packages/looker/src/overlays/heatmap.ts
  app/packages/looker/src/overlays/segmentation.ts
  app/packages/looker/src/worker/decorated-fetch.test.ts
  app/packages/looker/src/worker/decorated-fetch.ts
  app/packages/looker/src/worker/deserializer.ts
  app/packages/looker/src/worker/disk-overlay-decoder.test.ts
  app/packages/looker/src/worker/disk-overlay-decoder.ts
  app/packages/looker/src/worker/index.ts
  app/packages/looker/src/worker/pooled-fetch.test.ts
  app/packages/looker/src/worker/pooled-fetch.ts
  app/packages/looker/src/worker/shared.ts
Labels: app

#5217 bump release date
  docs/source/release-notes.rst
Labels: documentation

#5225 Cherry-picking #5224 for release
  docs/scripts/make_model_zoo_docs.py
Labels: documentation

#5267 Fixing #5254
  app/packages/core/src/plugins/SchemaIO/components/NativeModelEvaluationView/Evaluation.tsx
  fiftyone/operators/builtins/panels/model_evaluation/__init__.py
Labels: bug

#5280 Do not collapse valid list field filters
  app/packages/state/src/recoil/sidebar.test.ts
  app/packages/state/src/recoil/sidebar.ts
Labels: app

#5286 Add extended selection to counts
  app/packages/state/src/recoil/filters.ts
Labels: bug, annotation

#5273 Similarity race condition patch
  fiftyone/utils/torch.py
Labels: bug

#5294 fix png decoding
  app/packages/looker/src/worker/canvas-decoder.test.ts
  app/packages/looker/src/worker/canvas-decoder.ts
  app/packages/looker/src/worker/painter.ts
Labels: app

#5293 Reset to initial buffers in video looker
  app/packages/looker/src/elements/video.ts
  app/packages/looker/src/lookers/video.ts
  e2e-pw/src/oss/specs/grid-tagging.spec.ts
Labels: bug, app

#5287 Fix cached looker font sizes
  app/packages/core/src/components/Grid/Grid.tsx
  app/packages/core/src/components/ImageContainerHeader.tsx
  app/packages/looker/src/lookers/abstract.ts
Labels: bug, app

#5298 remove erroneous base url extraction
  app/packages/looker/src/worker/disk-overlay-decoder.ts
Labels: app

#5307 Release notes
  docs/source/release-notes.rst
  docs/source/teams/data_lens.rst
Labels: documentation

#5226 List hf hub datasets
  fiftyone/utils/huggingface.py
Labels: enhancement

#5324 Handle tree paths in GitHub identifiers
  fiftyone/plugins/core.py
  fiftyone/plugins/utils.py
  fiftyone/utils/github.py
Labels: bug

#5320 Adds index usage info to `get_index_information(include_stats=True)`
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  tests/unittests/dataset_tests.py
Labels: feature
