Repository voxel51/fiftyone, pull requests merged in 2024-06, with the labels that each got.

#4449 Upgrade `jest`, `vite` and `vitest`
  app/package.json
  app/packages/aggregations/package.json
  app/packages/app/package.json
  app/packages/components/package.json
  app/packages/core/package.json
  app/packages/embeddings/package.json
  app/packages/flashlight/package.json
  app/packages/looker-3d/package.json
  app/packages/looker/package.json
  app/packages/map/package.json
  app/packages/operators/package.json
  app/packages/plugins/package.json
  app/packages/relay/package.json
  app/packages/spaces/package.json
  app/packages/state/package.json
  app/packages/state/src/hooks/useGroupEntries.test.tsx
  app/packages/utilities/package.json
  app/yarn.lock
Labels: dependencies

#4442 3D Scene I/O optimization and bugfixes
  docs/source/teams/cloud_media.rst
  fiftyone/core/metadata.py
  fiftyone/core/storage.py
  fiftyone/core/threed/object_3d.py
  fiftyone/core/threed/scene_3d.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/utils3d.py
  tests/unittests/metadata_tests.py
  tests/unittests/threed/scene_3d_tests.py
  tests/unittests/utils3d_tests.py
Labels: bug

#4456 Teams 1.7.1/OSS 0.24.1 release notes
  docs/source/plugins/index.rst
  docs/source/release-notes.rst
  docs/source/user_guide/config.rst
Labels: documentation

#4469 Refetch saved views on dataset change
  app/packages/core/src/components/Sidebar/ViewSelection/index.tsx
  fiftyone/server/events/initialize.py
  fiftyone/server/mutation.py
Labels: bug, app

#4472 Fix copy_files()
  fiftyone/core/storage.py
Labels: bug

#4479 Fix dynamic group player for group datasets
  app/packages/state/src/hooks/useCreateLooker.ts
  app/packages/state/src/recoil/dynamicGroups.test.ts
  app/packages/state/src/recoil/dynamicGroups.ts
Labels: bug, app

#4497 Use `textContent` in `@fiftyone/looker`
  app/packages/looker/src/elements/common/error.ts
  app/packages/looker/src/elements/common/tags.test.ts
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/elements/common/util.ts
  app/packages/looker/src/elements/frame.ts
  app/packages/looker/src/elements/imavid/frame-count.ts
  app/packages/looker/src/elements/imavid/play-button.ts
  app/packages/looker/src/elements/video.ts
Labels: app

#4492 Don't mutate expressions passed to to_clips() in-place
  fiftyone/core/clips.py
  tests/unittests/view_tests.py
Labels: bug

#4527 make dynamic groups work for fo3d files
  app/packages/state/src/recoil/groups.ts
Labels: bug, app
