Repository voxel51/fiftyone, pull requests merged in 2024-05, with the labels that each got.

#4319 Allow sidebar changes during lightning loading state
  app/__mocks__/recoil.ts
  app/packages/state/src/recoil/filters.test.ts
  app/packages/state/src/recoil/filters.ts
  app/packages/state/src/recoil/sidebarExpanded.ts
Labels: bug, app

#4351 Gracefully handle None-valued tag fields
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  tests/unittests/view_tests.py
Labels: bug

#4352 Adding in-App workspaces docs
  docs/source/images/app/app-load-workspace.gif
  docs/source/images/app/app-save-workspace.gif
  docs/source/images/app/app-update-workspace.gif
  docs/source/user_guide/app.rst
Labels: documentation

#4346 Fix temporal detections filtering
  app/packages/looker/src/overlays/classifications.test.ts
  app/packages/looker/src/overlays/classifications.ts
Labels: bug, app

#4345 Fix overlay processing for empty label lists
  app/packages/looker/src/overlays/index.test.ts
  app/packages/looker/src/overlays/index.ts
Labels: bug, app

#4372 DeepSort tracking enhancements
  fiftyone/utils/tracking/deepsort.py
Labels: enhancement

#4324 Fix compute visualization results from operators
  fiftyone/server/decorators.py
  tests/unittests/server_decorators_tests.py
Labels: bug, server

#4347 Add state processing to the refresh event
  app/packages/app/src/useEvents/useRefresh.ts
Labels: enhancement, app

#4400 Minor fix in documentation related to groups
  docs/source/teams/roles_and_permissions.rst
Labels: documentation

#4392 Support loading annotations for large CVAT tasks with many jobs
  fiftyone/utils/cvat.py
  tests/intensive/cvat_tests.py
Labels: annotation

#4379 Add new permission flags for tagging, changing sidebar groups, creating new field for similarity search
  app/packages/app/src/useWriters/registerWriter.ts
  app/packages/core/src/components/Actions/ActionsRow.tsx
  app/packages/core/src/components/Actions/similar/Similar.tsx
  app/packages/core/src/components/ColorModal/ColorFooter.tsx
  app/packages/core/src/components/Sidebar/Entries/AddGroupEntry.tsx
  app/packages/core/src/components/Sidebar/Entries/Draggable.tsx
  app/packages/core/src/components/Sidebar/Entries/GroupEntries.tsx
  app/packages/core/src/components/Sidebar/ViewSelection/index.tsx
  app/packages/spaces/src/components/Workspaces/Workspace.tsx
  app/packages/spaces/src/components/Workspaces/hooks.ts
  app/packages/spaces/src/components/Workspaces/index.tsx
  app/packages/state/src/recoil/atoms.ts
  app/packages/state/src/session.ts
Labels: app

#4405 [Proposal] Automatic PRs into `develop`
  .github/workflows/push-release.yml
Labels: ci

#4417 Fixing log syntax in set_progress()
  fiftyone/operators/executor.py
Labels: bug

#4429 Fix YOLO-NAS inference
  fiftyone/utils/super_gradients.py
Labels: bug

#4386 Teams integration
  .github/workflows/pr.yml
  .github/workflows/push-release.yml
Labels: ci

#4444 Fixing anomaly detection tutorial title level
  docs/source/tutorials/anomaly_detection.ipynb
Labels: documentation
