Repository voxel51/fiftyone, pull requests merged in 2024-01, with the labels that each got.

#3976 fix url construction
  app/packages/utilities/src/fetch.ts
Labels: bug

#3966 Use mixed mode in select_group_slices
  fiftyone/server/mutation.py
  fiftyone/server/view.py
Labels: bug

#3958 Fix sort by similarity for datasets with a color scheme
  fiftyone/server/routes/sort.py
Labels: bug, app

#3978 Add support for configuring whether run cleanup happens
  fiftyone/core/collections.py
  fiftyone/core/runs.py
Labels: enhancement

#4002 Fix schema bugs with embedded document fields
  fiftyone/core/document.py
  fiftyone/core/odm/document.py
  fiftyone/core/validation.py
  tests/unittests/evaluation_tests.py
  tests/unittests/operators/decorators_tests.py
Labels: bug

#3997 Fix embedded patches fields in the App
  app/packages/looker/src/overlays/index.ts
  app/packages/looker/src/util.ts
  app/packages/looker/src/zoom.ts
  fiftyone/core/patches.py
Labels: bug, app, core

#3979 Add support for customizing progress bar rendering at method level
  docs/source/plugins/developing_plugins.rst
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/metadata.py
  fiftyone/core/models.py
  fiftyone/core/odm/database.py
  fiftyone/core/storage.py
  fiftyone/core/utils.py
  fiftyone/core/view.py
  fiftyone/operators/__init__.py
  fiftyone/operators/utils.py
  fiftyone/utils/annotations.py
  fiftyone/utils/coco.py
  fiftyone/utils/csv.py
  fiftyone/utils/cvat.py
  fiftyone/utils/data/exporters.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/data/parsers.py
  fiftyone/utils/eval/activitynet.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/openimages.py
  fiftyone/utils/eval/regression.py
  fiftyone/utils/eval/segmentation.py
  fiftyone/utils/geojson.py
  fiftyone/utils/image.py
  fiftyone/utils/iou.py
  fiftyone/utils/labelbox.py
  fiftyone/utils/labels.py
  fiftyone/utils/scale.py
  fiftyone/utils/utils3d.py
  fiftyone/utils/video.py
  fiftyone/zoo/datasets/__init__.py
  tests/unittests/utils_tests.py
Labels: enhancement

#3982 Disable Modal shortcuts for alt/ctrl/meta
  app/packages/core/src/components/Modal/ModalNavigation.tsx
  e2e-pw/src/oss/poms/modal/index.ts
  e2e-pw/src/oss/poms/modal/modal-sidebar.ts
  e2e-pw/src/oss/specs/smoke-tests/quickstart.spec.ts
Labels: bug, app

#3981 Fix sorting by similarity with MongoDB backend
  fiftyone/server/view.py
Labels: bug, app

#3941 Lightning bug fixes
  app/packages/components/src/components/Selector/Selector.tsx
  app/packages/components/src/components/Selector/index.ts
  app/packages/components/src/components/index.ts
  app/packages/core/src/components/Actions/Options.tsx
  app/packages/core/src/components/Filters/StringFilter/StringFilter.tsx
  app/packages/core/src/components/Filters/StringFilter/useOnSelect.ts
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry/Arrow.tsx
  app/packages/core/src/components/ViewBar/ViewStage/utils.ts
  app/packages/core/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts
  app/packages/state/src/recoil/lightning.ts
  app/packages/utilities/src/type-check.ts
  e2e-pw/src/oss/poms/action-row/display-options.ts
  e2e-pw/src/oss/poms/sidebar.ts
  e2e-pw/src/oss/specs/sidebar/lightning.spec.ts
Labels: bug, app

#3964 Group mode re-filtering of aggregations
  fiftyone/server/aggregate.py
  fiftyone/server/aggregations.py
  fiftyone/server/mutation.py
  fiftyone/server/view.py
  tests/unittests/server_aggregations_tests.py
Labels: bug, server

#4013 Fix App modal media field
  app/packages/app/src/pages/datasets/__generated__/DatasetPageQuery.graphql.ts
  app/packages/relay/src/fragments/__generated__/mediaFieldsFragment.graphql.ts
  app/packages/relay/src/fragments/mediaFieldsFragment.ts
  app/packages/relay/src/queries/__generated__/datasetQuery.graphql.ts
  app/packages/state/src/recoil/options.ts
Labels: bug, app

#4016 Include sample/frame singletons when clearing dataset cache
  fiftyone/core/dataset.py
  fiftyone/core/singletons.py
  tests/unittests/dataset_tests.py
Labels: enhancement

#4015 Add dynamic batching to bulk writes
  docs/source/user_guide/config.rst
  fiftyone/core/collections.py
  fiftyone/core/config.py
  fiftyone/core/dataset.py
  fiftyone/core/odm/database.py
  fiftyone/core/utils.py
  tests/unittests/utils_tests.py
Labels: feature

#4018 Fix similarity action k requirement
  app/packages/core/src/components/Actions/similar/Similar.tsx
Labels: bug, app

#4025 [`fiftyone-db`] Fix /etc/os-release files with empty lines
  package/db/setup.py
Labels: bug

#4038 Documenting visualization method customization
  docs/source/_includes/substitutions.rst
  docs/source/user_guide/brain.rst
Labels: documentation

#4039 Add support for passing kwargs directly when creating custom runs
  fiftyone/core/collections.py
  fiftyone/core/runs.py
  tests/unittests/run_tests.py
Labels: enhancement

#4041 Cherry-picking ML work for release
  docs/source/_includes/substitutions.rst
  docs/source/release-notes.rst
  docs/source/user_guide/brain.rst
  fiftyone/core/collections.py
  fiftyone/core/runs.py
  setup.py
  tests/unittests/run_tests.py
Labels: release

#4042 Release v0.23.4
  app/packages/plugins/src/index.ts
  docs/source/_includes/substitutions.rst
  docs/source/release-notes.rst
  docs/source/user_guide/brain.rst
  fiftyone/core/collections.py
  fiftyone/core/runs.py
  setup.py
  tests/unittests/run_tests.py
Labels: release
