Repository voxel51/fiftyone, pull requests merged in 2024-08, with the labels that each got.

#4575 Add test for frame view annotation
  tests/intensive/cvat_tests.py
Labels: testing, annotation

#4586 Update fiftyone-teams doc on roles and permissions
  docs/source/images/teams/admin_roles_page.png
  docs/source/images/teams/admin_team_users_page.png
  docs/source/images/teams/dataset_default_access.png
  docs/source/images/teams/dataset_specific_access.png
  docs/source/teams/roles_and_permissions.rst
Labels: documentation

#4614 Bugfix: support branches that contain slashes when downloading plugins
  fiftyone/plugins/utils.py
  fiftyone/utils/github.py
  tests/unittests/plugins/core_tests.py
  tests/unittests/plugins/secrets_tests.py
Labels: bug

#4623 Retain sample selection after modal pop history state
  app/packages/app/src/Sync.tsx
  e2e-pw/src/oss/specs/selection.spec.ts
Labels: bug, app

#4629 Remove padding grid fill
  app/packages/spotlight/src/index.ts
Labels: enhancement, app

#4618 Fix modal linking
  app/packages/app/src/useEventSource.ts
  app/packages/app/src/useEvents/useStateUpdate.ts
  app/packages/app/src/useEvents/utils.ts
  app/packages/app/src/useSetters/onSetDataset.ts
  app/packages/utilities/src/index.ts
  e2e-pw/src/oss/fixtures/loader.ts
  e2e-pw/src/oss/specs/groups/dynamic-groups.spec.ts
  e2e-pw/src/oss/specs/groups/sparse-dynamic-groups.spec.ts
  e2e-pw/src/oss/specs/modal/linking.spec.ts
  e2e-pw/src/oss/specs/regression-tests/grid-page.spec.ts
  e2e-pw/src/oss/specs/smoke-tests/quickstart-groups-dynamic.spec.ts
  e2e-pw/src/shared/abstract-loader.ts
Labels: bug, app

#4621 Allow empty `paths` aggregation
  fiftyone/server/aggregations.py
  tests/unittests/server_aggregations_tests.py
Labels: bug, server

#4628 Scrollbar fixes
  app/packages/app/src/components/Setup.tsx
  app/packages/components/src/scrollable.module.css
  app/packages/core/src/components/Grid/Grid.module.css
  app/packages/core/src/components/Grid/Grid.tsx
  app/packages/core/src/components/Histogram.tsx
  app/packages/core/src/components/Sidebar/Sidebar.module.css
  app/packages/core/src/components/Sidebar/Sidebar.tsx
  app/packages/core/src/plugins/SchemaIO/components/JSONView.tsx
  app/packages/flashlight/src/index.ts
  app/packages/flashlight/src/styles.module.css
  app/packages/spotlight/package.json
  app/packages/spotlight/src/styles.module.css
  app/packages/spotlight/tsconfig.json
  app/packages/utilities/src/index.ts
  app/packages/utilities/src/styles.ts
  app/packages/utilities/vite.config.ts
  app/yarn.lock
Labels: app

#4635 Add missing Model interface imports to public namespace
  fiftyone/__public__.py
Labels: cleaning

#4634 Fix bug when loading HF transformers from zoo
  fiftyone/utils/transformers.py
Labels: bug

#4636 Support save contexts for generated views
  fiftyone/core/clips.py
  fiftyone/core/collections.py
  fiftyone/core/patches.py
  fiftyone/core/video.py
  tests/unittests/patches_tests.py
  tests/unittests/video_tests.py
Labels: bug, enhancement

#4431 Add documentation for Elasticsearch vector DB integration
  docs/source/_static/images/integrations/elasticsearch.jpg
  docs/source/index.rst
  docs/source/integrations/elasticsearch.rst
  docs/source/integrations/index.rst
  docs/source/user_guide/brain.rst
Labels: documentation

#4653 Cherry picking #4633 for release
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  tests/unittests/dataset_tests.py
Labels: enhancement

#4655 Improve/fix modal navigation
  app/packages/core/src/components/Grid/Grid.tsx
  app/packages/core/src/components/Grid/recoil.ts
  app/packages/core/src/components/Grid/useThreshold.ts
  app/packages/core/src/components/ImageContainerHeader.tsx
  app/packages/core/src/components/Sidebar/Entries/PathValueEntry.tsx
  app/packages/looker/src/elements/common/tags.ts
  app/packages/spotlight/package.json
  app/packages/spotlight/src/constants.ts
  app/packages/spotlight/src/createScrollReader.ts
  app/packages/spotlight/src/index.ts
  app/packages/spotlight/src/iter.ts
  app/packages/spotlight/src/row.ts
  app/packages/spotlight/src/section.ts
  app/packages/spotlight/src/types.ts
  app/packages/state/src/hooks/useExpandSample.ts
  app/packages/utilities/src/index.ts
  app/yarn.lock
  docs/source/images/app/app-clip-views1.gif
  docs/source/images/app/app-clip-views2.gif
Labels: bug, app

#4659 vitest cleanup
  app/package.json
  app/packages/components/package.json
  app/packages/core/package.json
  app/packages/embeddings/package.json
  app/packages/flashlight/package.json
  app/packages/looker-3d/package.json
  app/packages/looker/package.json
  app/packages/spotlight/package.json
  app/packages/state/package.json
  app/packages/utilities/package.json
  app/yarn.lock
Labels: app, dependencies

#4674 Fixing #4627
  fiftyone/utils/cvat.py
Labels: bug

#4673 prevent filter expansion resets from modal
  app/packages/app/src/routing/RouterContext.ts
  app/packages/core/src/components/Grid/useRefreshers.ts
  app/packages/relay/src/Writer.tsx
  app/packages/state/src/recoil/sidebarExpanded.ts
  e2e-pw/src/oss/poms/sidebar.ts
  e2e-pw/src/oss/specs/smoke-tests/quickstart.spec.ts
Labels: bug, app

#4676 Split modal/grid dynamic groups mode
  app/packages/core/src/components/Actions/GroupMediaVisibilityContainer.tsx
  app/packages/core/src/components/Actions/Options.tsx
  app/packages/core/src/components/Grid/useRefreshers.ts
  app/packages/core/src/components/Modal/Group/DynamicGroup/NestedGroup/index.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/NonNestedGroup/index.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/index.tsx
  app/packages/core/src/components/Modal/Group/DynamicGroup/useDynamicGroupSamples.ts
  app/packages/core/src/components/Modal/Looker.tsx
  app/packages/core/src/components/Modal/Modal.tsx
  app/packages/state/src/hooks/useCreateLooker.ts
  app/packages/state/src/hooks/useSetModalState.ts
  app/packages/state/src/recoil/dynamicGroups.ts
  app/packages/state/src/recoil/groups.ts
  app/packages/state/src/recoil/modal.ts
  app/packages/state/src/recoil/options.ts
Labels: enhancement, app

#4637 Python panel docs
  docs/source/cli/index.rst
  docs/source/images/plugins/plugin-design.png
  docs/source/plugins/developing_plugins.rst
  docs/source/plugins/index.rst
  fiftyone/core/cli.py
  fiftyone/operators/__init__.py
  fiftyone/operators/executor.py
  fiftyone/operators/operations.py
  fiftyone/operators/operator.py
  fiftyone/operators/panel.py
  fiftyone/operators/registry.py
  fiftyone/operators/server.py
  fiftyone/plugins/definitions.py
Labels: documentation

#4647 Release notes v0.25.0
  docs/source/deprecation.rst
  docs/source/images/plugins/panels/dashboard-panel.gif
  docs/source/plugins/developing_plugins.rst
  docs/source/plugins/index.rst
  docs/source/release-notes.rst
  docs/source/teams/management_sdk.rst
Labels: documentation

#4707 Docs lint
  docs/source/plugins/developing_plugins.rst
Labels: documentation

#4713 Fixing alpha docs
  fiftyone/core/collections.py
  fiftyone/core/models.py
  fiftyone/utils/patches.py
  fiftyone/utils/torch.py
Labels: documentation

#4715 Delegated outputs may be None
  fiftyone/operators/delegated.py
Labels: bug

#4735 Fix Keypoint filtering
  app/packages/state/src/recoil/pathFilters/index.test.ts
  app/packages/state/src/recoil/pathFilters/index.ts
Labels: bug, app

#4719 video-as-frames performance improvement: eagerly fetch images in addition to sample data
  app/packages/looker/src/elements/base.ts
  app/packages/looker/src/elements/common/actions.ts
  app/packages/looker/src/elements/imavid/index.ts
  app/packages/looker/src/elements/imavid/play-button.ts
  app/packages/looker/src/elements/imavid/playback-rate.ts
  app/packages/looker/src/lookers/imavid/constants.ts
  app/packages/looker/src/lookers/imavid/controller.ts
  app/packages/looker/src/lookers/imavid/ima-vid-frame-samples.ts
  app/packages/looker/src/lookers/imavid/index.ts
  app/packages/looker/src/state.ts
  app/packages/state/src/utils.ts
Labels: app

#4745 Fix sidebar state persistence
  app/packages/app/src/pages/datasets/__generated__/DatasetPageQuery.graphql.ts
  app/packages/relay/src/fragments/__generated__/sidebarGroupsFragment.graphql.ts
  app/packages/relay/src/fragments/sidebarGroupsFragment.ts
  app/packages/relay/src/graphQLSyncFragmentAtomFamily.ts
  app/packages/relay/src/queries/__generated__/datasetQuery.graphql.ts
  app/packages/state/src/hooks/useSetModalState.ts
  app/packages/state/src/recoil/sidebar.ts
  app/packages/state/src/recoil/sidebarExpanded.ts
  e2e-pw/src/oss/specs/smoke-tests/quickstart.spec.ts
Labels: bug, app

#4754 Fix bug with group_by(..., match_expr=)
  fiftyone/core/stages.py
  tests/unittests/group_tests.py
Labels: bug

#4739 Fix sample selection with map panel
  app/packages/core/src/components/Grid/Grid.tsx
  app/packages/core/src/components/Grid/useRecords.test.ts
  app/packages/core/src/components/Grid/useRecords.ts
  app/packages/core/src/components/Grid/useSelect.ts
  app/packages/core/src/components/Grid/useSelectSample.test.ts
  app/packages/core/src/components/Grid/useSelectSample.ts
  app/packages/core/src/components/Grid/useSpotlightPager.ts
Labels: bug, app
