Repository voxel51/fiftyone, pull requests merged in 2024-09, with the labels that each got.

#4767 Release notes for v0.25.1
  docs/source/release-notes.rst
Labels: documentation

#4787 Support large deletions by sample/frame IDs
  fiftyone/core/dataset.py
Labels: bug

#4757 Lightning filter fixes
  app/packages/core/src/components/Filters/StringFilter/Checkboxes.tsx
  app/packages/core/src/components/Filters/StringFilter/useSelected.ts
  app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry/FilterItem.tsx
  app/packages/state/src/recoil/lightning.test.ts
  app/packages/state/src/recoil/lightning.ts
Labels: bug, app

#4791 Remove App-only note
  docs/source/teams/roles_and_permissions.rst
Labels: documentation, cleaning

#4781 Update labelstudio docs for multilabel classification
  docs/source/integrations/labelstudio.rst
Labels: documentation, annotation

#4772 Timeline API
  app/packages/core/package.json
  app/packages/core/src/components/Modal/Modal.tsx
  app/packages/core/src/components/Modal/ModalNavigation.tsx
  app/packages/looker-3d/src/state.ts
  app/packages/looker/package.json
  app/packages/looker/src/lookers/imavid/ima-vid-frame-samples.ts
  app/packages/looker/src/lookers/imavid/store.ts
  app/packages/looker/src/lookers/video.ts
  app/packages/playback/eslint.config.mjs
  app/packages/playback/index.ts
  app/packages/playback/package.json
  app/packages/playback/src/context.tsx
  app/packages/playback/src/lib/constants.ts
  app/packages/playback/src/lib/state.ts
  app/packages/playback/src/lib/use-create-timeline.ts
  app/packages/playback/src/lib/use-default-timeline-name.ts
  app/packages/playback/src/lib/use-frame-number.ts
  app/packages/playback/src/lib/use-timeline-viz-utils.ts
  app/packages/playback/src/lib/use-timeline.ts
  app/packages/playback/src/views/PlaybackElements.tsx
  app/packages/playback/src/views/Timeline.tsx
  app/packages/playback/src/views/svgs/buffering.svg
  app/packages/playback/src/views/svgs/pause.svg
  app/packages/playback/src/views/svgs/play.svg
  app/packages/playback/src/views/svgs/speed.svg
  app/packages/playback/src/vite-env.d.ts
  app/packages/playback/tsconfig.json
  app/packages/playback/vite.config.ts
  app/packages/spaces/src/components/Panel.tsx
  app/packages/state/src/hooks/hooks-utils.ts
  app/packages/state/src/hooks/index.ts
  app/packages/state/src/hooks/useLookerStore.ts
  app/packages/state/src/index.ts
  app/packages/state/src/jotai/index.ts
  app/packages/state/src/jotai/jotai-store.ts
  app/packages/state/src/recoil/modal.ts
  app/packages/state/src/utils-types.ts
  app/packages/utilities/src/buffer-manager/buffer-manager.test.ts
  app/packages/utilities/src/buffer-manager/index.ts
  app/yarn.lock
Labels: feature, app

#4597 Adding `created_at`, `last_modified_at`, and read-only fields
  docs/source/cheat_sheets/views_cheat_sheet.rst
  docs/source/integrations/coco.rst
  docs/source/user_guide/app.rst
  docs/source/user_guide/basics.rst
  docs/source/user_guide/evaluation.rst
  docs/source/user_guide/groups.rst
  docs/source/user_guide/using_datasets.rst
  docs/source/user_guide/using_views.rst
  e2e-pw/src/oss/specs/plugins/histograms.spec.ts
  fiftyone/core/clips.py
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/fields.py
  fiftyone/core/frame.py
  fiftyone/core/odm/dataset.py
  fiftyone/core/odm/document.py
  fiftyone/core/odm/embedded_document.py
  fiftyone/core/odm/frame.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/odm/sample.py
  fiftyone/core/odm/utils.py
  fiftyone/core/patches.py
  fiftyone/core/stages.py
  fiftyone/core/utils.py
  fiftyone/core/video.py
  fiftyone/core/view.py
  fiftyone/migrations/revisions/v1_0_0.py
  fiftyone/utils/data/importers.py
  tests/unittests/dataset_tests.py
  tests/unittests/group_tests.py
  tests/unittests/import_export_tests.py
  tests/unittests/index_tests.py
  tests/unittests/patches_tests.py
  tests/unittests/run_tests.py
  tests/unittests/video_tests.py
  tests/unittests/view_tests.py
Labels: feature

#4752 Adding support for remotely-sourced zoo datasets
  docs/source/cli/index.rst
  docs/source/plugins/developing_plugins.rst
  docs/source/user_guide/dataset_zoo/api.rst
  docs/source/user_guide/dataset_zoo/datasets.rst
  docs/source/user_guide/dataset_zoo/index.rst
  docs/source/user_guide/dataset_zoo/remote.rst
  fiftyone/core/cli.py
  fiftyone/plugins/core.py
  fiftyone/zoo/datasets/__init__.py
Labels: feature

#4747 Scale grid text
  app/packages/core/src/components/Grid/Grid.tsx
  app/packages/core/src/components/Grid/useFontSize.ts
  app/packages/core/src/components/Grid/useSelect.ts
  app/packages/looker/src/elements/common/tags.module.css
  app/packages/looker/src/elements/common/tags.ts
  app/packages/looker/src/state.ts
  app/packages/state/src/hooks/useCreateLooker.ts
  e2e-pw/src/oss/specs/grid-tagging.spec.ts-snapshots/grid-tagged-chromium-darwin.png
  e2e-pw/src/oss/specs/grid-tagging.spec.ts-snapshots/grid-tagged-chromium-linux.png
  e2e-pw/src/oss/specs/grid-tagging.spec.ts-snapshots/grid-untagged-chromium-darwin.png
  e2e-pw/src/oss/specs/grid-tagging.spec.ts-snapshots/grid-untagged-chromium-linux.png
  e2e-pw/src/oss/specs/sidebar/sidebar-cifar.spec.ts-snapshots/hide-ship-chromium-darwin.png
  e2e-pw/src/oss/specs/sidebar/sidebar-cifar.spec.ts-snapshots/hide-ship-invisible-cat-chromium-darwin.png
  e2e-pw/src/oss/specs/sidebar/sidebar-cifar.spec.ts-snapshots/hide-ship-visible-cat-chromium-linux.png
  e2e-pw/src/oss/specs/sidebar/sidebar-cifar.spec.ts-snapshots/not-visible-cat-chromium-darwin.png
  e2e-pw/src/oss/specs/sidebar/sidebar-cifar.spec.ts-snapshots/not-visible-cat-chromium-linux.png
Labels: enhancement, app

#4789 Fix selection for group modal
  fiftyone/server/view.py
  tests/unittests/server_group_tests.py
Labels: bug, app

#4803 fix modal navigation bug
  app/packages/core/src/components/Modal/Modal.tsx
  app/packages/core/src/components/Modal/ModalNavigation.tsx
  app/packages/core/src/components/Modal/ModalSamplePlugin.tsx
Labels: bug

#4815 Add date fields to primitives sidebar group
  fiftyone/core/odm/dataset.py
Labels: bug

#4763 Improve colorscheme ux
  app/packages/core/src/components/ColorModal/colorPalette/Colorscale.tsx
  app/packages/core/src/components/ColorModal/colorPalette/DefaultMaskTargets.tsx
  app/packages/core/src/components/ColorModal/colorPalette/FieldsMaskTarget.tsx
  app/packages/core/src/components/ColorModal/colorPalette/GlobalColorscale.tsx
  app/packages/core/src/components/ColorModal/controls/ColorscaleList.tsx
  app/packages/core/src/components/ColorModal/controls/IdxColorList.tsx
  app/packages/core/src/components/ColorModal/controls/ManualColorScaleList.tsx
  app/packages/core/src/components/ColorModal/utils.ts
  app/packages/core/src/components/Common/Input.tsx
  docs/source/user_guide/app.rst
  docs/source/user_guide/using_datasets.rst
  fiftyone/core/odm/dataset.py
  fiftyone/core/plots/plotly.py
  setup.py
Labels: documentation, enhancement, app

#4822 Hotfix pymongo
  docs/source/release-notes.rst
  docs/source/user_guide/dataset_creation/datasets.rst
  fiftyone/utils/dicom.py
  requirements/test.txt
  setup.py
Labels: release

#4832 Remove deprecated methods for 1.0
  fiftyone/core/dataset.py
Labels: cleaning

#4818 Migrating zoo/brain docs to top-level
  README.md
  docs/source/brain.rst
  docs/source/dataset_zoo/api.rst
  docs/source/dataset_zoo/datasets.rst
  docs/source/dataset_zoo/index.rst
  docs/source/dataset_zoo/remote.rst
  docs/source/index.rst
  docs/source/integrations/albumentations.rst
  docs/source/model_zoo/api.rst
  docs/source/model_zoo/design.rst
  docs/source/model_zoo/index.rst
  docs/source/model_zoo/models.rst
  docs/source/model_zoo/remote.rst
  docs/source/redirects
  docs/source/user_guide/index.rst
Labels: documentation

#4830 Adding builtin operators for more of the FO interface
  docs/source/brain.rst
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/migrations/revisions/v1_0_0.py
  fiftyone/operators/builtin.py
  tests/unittests/dataset_tests.py
Labels: feature

#4841 Summary fields should support frame-level input paths
  fiftyone/operators/builtin.py
Labels: bug

#4836 Persist current slice during group modal navigation
  app/packages/state/src/hooks/useSetExpandedSample.ts
  e2e-pw/src/oss/specs/smoke-tests/quickstart-groups.spec.ts
Labels: bug, app

#4852 Fix RGB mask targets when hex color codes are lowercase
  app/packages/state/src/utils.test.ts
  app/packages/state/src/utils.ts
Labels: bug, app

#4854 No monkey business
  fiftyone/core/odm/document.py
Labels: bug

#4861 Make v1.0.0 migration robust to in-progress terminations
  fiftyone/migrations/revisions/v1_0_0.py
Labels: enhancement

#4865 Better heatmap range handling
  app/packages/looker/src/overlays/heatmap.ts
  app/packages/looker/src/worker/painter.test.ts
  app/packages/looker/src/worker/painter.ts
Labels: bug, app

#4839 Release notes v1.0.0
  docs/scripts/make_model_zoo_docs.py
  docs/source/deprecation.rst
  docs/source/images/datasets/quickstart-video-summary-fields.gif
  docs/source/index.rst
  docs/source/plugins/developing_plugins.rst
  docs/source/release-notes.rst
  docs/source/user_guide/using_datasets.rst
Labels: documentation
