Repository voxel51/fiftyone, pull requests merged in 2025-07, with the labels that each got.

#6088 Handle different drives on Windows
  fiftyone/core/utils.py
  fiftyone/plugins/context.py
  fiftyone/plugins/definitions.py
  fiftyone/zoo/datasets/__init__.py
  fiftyone/zoo/models/__init__.py
  tests/unittests/utils_tests.py
Labels: bug

#6094 Parse label attributes as lists when loading from CVAT
  fiftyone/utils/cvat.py
Labels: bug, annotation

#6129 Bugfix: fully support frame patch embeddings in Embeddings panel
  app/packages/embeddings/src/useColorByChoices.tsx
  fiftyone/server/routes/embeddings.py
Labels: bug

#6131 Ultralytics: return empty labels, not None, when no objects are found
  fiftyone/utils/ultralytics.py
Labels: bug

#6138 Fix #6137: use named function to avoid pickle error
  fiftyone/core/models.py
Labels: bug

#6163 Fix CVAT bug with rotation attribute of 3d labels
  fiftyone/utils/cvat.py
Labels: bug, annotation

#6149 FOEPD-1759: Add optimized syntaxes for `set_values()`, `set_label_values()` and `map_values()`
  docs/source/user_guide/using_datasets.rst
  fiftyone/core/collections.py
  fiftyone/utils/data/base.py
  plugins/operators/__init__.py
  tests/unittests/utils_tests.py
  tests/unittests/view_tests.py
Labels: bug, feature

#6168 dynamic groups and 3d misc bug fixes FOEPD-1784, FOEPD-1723, FOEPD-1722, FOEPD-1721
  app/packages/looker-3d/package.json
  app/packages/looker-3d/src/fo3d/MediaTypeFo3d.tsx
  app/packages/looker-3d/src/fo3d/scene-controls/SceneControls.tsx
  app/packages/state/src/recoil/aggregations.ts
  app/yarn.lock
Labels: bug, app
