Repository voxel51/fiftyone, pull requests merged in 2025-08, with the labels that each got.

#6244 Optmize inline code font size
  docs/source/_static/css/custom.css
  docs/source/assets/styles/components/_code.sass
Labels: documentation

#6242 Increase font sizes on CTAs and tab headings
  docs/source/_static/css/custom.css
  docs/source/assets/styles/components/_buttons.sass
  docs/source/assets/styles/components/_tabs.sass
Labels: documentation

#6241 Make tables fit to div width (and bring back alternating row styling)
  docs/source/_static/css/custom.css
  docs/source/assets/styles/base/_variables.scss
  docs/source/assets/styles/components/_tables.sass
Labels: documentation

#6254 FOEPD-1823 apply color after transformation of up vector
  app/packages/looker-3d/src/fo3d/mesh/Ply.tsx
  app/packages/looker-3d/src/fo3d/point-cloud/Pcd.tsx
  app/packages/looker-3d/src/fo3d/point-cloud/use-pcd-material.tsx
  app/packages/looker-3d/src/hooks/use-point-cloud-hover.tsx
  app/packages/looker-3d/src/labels/polygon-fill-utils.test.ts
  app/packages/looker-3d/src/labels/polygon-fill-utils.ts
  app/packages/looker-3d/src/labels/polyline.tsx
  app/packages/looker-3d/src/renderables/pcd/shaders/components.tsx
  app/packages/looker-3d/src/renderables/pcd/shaders/glsl.ts
  app/packages/looker-3d/src/renderables/pcd/shaders/types.ts
Labels: app

#6274 Use `get_mask()` to retrieve instance segmentations
  fiftyone/utils/cvat.py
  fiftyone/utils/iou.py
Labels: bug
