Repository voxel51/fiftyone, pull requests merged in 2025-06, with the labels that each got.

#5956 Add support for deleting all visible labels in selected samples
  docs/source/plugins/developing_plugins.rst
  fiftyone/core/clips.py
  fiftyone/core/collections.py
  fiftyone/core/patches.py
  fiftyone/core/video.py
  fiftyone/operators/executor.py
  fiftyone/operators/operations.py
  plugins/operators/__init__.py
  tests/unittests/patches_tests.py
  tests/unittests/video_tests.py
Labels: feature

#6001 fix frame field support type rendering bug
  app/packages/looker/src/elements/common/tags.ts
Labels: bug, app

#5995 add docs for dynamic pcd work
  docs/source/images/app/pcd-dynamic-coloring.gif
  docs/source/images/app/pcd-thresholding.gif
  docs/source/user_guide/app.rst
Labels: documentation
