Repository voxel51/fiftyone, pull requests merged in 2025-03, with the labels that each got.

#5214 Grid LRU caching with Looker size estimates
  app/packages/components/src/components/Toast/Toast.tsx
  app/packages/core/package.json
  app/packages/core/src/components/Actions/Options.tsx
  app/packages/core/src/components/Grid/Grid.module.css
  app/packages/core/src/components/Grid/Grid.tsx
  app/packages/core/src/components/Grid/recoil.ts
  app/packages/core/src/components/Grid/types.ts
  app/packages/core/src/components/Grid/useAt.ts
  app/packages/core/src/components/Grid/useEvents.ts
  app/packages/core/src/components/Grid/useLabelVisibility.ts
  app/packages/core/src/components/Grid/useLookerCache.ts
  app/packages/core/src/components/Grid/useRefreshers.ts
  app/packages/core/src/components/Grid/useRenderer.ts
  app/packages/core/src/components/Grid/useResize.ts
  app/packages/core/src/components/Grid/useSelect.ts
  app/packages/core/src/components/Grid/useSelectSample.ts
  app/packages/core/src/components/Grid/useSpotlightPager.ts
  app/packages/core/src/components/Grid/useUpdates.ts
  app/packages/core/src/components/Sidebar/syncAndGetNewLabels.ts
  app/packages/core/src/components/Sidebar/useDetectNewActiveLabelFields.ts
  app/packages/core/src/components/Snackbar.tsx
  app/packages/core/src/utils/links.ts
  app/packages/core/src/vite-env.d.ts
  app/packages/looker/src/cache.test.ts
  app/packages/looker/src/cache.ts
  app/packages/looker/src/elements/common/canvas.ts
  app/packages/looker/src/elements/video.ts
  app/packages/looker/src/index.ts
  app/packages/looker/src/lookers/abstract.ts
  app/packages/looker/src/lookers/video.ts
  app/packages/spotlight/src/constants.ts
  app/packages/spotlight/src/createScrollReader.ts
  app/packages/spotlight/src/events.ts
  app/packages/spotlight/src/index.ts
  app/packages/spotlight/src/row.ts
  app/packages/spotlight/src/section.ts
  app/packages/spotlight/src/styles.module.css
  app/packages/spotlight/src/tile.test.ts
  app/packages/spotlight/src/types.ts
  app/packages/spotlight/src/utilities.ts
  app/packages/state/src/labelsVisibility.ts
  app/packages/utilities/src/index.ts
  app/packages/utilities/src/size-bytes-estimate.ts
  app/yarn.lock
Labels: feature, app

#5531 Hide sidebar sorting option for Query Performance
  app/packages/core/src/components/Actions/Options.tsx
Labels: bug, app

#5537 Looker cache "frozen" fixes
  app/packages/core/src/components/Grid/useRenderer.ts
  app/packages/looker/src/cache.test.ts
  app/packages/looker/src/cache.ts
  app/packages/spotlight/src/index.ts
Labels: bug, app

#5540 treat detections as non-dense by default
  app/packages/state/src/labelsVisibility.test.ts
  app/packages/utilities/src/schema.ts
  e2e-pw/package.json
  e2e-pw/src/oss/poms/grid/index.ts
  e2e-pw/src/oss/specs/sidebar/sidebar.spec.ts
  e2e-pw/src/oss/specs/smoke-tests/tagger.spec.ts
  e2e-pw/yarn.lock
Labels: app

#5542 fix tooltip and make label render status hidden field
  app/packages/core/src/components/Grid/useUpdates.ts
  app/packages/looker/src/overlays/base.ts
  app/packages/looker/src/overlays/detection.ts
  app/packages/looker/src/worker/deserializer.ts
  app/packages/looker/src/worker/disk-overlay-decoder.ts
  app/packages/looker/src/worker/index.ts
  app/packages/looker/src/worker/painter.ts
Labels: bug

#5533 Fix session's selected labels
  fiftyone/core/session/session.py
  tests/unittests/session_events_tests.py
Labels: bug, app

#5554 Fix recomputing frames on a video dataset
  fiftyone/core/collections.py
  fiftyone/core/odm/mixins.py
  tests/unittests/video_tests.py
Labels: bug

#5562 Fix YOLO kwargs syntax
  docs/source/integrations/ultralytics.rst
Labels: bug

#5538 Optimize Query Performance counts with count scans
  app/packages/relay/src/fragments/__generated__/estimatedCountsFragment.graphql.ts
  app/packages/relay/src/queries/__generated__/aggregationsQuery.graphql.ts
  app/packages/state/src/recoil/aggregations.ts
  app/schema.graphql
  fiftyone/core/aggregations.py
  fiftyone/server/aggregations.py
  tests/unittests/server_aggregations_tests.py
Labels: bug

#5586 Fix #5570 full schema merges
  fiftyone/core/odm/mixins.py
  tests/unittests/import_export_tests.py
Labels: bug

#5582 Add support for patching samples with serialized values
  fiftyone/core/odm/document.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/odm/utils.py
  tests/unittests/sample_tests.py
Labels: enhancement

#5561 Adding `map_values()` stage and `edit_field_values` operator
  docs/source/user_guide/using_aggregations.rst
  docs/source/user_guide/using_views.rst
  fiftyone/__public__.py
  fiftyone/core/collections.py
  fiftyone/core/expressions.py
  fiftyone/core/stages.py
  plugins/operators/__init__.py
  plugins/operators/fiftyone.yml
  tests/unittests/view_tests.py
Labels: feature

#5587 Add support for listing operators with glob pattern via CLI
  docs/source/cli/index.rst
  fiftyone/core/cli.py
Labels: enhancement

#5321 Add FiftyOneTorchDataset
  docs/source/recipes/torch-dataset-examples/basic_example.ipynb
  docs/source/recipes/torch-dataset-examples/ddp_train.py
  docs/source/recipes/torch-dataset-examples/mnist_training.py
  docs/source/recipes/torch-dataset-examples/simple_training_example.ipynb
  docs/source/recipes/torch-dataset-examples/the_cache_field_names_argument.ipynb
  docs/source/recipes/torch-dataset-examples/utils.py
  fiftyone/core/collections.py
  fiftyone/utils/torch.py
Labels: feature

#5602 Cherry pick runs docs edits from #5550
  docs/source/enterprise/plugins.rst
  docs/source/images/plugins/operators/runs/edit_label.png
  docs/source/images/plugins/operators/runs/errors.png
  docs/source/images/plugins/operators/runs/failed.png
  docs/source/images/plugins/operators/runs/filter_by_status.png
  docs/source/images/plugins/operators/runs/input.png
  docs/source/images/plugins/operators/runs/logs_configure_not_setup.png
  docs/source/images/plugins/operators/runs/logs_download_preview_pane.png
  docs/source/images/plugins/operators/runs/logs_download_runs_list_kebab.png
  docs/source/images/plugins/operators/runs/logs_general.png
  docs/source/images/plugins/operators/runs/logs_general_with_columns.png
  docs/source/images/plugins/operators/runs/logs_not_available_general.png
  docs/source/images/plugins/operators/runs/logs_not_available_pre_completion.png
  docs/source/images/plugins/operators/runs/logs_too_large.png
  docs/source/images/plugins/operators/runs/mark_as_failed.png
  docs/source/images/plugins/operators/runs/my_runs.png
  docs/source/images/plugins/operators/runs/output.png
  docs/source/images/plugins/operators/runs/pinning.png
  docs/source/images/plugins/operators/runs/raw_input.png
  docs/source/images/plugins/operators/runs/re_run.png
  docs/source/images/plugins/operators/runs/run_error.png
  docs/source/images/plugins/operators/runs/run_input_general.png
  docs/source/images/plugins/operators/runs/run_input_raw.png
  docs/source/images/plugins/operators/runs/run_output.png
  docs/source/images/plugins/operators/runs/run_pinning.png
  docs/source/images/plugins/operators/runs/run_progress.png
  docs/source/images/plugins/operators/runs/run_re_run.png
  docs/source/images/plugins/operators/runs/run_rename.png
  docs/source/images/plugins/operators/runs/run_view.png
  docs/source/images/plugins/operators/runs/runs_general.png
  docs/source/images/plugins/operators/runs/runs_hover_queued.png
  docs/source/images/plugins/operators/runs/runs_hover_scheduled.png
  docs/source/images/plugins/operators/runs/runs_mark_as_failed.png
  docs/source/images/plugins/operators/runs/runs_my_vs_all.png
  docs/source/images/plugins/operators/runs/runs_page.png
  docs/source/images/plugins/operators/runs/runs_pinned_sidebar.png
  docs/source/images/plugins/operators/runs/runs_progress_enabled.png
  docs/source/images/plugins/operators/runs/runs_running_basic.png
  docs/source/images/plugins/operators/runs/runs_search.png
  docs/source/images/plugins/operators/runs/runs_sorting.png
  docs/source/images/plugins/operators/runs/runs_statuses.png
  docs/source/images/plugins/operators/runs/runs_this_vs_all.png
  docs/source/images/plugins/operators/runs/search_by_name.png
  docs/source/images/plugins/operators/runs/sort.png
  docs/source/images/plugins/operators/runs/view.png
Labels: documentation

#5457 CVAT: Upload detection rotation attribute
  fiftyone/utils/cvat.py
Labels: annotation

#5601 selective labels rendering pass
  app/packages/core/src/components/ColorModal/controls/RefreshColor.tsx
  app/packages/core/src/components/Grid/useUpdates.ts
  app/packages/core/src/components/Sidebar/useDetectNewActiveLabelFields.ts
  app/packages/core/src/components/utils.tsx
  app/packages/looker/src/lookers/abstract.ts
  app/packages/looker/src/lookers/frame.ts
  app/packages/looker/src/lookers/image.ts
  app/packages/looker/src/lookers/imavid/index.ts
  app/packages/looker/src/lookers/three-d.ts
  app/packages/looker/src/lookers/video.ts
  app/packages/looker/src/overlays/detection.ts
  app/packages/looker/src/state.ts
  app/packages/looker/src/worker/async-labels-rendering-manager.ts
  app/packages/looker/src/worker/index.ts
  e2e-pw/src/oss/specs/groups/ima-vid.spec.ts
Labels: app

#5458 Support 3D object detection annotation on pcd files with CVAT
  docs/source/integrations/cvat.rst
  fiftyone/utils/cvat.py
Labels: annotation

#5654 Fix map samples batch unit test
  tests/unittests/map/batcher/test_id_batch.py
Labels: bug

#5662 Gracefully handle None in `edit_field_values`
  plugins/operators/__init__.py
Labels: bug
