Repository voxel51/fiftyone, pull requests merged in 2025-04, with the labels that each got.

#5685 Fix built-in sort by similarity for patches views
  app/packages/core/src/components/Actions/similar/utils.ts
  app/packages/state/src/hooks/useLookerStore.ts
Labels: bug, app

#5684 Override modal tagging when a sample selection is present
  app/packages/core/src/components/Actions/utils.test.ts
  app/packages/core/src/components/Actions/utils.tsx
Labels: bug, app

#5683 Fix modal video tagging
  app/packages/core/src/components/Grid/useSpotlightPager.ts
  app/packages/core/src/components/Grid/utils.test.ts
  app/packages/core/src/components/Grid/utils.ts
  app/packages/state/src/recoil/looker.ts
Labels: bug, app

#5697 Fix #5335: missing false positives in detection evaluations when classwise=False
  fiftyone/utils/eval/coco.py
  fiftyone/utils/eval/openimages.py
  fiftyone/utils/iou.py
  tests/unittests/evaluation_tests.py
Labels: bug

#5663 Add support for listing schemas without traversing embedded list fields
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/fields.py
  fiftyone/core/odm/mixins.py
  fiftyone/core/view.py
  fiftyone/utils/annotations.py
  tests/unittests/dataset_tests.py
Labels: enhancement

#5665 Must now use `add_samples()` and `_upsert_samples()` directly
  fiftyone/utils/beam.py
Labels: bug

#5738 Correctly handle existing files when using `UniqueFilenameMaker` with `ignore_exts=True`
  fiftyone/core/utils.py
Labels: bug

#5745 Add torch packages to test requirements
  fiftyone/utils/torch.py
  requirements/test.txt
  tests/unittests/torch_dataset_tests.py
Labels: bug

#5705 Optimize frame lookups to be as late as possible in aggregations
  fiftyone/core/aggregations.py
  fiftyone/core/collections.py
  fiftyone/core/stages.py
  fiftyone/core/view.py
  tests/unittests/aggregation_tests.py
  tests/unittests/server_samples_tests.py
Labels: enhancement

#5723 Automatically update `last_modified_at` when deleting samples/frames
  fiftyone/core/dataset.py
  fiftyone/core/frame.py
  fiftyone/core/odm/document.py
  fiftyone/core/sample.py
  fiftyone/core/singletons.py
  tests/unittests/dataset_tests.py
  tests/unittests/video_tests.py
Labels: enhancement

#5730 Optimize `split_labels()` and `delete_labels()`
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  tests/unittests/view_tests.py
Labels: bug, enhancement

#5577 Labels correspondence
  app/packages/core/src/components/Modal/Modal.tsx
  app/packages/core/src/components/Modal/ModalNavigation.tsx
  app/packages/core/src/components/Modal/TooltipInfo.tsx
  app/packages/looker-3d/package.json
  app/packages/looker-3d/src/constants.ts
  app/packages/looker-3d/src/hooks/use-3d-label-color.ts
  app/packages/looker-3d/src/hooks/use-fo-loaders.ts
  app/packages/looker-3d/src/hooks/use-similar-labels-3d.ts
  app/packages/looker-3d/src/labels/cuboid.tsx
  app/packages/looker-3d/src/labels/index.tsx
  app/packages/looker-3d/src/labels/line.tsx
  app/packages/looker-3d/src/labels/loader.ts
  app/packages/looker-3d/src/labels/polyline.tsx
  app/packages/looker-3d/src/labels/shared.tsx
  app/packages/looker/src/constants.ts
  app/packages/looker/src/elements/common/actions.ts
  app/packages/looker/src/elements/common/canvas.ts
  app/packages/looker/src/elements/common/util.ts
  app/packages/looker/src/index.ts
  app/packages/looker/src/lookers/abstract.ts
  app/packages/looker/src/lookers/video.ts
  app/packages/looker/src/overlays/base.ts
  app/packages/looker/src/overlays/detection.ts
  app/packages/looker/src/selective-rendering-events.ts
  app/packages/looker/src/state.ts
  app/packages/operators/src/operators.ts
  app/packages/playback/src/lib/state.ts
  app/packages/relay/src/mutations/__generated__/createSavedViewMutation.graphql.ts
  app/packages/relay/src/mutations/__generated__/setSelectedLabelsMutation.graphql.ts
  app/packages/relay/src/mutations/__generated__/setViewMutation.graphql.ts
  app/packages/relay/src/queries/__generated__/aggregationsQuery.graphql.ts
  app/packages/state/src/hooks/useCreateLooker.ts
  app/packages/state/src/hooks/useOnSelectLabel.ts
  app/packages/state/src/hooks/useOnShiftClickLabel.ts
  app/packages/state/src/hooks/useTooltip.ts
  app/packages/state/src/jotai/index.ts
  app/packages/state/src/recoil/types.ts
  app/schema.graphql
  app/yarn.lock
  e2e-pw/src/oss/poms/field-visibility/field-visibility.ts
  e2e-pw/src/oss/specs/smoke-tests/field-visibility.spec.ts
  fiftyone/__public__.py
  fiftyone/core/fields.py
  fiftyone/core/labels.py
  fiftyone/core/session/events.py
  fiftyone/server/inputs.py
  fiftyone/server/routes/__init__.py
  fiftyone/server/routes/get_similar_labels_frames.py
  fiftyone/server/view.py
  tests/unittests/dataset_tests.py
  tests/unittests/server_lightning_tests.py
Labels: feature, app

#5789 Pin PIP version for windows in GitHub Action
  .github/workflows/windows-test.yml
Labels: bug

#5769 Move build App step in install script
  install.bash
  install.bat
Labels: bug, installation

#5666 Add support for adding samples as a generator
  fiftyone/core/dataset.py
  fiftyone/utils/data/importers.py
  fiftyone/utils/data/parsers.py
  tests/unittests/dataset_tests.py
Labels: enhancement

#5724 Bug fix: renaming evaluations with custom metrics
  fiftyone/utils/eval/base.py
  fiftyone/utils/eval/classification.py
  fiftyone/utils/eval/detection.py
  fiftyone/utils/eval/regression.py
  fiftyone/utils/eval/segmentation.py
  tests/unittests/decorators.py
  tests/unittests/evaluation_plugins/__init__.py
  tests/unittests/evaluation_plugins/fiftyone.yml
  tests/unittests/evaluation_tests.py
Labels: bug

#5785 Add support for setting new embedded document fields
  fiftyone/core/odm/mixins.py
  tests/unittests/dataset_tests.py
  tests/unittests/view_tests.py
Labels: enhancement
