Repository voxel51/fiftyone, pull requests merged in 2025-05, with the labels that each got.

#5863 Editing pass over 1.5/2.8 docs
  docs/source/_includes/substitutions.rst
  docs/source/deprecation.rst
  docs/source/plugins/developing_plugins.rst
  docs/source/release-notes.rst
  docs/source/user_guide/app.rst
  docs/source/user_guide/config.rst
  docs/source/user_guide/groups.rst
  docs/source/user_guide/using_datasets.rst
Labels: documentation

#5704 Add support for merging embedded document fields
  fiftyone/core/collections.py
  fiftyone/core/dataset.py
  fiftyone/core/document.py
  fiftyone/core/frame.py
  fiftyone/core/sample.py
  fiftyone/utils/data/importers.py
  tests/unittests/dataset_tests.py
Labels: feature

#5867 Fix ordered compound grouping
  fiftyone/core/stages.py
  tests/unittests/group_tests.py
Labels: bug

#5872 Do not require read access to admin database
  fiftyone/core/odm/database.py
  tests/unittests/fcv_tests.py
Labels: bug

#5865 Simplify requirements
  install.bash
  requirements.txt
  requirements/common.txt
  requirements/dev.txt
  requirements/github.txt
  requirements/prod.txt
Labels: cleaning

#5884 Update UniqueFilenameMaker
  fiftyone/core/utils.py
  tests/unittests/utils/test_unique_filename_maker.py
Labels: bug

#5894 Apply confidence to Keypoint instances correctly
  fiftyone/core/labels.py
  fiftyone/core/sample.py
  fiftyone/utils/torch.py
Labels: bug

#5885 Resolve CVAT v2.31.0+ compatibility issue
  docs/source/integrations/cvat.rst
  fiftyone/utils/cvat.py
Labels: bug, annotation

#5895 Tweak ultralytics batch inference docs
  docs/source/integrations/ultralytics.rst
Labels: documentation

#5926 Fix bug with `GroupDatasetImporter`s that use `has_sample_field_schema=True`
  docs/source/user_guide/dataset_creation/datasets.rst
  fiftyone/utils/data/importers.py
Labels: bug

#5925 fix imavid sources big
  app/packages/looker/src/lookers/imavid/index.ts
Labels: bug

#5927 Avoid duplicate filenames when uploading to CVAT
  fiftyone/utils/cvat.py
Labels: bug

#5953 Add support for storing instance segmentations on disk in `apply_model()`
  fiftyone/core/models.py
Labels: bug

#5957 Map samples: use `deque`, `reload()`, and `fo.config`
  fiftyone/core/collections.py
  fiftyone/core/map/__init__.py
  fiftyone/core/map/factory.py
  tests/unittests/map/test_factory.py
  tests/unittests/map/test_implementations.py
Labels: enhancement

#5944 labels-correspondence app follow-up work
  app/packages/core/src/components/Modal/Modal.tsx
  app/packages/core/src/components/Modal/TooltipInfo.tsx
  app/packages/looker-3d/src/state.ts
  app/packages/looker/src/elements/common/util.ts
  app/packages/looker/src/overlays/detection.ts
  app/packages/looker/src/overlays/index.test.ts
  app/packages/looker/src/overlays/util.ts
  app/packages/looker/src/worker/painter.ts
  app/packages/state/src/jotai/index.ts
  app/packages/state/src/recoil/modal.ts
  e2e-pw/src/oss/fixtures/index.ts
Labels: app

#5971 Gracefully handle a single unique datetime value in `histogram_values()`
  fiftyone/core/aggregations.py
  tests/unittests/aggregation_tests.py
Labels: bug
